// The propositional logic translations were likely generated programatically by Gensler.
// TODO: Create a program that generates easy translations, four options and the solution.
// TODO: Create a program that gives hints based on the mistaken option (There's always a pattern!)

const feedback_single_person =
  'stands for a single person, and so translates into a small letter.';

export interface Option {
  id: number;
  label: string;
}

export interface Question {
  id: string;
  prompt: string;
  options: Option[];
  correctId: number[];
  answer: string;
}

export interface Chapter {
  set: string;
  isNew?: boolean;
  slugs: string[];
  id: number;
  title: string;
  header: string;
  questions: Question[];
}

const chapters = [
  {
    set: 'Set A',
    slugs: ['syllogistic', 'translations'],
    isNew: true,
    id: 1,
    title: 'Syllogistic Translations: Easy',
    header: 'Translates into logic as:',
    questions: [
      {
        id: '1.1',
        prompt: "You aren't the cleanest biologist.",
        options: [
          { id: 0, label: 'u is not B' },
          { id: 1, label: 'U is not b' },
          { id: 2, label: 'U is not B' },
          { id: 3, label: 'u is not b' },
        ],
        correctId: [3],
        answer: '',
      },
      {
        id: '1.2',
        prompt: "You aren't a short convict.",
        options: [
          { id: 0, label: 'u is not c' },
          { id: 1, label: 'U is not c' },
          { id: 2, label: 'u is not C' },
          { id: 3, label: 'U is not C' },
        ],
        correctId: [2],
        answer:
          '"A short convict" could describe many persons, and so translates into a capital letter.',
      },
      {
        id: '1.3',
        prompt: "The dancer isn't the most cheerful person.",
        options: [
          { id: 0, label: 'D is not C' },
          { id: 1, label: 'D is not c' },
          { id: 2, label: 'd is not C' },
          { id: 3, label: 'd is not c' },
        ],
        correctId: [3],
        answer: '',
      },
      {
        id: '1.4',
        prompt: 'All soldiers in Berlin forgive people who are remarkable.',
        options: [
          { id: 0, label: 'S is F' },
          { id: 1, label: 'all S is F' },
          { id: 2, label: 'all s is F' },
          { id: 3, label: 'all F is S' },
        ],
        correctId: [1],
        answer: '',
      },
      {
        id: '1.5',
        prompt: "You aren't the smartest criminal.",
        options: [
          { id: 0, label: 'u is not C' },
          { id: 1, label: 'U is not C' },
          { id: 2, label: 'U is not c' },
          { id: 3, label: 'u is not c' },
        ],
        correctId: [3],
        answer: '',
      },
      {
        id: '1.6',
        prompt: "You aren't a slow druggist.",
        options: [
          { id: 0, label: 'U is not d' },
          { id: 1, label: 'u is not D' },
          { id: 2, label: 'U is not D' },
          { id: 3, label: 'u is not d' },
        ],
        correctId: [1],
        answer: '',
      },
      {
        id: '1.7',
        prompt: "I'm the cheapest poet in Paris.",
        options: [
          { id: 0, label: 'I is P' },
          { id: 1, label: 'i is P' },
          { id: 2, label: 'I is p' },
          { id: 3, label: 'i is p' },
        ],
        correctId: [3],
        answer: `"The cheapest poet" ${feedback_single_person}`,
      },
      {
        id: '1.8',
        prompt: 'All detectives in London hate people who are frantic.',
        options: [
          { id: 0, label: 'all H is D' },
          { id: 1, label: 'all D is H' },
          { id: 2, label: 'all d is H' },
          { id: 3, label: 'D is H' },
        ],
        correctId: [1],
        answer: '',
      },
      {
        id: '1.9',
        prompt: "You aren't the wildest plumber.",
        options: [
          { id: 0, label: 'u is not P' },
          { id: 1, label: 'u is not p' },
          { id: 2, label: 'U is not P' },
          { id: 3, label: 'U is not p' },
        ],
        correctId: [1],
        answer: `"The wildest plumber" ${feedback_single_person}`,
      },
      {
        id: '1.10',
        prompt: "You aren't a short customer.",
        options: [
          { id: 0, label: 'U is not c' },
          { id: 1, label: 'U is not C' },
          { id: 2, label: 'u is not c' },
          { id: 3, label: 'u is not C' },
        ],
        correctId: [3],
        answer: '',
      },
      {
        id: '1.11',
        prompt: "I'm the boldest guitarist in New York.",
        options: [
          { id: 0, label: 'I is G' },
          { id: 1, label: 'i is g' },
          { id: 2, label: 'i is G' },
          { id: 3, label: 'I is g' },
        ],
        correctId: [1],
        answer: '',
      },
      {
        id: '1.12',
        prompt: 'All judges in Madrid appreciate people who are tactful.',
        options: [
          { id: 0, label: 'J is A' },
          { id: 1, label: 'all J is A' },
          { id: 2, label: 'all A is J' },
          { id: 3, label: 'all j is A' },
        ],
        correctId: [1],
        answer: '',
      },
      {
        id: '1.13',
        prompt: "You aren't the slowest dentist.",
        options: [
          { id: 0, label: 'U is not d' },
          { id: 1, label: 'u is not d' },
          { id: 2, label: 'u is not D' },
          { id: 3, label: 'U is not D' },
        ],
        correctId: [1],
        answer: '',
      },
      {
        id: '1.14',
        prompt: "Some prisoners don't blame any frivolous people.",
        options: [
          { id: 0, label: 'P is not B' },
          { id: 1, label: 'some P is B' },
          { id: 2, label: 'some P is not B' },
          { id: 3, label: 'some p is not B' },
        ],
        correctId: [2],
        answer: '',
      },
      {
        id: '1.15',
        prompt: "I'm the cleanest musician in Moscow.",
        options: [
          { id: 0, label: 'I is M' },
          { id: 1, label: 'i is M' },
          { id: 2, label: 'I is m' },
          { id: 3, label: 'i is m' },
        ],
        correctId: [3],
        answer: '',
      },
      {
        id: '1.16',
        prompt: 'All pessimists in Detroit encourage people who are dishonest.',
        options: [
          { id: 0, label: 'P is E' },
          { id: 1, label: 'all E is P' },
          { id: 2, label: 'all P is E' },
          { id: 3, label: 'all p is E' },
        ],
        correctId: [2],
        answer: '',
      },
      {
        id: '1.17',
        prompt: "You aren't the meanest politician.",
        options: [
          { id: 0, label: 'U is not P' },
          { id: 1, label: 'U is not p' },
          { id: 2, label: 'u is not p' },
          { id: 3, label: 'u is not P' },
        ],
        correctId: [2],
        answer: `"The meanest politician" ${feedback_single_person}`,
      },
      {
        id: '1.18',
        prompt: "Some republicans don't hate any filthy people.",
        options: [
          { id: 0, label: 'some R is H' },
          { id: 1, label: 'some R is not H' },
          { id: 2, label: 'R is not H' },
          { id: 3, label: 'some r is not H' },
        ],
        correctId: [1],
        answer: '',
      },
      /* {
        id: '1.19',
        prompt: "I'm the smartest doctor in Chicago.",
        options: [
          { id: 0, label: 'some R is H' },
          { id: 1, label: 'some R is not H' },
          { id: 2, label: 'R is not H' },
          { id: 3, label: 'some r is not H' },
        ],
        correctId: [0],
        answer: `"The smartest doctor" ${feedback_single_person}`,
      }, */
      {
        id: '1.20',
        prompt: 'All pickpockets in Rome hurt people who are fortunate.',
        options: [
          { id: 0, label: 'all H is P' },
          { id: 1, label: 'All P is H' },
          { id: 2, label: 'P is H' },
          { id: 3, label: 'all p is H' },
        ],
        correctId: [1],
        answer: '',
      },
      {
        id: '1.21',
        prompt: "You aren't the strongest banker.",
        options: [
          { id: 0, label: 'U is not b' },
          { id: 1, label: 'u is not b' },
          { id: 2, label: 'U is not B' },
          { id: 3, label: 'u is not B' },
        ],
        correctId: [1],
        answer: `"The strongest banker" ${feedback_single_person}`,
      },
      {
        id: '1.22',
        prompt: "Some Germans don't blame any miserable people.",
        options: [
          { id: 0, label: 'some G is B' },
          { id: 1, label: 'some g is not B' },
          { id: 2, label: 'some G is not B' },
          { id: 3, label: 'G is not B' },
        ],
        correctId: [2],
        answer: '',
      },
      {
        id: '1.23',
        prompt: "I'm the cruelest bachelor in Santa Monica.",
        options: [
          { id: 0, label: 'I is b' },
          { id: 1, label: 'i is B' },
          { id: 2, label: 'i is b' },
          { id: 3, label: 'I is B' },
        ],
        correctId: [2],
        answer: `"The cruelest bachelor" ${feedback_single_person}`,
      },
      {
        id: '1.24',
        prompt: 'All carpenters in Virginia bother people who are dangerous.',
        options: [
          { id: 0, label: 'all c is B' },
          { id: 1, label: 'all B is C' },
          { id: 2, label: 'all C is B' },
          { id: 3, label: 'C is B' },
        ],
        correctId: [2],
        answer: '',
      },
      {
        id: '1.25',
        prompt: "You aren't the brightest convict.",
        options: [
          { id: 0, label: 'u is not C' },
          { id: 1, label: 'u is not c' },
          { id: 2, label: 'U is not C' },
          { id: 3, label: 'U is not c' },
        ],
        correctId: [2],
        answer: `"The brightest" ${feedback_single_person}`,
      },
      {
        id: '1.25',
        prompt: 'Some vicious criminals are boring.',
        options: [
          { id: 0, label: 'C is b' },
          { id: 1, label: 'some C is B' },
          { id: 2, label: 'some C is b' },
          { id: 3, label: 'C is B' },
        ],
        correctId: [2],
        answer: '',
      },
      {
        id: '1.26',
        prompt: "I'm the slowest diabetic in Boston.",
        options: [
          { id: 0, label: 'I is d' },
          { id: 1, label: 'I is D' },
          { id: 2, label: 'i is d' },
          { id: 3, label: 'i is D' },
        ],
        correctId: [2],
        answer: `"The slowest diabetic" ${feedback_single_person}`,
      },
      {
        id: '1.27',
        prompt:
          'All backpackers in Mexico City know people who are prosperous.',
        options: [
          { id: 0, label: 'B is K' },
          { id: 1, label: 'all b is K' },
          { id: 2, label: 'all B is K' },
          { id: 3, label: 'all K is B' },
        ],
        correctId: [2],
        answer: ``,
      },
      {
        id: '1.28',
        prompt: "You aren't the tallest cannibal.",
        options: [
          { id: 0, label: 'u is not C' },
          { id: 1, label: 'u is not c' },
          { id: 2, label: 'U is not C' },
          { id: 3, label: 'U is not c' },
        ],
        correctId: [1],
        answer: ``,
      },
      {
        id: '1.29',
        prompt: 'Some notorious fugitives are dishonest.',
        options: [
          { id: 0, label: 'F is D' },
          { id: 1, label: 'F is d' },
          { id: 2, label: 'some F is D' },
          { id: 3, label: 'some F is d' },
        ],
        correctId: [2],
        answer: ``,
      },
      {
        id: '1.30',
        prompt: "I'm the meanest bandit in Bratislava.",
        options: [
          { id: 0, label: 'i is B' },
          { id: 1, label: 'I is B' },
          { id: 2, label: 'I is b' },
          { id: 3, label: 'i is b' },
        ],
        correctId: [3],
        answer: `"The meanest bandit" ${feedback_single_person}`,
      },
    ],
  },
  {
    set: 'Set C',
    slugs: ['propositional', 'translations'],
    id: 6,
    title: 'Propositional Translations: Easy',
    header: 'Translates into logic as:',
    questions: [
      {
        id: '6.1',
        prompt: 'Both P and either L or D',
        options: [
          { id: 0, label: '$ (P \\cdot (L \\vee D)) $' },
          { id: 1, label: '$ (P \\cdot L) \\vee D $' },
          { id: 2, label: '$ P \\cdot L \\vee D $' },
          { id: 3, label: '$ ((P \\cdot L) \\vee D) $' },
        ],
        correctId: [0],
        answer: '',
      },
      {
        id: '6.2',
        prompt: 'Not either not B or N',
        options: [
          { id: 0, label: '$ (B \\vee N) $' },
          { id: 1, label: '$ B \\vee N $' },
          { id: 2, label: '$ \\sim\\sim B \\vee N $' },
          { id: 3, label: '$ \\sim(\\sim B \\vee N) $' },
        ],
        correctId: [3],
        answer: '',
      },
      {
        id: '6.3',
        prompt: "You aren't either smart or filthy",
        options: [
          { id: 0, label: '$ \\sim(S \\vee F) $' },
          { id: 1, label: '$ \\sim S \\vee F $' },
          { id: 2, label: '$ (\\sim S \\vee \\sim F) $' },
          { id: 3, label: '$ (\\sim S \\vee F) $' },
        ],
        correctId: [0],
        answer: '',
      },
      {
        id: '6.4',
        prompt: "You aren't both not forgetful and confident",
        options: [
          { id: 0, label: '$ (F \\cdot C) $' },
          { id: 1, label: '$ F \\cdot C $' },
          { id: 2, label: '$ \\sim(\\sim F \\cdot C) $' },
          { id: 3, label: '$ \\sim\\sim F \\cdot C $' },
        ],
        correctId: [2],
        answer: '',
      },
      {
        id: '6.5',
        prompt: 'Not if not S then L',
        options: [
          { id: 0, label: '$ \\sim(\\sim S \\rightarrow L) $' },
          { id: 1, label: '$ \\sim\\sim S \\rightarrow L $' },
          { id: 2, label: '$ S \\rightarrow L $' },
          { id: 3, label: '$ (S \\rightarrow L) $' },
        ],
        correctId: [0],
        answer: '',
      },
      {
        id: '6.6',
        prompt: 'Not either not C or L',
        options: [
          { id: 0, label: '$ \\sim\\sim C \\vee L $' },
          { id: 1, label: '$ (C \\vee L) $' },
          { id: 2, label: '$ C \\vee L $' },
          { id: 3, label: '$ \\sim(\\sim C \\vee L) $' },
        ],
        correctId: [3],
        answer: '',
      },
      {
        id: '6.7',
        prompt: "If you're dull then you're logical, and you're persistent",
        options: [
          { id: 0, label: '$ (D \\rightarrow L) \\cdot P $' },
          { id: 1, label: '$ (D \\rightarrow (L \\cdot P)) $' },
          { id: 2, label: '$ ((D \\rightarrow L) \\cdot P) $' },
          { id: 3, label: '$ D \\rightarrow L \\cdot P $' },
        ],
        correctId: [2],
        answer: '',
      },
      {
        id: '6.8',
        prompt: "You're either not mean or not curious",
        options: [
          { id: 0, label: '$ (\\sim M \\vee C) $' },
          { id: 1, label: '$ \\sim M \\vee \\sim C $' },
          { id: 2, label: '$ (\\sim M \\vee \\sim C) $' },
          { id: 3, label: '$ \\sim(M \\vee \\sim C) $' },
        ],
        correctId: [2],
        answer: '',
      },
      {
        id: '6.9',
        prompt: "You're both not bashful and not careful",
        options: [
          { id: 0, label: '$ (\\sim B \\cdot C) $' },
          { id: 1, label: '$ \\sim(B \\cdot \\sim C) $' },
          { id: 2, label: '$ \\sim B \\cdot \\sim C $' },
          { id: 3, label: '$ (\\sim B \\cdot \\sim C) $' },
        ],
        correctId: [3],
        answer: '',
      },
      {
        id: '6.10',
        prompt: "You aren't both charitable and frightened",
        options: [
          { id: 0, label: '$ (\\sim C \\cdot F) $' },
          { id: 1, label: '$ \\sim C \\cdot F $' },
          { id: 2, label: '$ (\\sim C \\cdot \\sim F) $' },
          { id: 3, label: '$ \\sim(C \\cdot F) $' },
        ],
        correctId: [3],
        answer: '',
      },
      {
        id: '6.11',
        prompt: "If you're bright then you're cheerful, or you're powerful",
        options: [
          { id: 0, label: '$ (B \\rightarrow (C \\vee P)) $' },
          { id: 1, label: '$ ((B \\rightarrow C) \\vee P) $' },
          { id: 2, label: '$ B \\rightarrow C \\vee P $' },
          { id: 3, label: '$ (B \\rightarrow C) \\vee P $' },
        ],
        correctId: [1],
        answer: '',
      },
      {
        id: '6.12',
        prompt: 'Either both W and C or D',
        options: [
          { id: 0, label: '$ ((W \\cdot C) \\vee D) $' },
          { id: 1, label: '$ (W \\cdot (C \\vee D)) $' },
          { id: 2, label: '$ (W \\cdot C) \\vee D $' },
          { id: 3, label: '$ W \\cdot C \\cdot D $' },
        ],
        correctId: [0],
        answer: '',
      },
      {
        id: '6.13',
        prompt: "If you're strong, then you're famous or courageous",
        options: [
          { id: 0, label: '$ S \\rightarrow F \\vee C $' },
          { id: 1, label: '$ ((S \\rightarrow F) \\vee C) $' },
          { id: 2, label: '$ (S \\rightarrow (F \\vee C)) $' },
          { id: 3, label: '$ (S \\rightarrow F) \\vee C $' },
        ],
        correctId: [2],
        answer: '',
      },
      {
        id: '6.14',
        prompt: 'Not if C then F',
        options: [
          { id: 0, label: '$ (\\sim C \\rightarrow F) $' },
          { id: 1, label: '$ (\\sim C \\rightarrow \\sim F) $' },
          { id: 2, label: '$ \\sim(C \\rightarrow F) $' },
          { id: 3, label: '$ \\sim C \\rightarrow F $' },
        ],
        correctId: [2],
        answer: '',
      },
      {
        id: '6.15',
        prompt: "If you're short then you're greedy, or you're hideous",
        options: [
          { id: 0, label: '$ S \\rightarrow G \\vee H $' },
          { id: 1, label: '$ (S \\rightarrow G) \\vee H $' },
          { id: 2, label: '$ (S \\rightarrow (G \\vee H)) $' },
          { id: 3, label: '$ ((S \\rightarrow G) \\vee H) $' },
        ],
        correctId: [3],
        answer: '',
      },
      {
        id: '6.16',
        prompt: "If you aren't poor then you aren't beautiful",
        options: [
          { id: 0, label: '$ \\sim(P \\rightarrow \\sim B) $' },
          { id: 1, label: '$ \\sim P \\rightarrow \\sim B $' },
          { id: 2, label: '$ (\\sim P \\rightarrow \\sim B) $' },
          { id: 3, label: '$ (\\sim P \\vee B) $' },
        ],
        correctId: [2],
        answer: '',
      },
      {
        id: '6.17',
        prompt: 'Either not B or L',
        options: [
          { id: 0, label: '$ (\\sim B \\vee \\sim L) $' },
          { id: 1, label: '$ \\sim B \\vee L $' },
          { id: 2, label: '$ \\sim(B \\vee L) $' },
          { id: 3, label: '$ (\\sim B \\vee L) $' },
        ],
        correctId: [3],
        answer: '',
      },
      {
        id: '6.18',
        prompt: 'If S, then H and L',
        options: [
          { id: 0, label: '$ (S \\rightarrow (H \\cdot L)) $' },
          { id: 1, label: '$ S \\rightarrow H \\cdot L $' },
          { id: 2, label: '$ ((S \\rightarrow H) \\cdot L) $' },
          { id: 3, label: '$ (S \\rightarrow H) \\cdot L $' },
        ],
        correctId: [0],
        answer: '',
      },
      {
        id: '6.19',
        prompt: "You're tall and naive, or else dangerous",
        options: [
          { id: 0, label: '$ ((T \\vee N) \\vee D) $' },
          { id: 1, label: '$ T \\cdot N \\vee D $' },
          { id: 2, label: '$ (T \\cdot N) \\vee D $' },
          { id: 3, label: '$ (T \\cdot (N \\vee D)) $' },
        ],
        correctId: [0],
        answer: '',
      },
      {
        id: '6.20',
        prompt: 'W, and D or S',
        options: [
          { id: 0, label: '$ ((W \\cdot D) \\vee S) $' },
          { id: 1, label: '$ (W \\cdot (D \\vee S)) $' },
          { id: 2, label: '$ (W \\cdot D) \\vee S $' },
          { id: 3, label: '$ W \\cdot D \\vee S $' },
        ],
        correctId: [1],
        answer: '',
      },
      {
        id: '6.21',
        prompt: 'Either not M or B',
        options: [
          { id: 0, label: '$ (\\sim M \\vee \\sim B) $' },
          { id: 1, label: '$ (\\sim M \\vee B) $' },
          { id: 2, label: '$ \\sim(M \\vee B) $' },
          { id: 3, label: '$ \\sim M \\vee B $' },
        ],
        correctId: [1],
        answer: '',
      },
      {
        id: '6.22',
        prompt: 'Either not B or not C',
        options: [
          { id: 0, label: '$ (\\sim B \\vee C) $' },
          { id: 1, label: '$ \\sim(B \\vee \\sim C) $' },
          { id: 2, label: '$ (\\sim B \\vee \\sim C) $' },
          { id: 3, label: '$ \\sim B \\vee \\sim C $' },
        ],
        correctId: [2],
        answer: '',
      },
      {
        id: '6.23',
        prompt: 'If R then P, and C',
        options: [
          { id: 0, label: '$ ((R \\rightarrow P) \\cdot C) $' },
          { id: 1, label: '$ R \\rightarrow P \\cdot C $' },
          { id: 2, label: '$ (R \\rightarrow (P \\cdot C)) $' },
          { id: 3, label: '$ (R \\rightarrow P) \\cdot C $' },
        ],
        correctId: [0],
        answer: '',
      },
      {
        id: '6.24',
        prompt: 'Not both R and C',
        options: [
          { id: 0, label: '$ \\sim R \\cdot C $' },
          { id: 1, label: '$ (\\sim R \\cdot \\sim C) $' },
          { id: 2, label: '$ \\sim(R \\cdot C) $' },
          { id: 3, label: '$ (\\sim R \\cdot C) $' },
        ],
        correctId: [2],
        answer: '',
      },
      {
        id: '6.25',
        prompt: 'Either not C or N',
        options: [
          { id: 0, label: '$ \\sim C \\vee N $' },
          { id: 1, label: '$ \\sim(C \\vee N) $' },
          { id: 2, label: '$ (\\sim C \\vee \\sim N) $' },
          { id: 3, label: '$ (\\sim C \\vee N) $' },
        ],
        correctId: [3],
        answer: '',
      },
      {
        id: '6.26',
        prompt: 'If not C then H',
        options: [
          { id: 0, label: '$ \\sim C \\rightarrow H $' },
          { id: 1, label: '$ (\\sim C \\rightarrow H) $' },
          { id: 2, label: '$ (\\sim C \\rightarrow \\sim H) $' },
          { id: 3, label: '$ \\sim(C \\rightarrow H) $' },
        ],
        correctId: [1],
        answer: '',
      },
      {
        id: '6.27',
        prompt: 'Not either not W or C',
        options: [
          { id: 0, label: '$ \\sim\\sim W \\vee C $' },
          { id: 1, label: '$ W \\vee C $' },
          { id: 2, label: '$ (W \\vee C) $' },
          { id: 3, label: '$ \\sim(\\sim W \\vee C) $' },
        ],
        correctId: [3],
        answer: '',
      },
      {
        id: '6.28',
        prompt: 'Both not M and L',
        options: [
          { id: 0, label: '$ (\\sim M \\cdot L) $' },
          { id: 1, label: '$ (\\sim M \\cdot \\sim L) $' },
          { id: 2, label: '$ \\sim(M \\cdot L) $' },
          { id: 3, label: '$ \\sim M \\cdot L $' },
        ],
        correctId: [0],
        answer: '',
      },
      {
        id: '6.29',
        prompt: "You're both not miserable and not comical",
        options: [
          { id: 0, label: '$ (\\sim M \\cdot C) $' },
          { id: 1, label: '$ \\sim M \\cdot \\sim C $' },
          { id: 2, label: '$ (\\sim M \\cdot \\sim C) $' },
          { id: 3, label: '$ \\sim(M \\cdot \\sim C) $' },
        ],
        correctId: [2],
        answer: '',
      },
      {
        id: '6.30',
        prompt: 'Either both R and L or N',
        options: [
          { id: 0, label: '$ (R \\cdot (L \\vee N)) $' },
          { id: 1, label: '$ (R \\cdot L) \\vee N $' },
          { id: 2, label: '$ R \\cdot L \\vee N $' },
          { id: 3, label: '$ ((R \\cdot L) \\vee N) $' },
        ],
        correctId: [3],
        answer: '',
      },
      {
        id: '6.31',
        prompt: "If you're bright, then you're polite or demented",
        options: [
          { id: 0, label: '$ (B \\rightarrow P) \\vee D $' },
          { id: 1, label: '$ B \\rightarrow P \\vee D $' },
          { id: 2, label: '$ ((B \\rightarrow P) \\vee D) $' },
          { id: 3, label: '$ (B \\rightarrow (P \\vee D)) $' },
        ],
        correctId: [3],
        answer: '',
      },
      {
        id: '6.32',
        prompt: "If you're smart, then you're bashful and careful",
        options: [
          { id: 0, label: '$ (S \\rightarrow (B \\cdot C)) $' },
          { id: 1, label: '$ ((S \\rightarrow B) \\cdot C) $' },
          { id: 2, label: '$ (S \\rightarrow B) \\cdot C $' },
          { id: 3, label: '$ S \\rightarrow B \\cdot C $' },
        ],
        correctId: [0],
        answer: '',
      },
      {
        id: '6.33',
        prompt: "You're cheap and frivolous, or else generous",
        options: [
          { id: 0, label: '$ ((C \\cdot F) \\vee G) $' },
          { id: 1, label: '$ C \\cdot F \\vee G $' },
          { id: 2, label: '$ (C \\cdot (F \\vee G)) $' },
          { id: 3, label: '$ (C \\cdot F) \\vee G $' },
        ],
        correctId: [0],
        answer: '',
      },
      {
        id: '6.34',
        prompt: "You're either both wild and gentle or else cheerful",
        options: [
          { id: 0, label: '$ W \\cdot G \\vee C $' },
          { id: 1, label: '$ (W \\cdot (G \\vee C)) $' },
          { id: 2, label: '$ (W \\cdot G) \\vee C $' },
          { id: 3, label: '$ ((W \\cdot G) \\vee C) $' },
        ],
        correctId: [3],
        answer: '',
      },
      {
        id: '6.35',
        prompt: "You aren't either dull or boastful",
        options: [
          { id: 0, label: '$ (\\sim D \\vee \\sim B) $' },
          { id: 1, label: '$ (\\sim D \\vee B) $' },
          { id: 2, label: '$ \\sim D \\vee B $' },
          { id: 3, label: '$ \\sim(D \\vee B) $' },
        ],
        correctId: [3],
        answer: '',
      },
      {
        id: '6.36',
        prompt: "You aren't both not creative and notorious",
        options: [
          { id: 0, label: '$ \\sim(\\sim C \\cdot N) $' },
          { id: 1, label: '$ (C \\cdot N) $' },
          { id: 2, label: '$ \\sim\\sim C \\cdot N $' },
          { id: 3, label: '$ C \\cdot N $' },
        ],
        correctId: [0],
        answer: '',
      },
      {
        id: '6.37',
        prompt: 'Not if not B then C',
        options: [
          { id: 0, label: '$ \\sim\\sim B \\rightarrow C $' },
          { id: 1, label: '$ B \\rightarrow C $' },
          { id: 2, label: '$ \\sim(\\sim B \\rightarrow C) $' },
          { id: 3, label: '$ (B \\rightarrow C) $' },
        ],
        correctId: [2],
        answer: '',
      },
      {
        id: '6.38',
        prompt: "You're both bright and either forgetful or confident",
        options: [
          { id: 0, label: '$ ((B \\cdot F) \\vee C) $' },
          { id: 1, label: '$ (B \\cdot F) \\vee C $' },
          { id: 2, label: '$ B \\cdot F \\vee C $' },
          { id: 3, label: '$ (B \\cdot (F \\vee C)) $' },
        ],
        correctId: [3],
        answer: '',
      },
      {
        id: '6.39',
        prompt: 'Not either W or C',
        options: [
          { id: 0, label: '$ (\\sim W \\vee \\sim C) $' },
          { id: 1, label: '$ \\sim W \\vee C $' },
          { id: 2, label: '$ (\\sim W \\vee C) $' },
          { id: 3, label: '$ \\sim(W \\vee C) $' },
        ],
        correctId: [3],
        answer: '',
      },
      {
        id: '6.40',
        prompt: "You're tall, and mediocre or colorful",
        options: [
          { id: 0, label: '$ (T \\cdot M) \\vee C $' },
          { id: 1, label: '$ (T \\cdot (M \\vee C)) $' },
          { id: 2, label: '$ ((T \\cdot M) \\vee C) $' },
          { id: 3, label: '$ T \\cdot M \\vee C $' },
        ],
        correctId: [1],
        answer: '',
      },
      {
        id: '6.41',
        prompt: 'If D then M, and L',
        options: [
          { id: 0, label: '$ D \\rightarrow M \\cdot L $' },
          { id: 1, label: '$ (D \\rightarrow M) \\cdot L $' },
          { id: 2, label: '$ (D \\rightarrow (M \\cdot L)) $' },
          { id: 3, label: '$ ((D \\rightarrow M) \\cdot L) $' },
        ],
        correctId: [3],
        answer: '',
      },
      {
        id: '6.42',
        prompt: 'Not both L and N',
        options: [
          { id: 0, label: '$ (\\sim L \\cdot \\sim N) $' },
          { id: 1, label: '$ \\sim L \\cdot N $' },
          { id: 2, label: '$ \\sim(L \\cdot N) $' },
          { id: 3, label: '$ (\\sim L \\cdot N) $' },
        ],
        correctId: [2],
        answer: '',
      },
      {
        id: '6.43',
        prompt: 'Either not B or P',
        options: [
          { id: 0, label: '$ \\sim(B \\vee P) $' },
          { id: 1, label: '$ \\sim B \\vee P $' },
          { id: 2, label: '$ (\\sim B \\vee P) $' },
          { id: 3, label: '$ (\\sim B \\vee \\sim P) $' },
        ],
        correctId: [2],
        answer: '',
      },
      {
        id: '6.44',
        prompt: "You're both not sarcastic and not bashful",
        options: [
          { id: 0, label: '$ (\\sim S \\cdot B) $' },
          { id: 1, label: '$ (\\sim S \\cdot \\sim B) $' },
          { id: 2, label: '$ \\sim(S \\cdot \\sim B) $' },
          { id: 3, label: '$ \\sim S \\cdot \\sim B $' },
        ],
        correctId: [1],
        answer: '',
      },
      {
        id: '6.45',
        prompt: 'If C then S, and B',
        options: [
          { id: 0, label: '$ (C \\rightarrow S) \\cdot B $' },
          { id: 1, label: '$ (C \\rightarrow (S \\cdot B)) $' },
          { id: 2, label: '$ C \\rightarrow S \\cdot B $' },
          { id: 3, label: '$ ((C \\rightarrow S) \\cdot B) $' },
        ],
        correctId: [3],
        answer: '',
      },
      {
        id: '6.46',
        prompt: "If you're strong then you're talented, or you're cautious",
        options: [
          { id: 0, label: '$ (S \\rightarrow T) \\vee C $' },
          { id: 1, label: '$ (S \\rightarrow (T \\vee C)) $' },
          { id: 2, label: '$ S \\rightarrow T \\vee C $' },
          { id: 3, label: '$ ((S \\rightarrow T) \\vee C) $' },
        ],
        correctId: [3],
        answer: '',
      },
      {
        id: '6.47',
        prompt: "If you aren't tall then you aren't frightened",
        options: [
          { id: 0, label: '$ (\\sim T \\rightarrow \\sim F) $' },
          { id: 1, label: '$ \\sim(T \\rightarrow \\sim F) $' },
          { id: 2, label: '$ \\sim T \\rightarrow \\sim F $' },
          { id: 3, label: '$ (\\sim T \\rightarrow F) $' },
        ],
        correctId: [0],
        answer: '',
      },
      {
        id: '6.48',
        prompt: 'Both not P and not B',
        options: [
          { id: 0, label: '$ \\sim P \\cdot \\sim B $' },
          { id: 1, label: '$ \\sim(P \\cdot \\sim B) $' },
          { id: 2, label: '$ (\\sim P \\cdot \\sim B) $' },
          { id: 3, label: '$ (\\sim P \\cdot B) $' },
        ],
        correctId: [2],
        answer: '',
      },
      {
        id: '6.49',
        prompt: 'If P, then C or D',
        options: [
          { id: 0, label: '$ (P \\rightarrow (C \\vee D)) $' },
          { id: 1, label: '$ ((P \\rightarrow C) \\vee D) $' },
          { id: 2, label: '$ P \\rightarrow C \\vee D $' },
          { id: 3, label: '$ (P \\rightarrow C) \\vee D $' },
        ],
        correctId: [0],
        answer: '',
      },
      {
        id: '6.50',
        prompt: 'Both not C and F',
        options: [
          { id: 0, label: '$ \\sim C \\cdot F $' },
          { id: 1, label: '$ (\\sim C \\cdot \\sim F) $' },
          { id: 2, label: '$ \\sim(C \\cdot F) $' },
          { id: 3, label: '$ (\\sim C \\cdot F) $' },
        ],
        correctId: [3],
        answer: '',
      },
      {
        id: '6.51',
        prompt: "If you aren't tough then you're greedy",
        options: [
          { id: 0, label: '$ (\\sim T \\rightarrow G) $' },
          { id: 1, label: '$ \\sim T \\rightarrow G $' },
          { id: 2, label: '$ (\\sim T \\rightarrow \\sim G) $' },
          { id: 3, label: '$ \\sim(T \\rightarrow G) $' },
        ],
        correctId: [0],
        answer: '',
      },
      {
        id: '6.52',
        prompt: "If you're weak and hideous, then you're candid",
        options: [
          { id: 0, label: '$ W \\cdot H \\rightarrow C $' },
          { id: 1, label: '$ (W \\cdot (H \\rightarrow C)) $' },
          { id: 2, label: '$ ((W \\cdot H) \\rightarrow C) $' },
          { id: 3, label: '$ (W \\cdot H) \\rightarrow C $' },
        ],
        correctId: [2],
        answer: '',
      },
      {
        id: '6.53',
        prompt: "You aren't both not fortunate and loveable",
        options: [
          { id: 0, label: '$ F \\cdot L $' },
          { id: 1, label: '$ (F \\cdot L) $' },
          { id: 2, label: '$ \\sim(\\sim F \\cdot L) $' },
          { id: 3, label: '$ \\sim\\sim F \\cdot L $' },
        ],
        correctId: [2],
        answer: '',
      },
      {
        id: '6.54',
        prompt: "You're cruel and lonely, or else humorous",
        options: [
          { id: 0, label: '$ ((C \\cdot L) \\vee H) $' },
          { id: 1, label: '$ (C \\cdot L) \\vee H $' },
          { id: 2, label: '$ C \\cdot L \\vee H $' },
          { id: 3, label: '$ (C \\cdot (L \\vee H)) $' },
        ],
        correctId: [0],
        answer: '',
      },
      {
        id: '6.55',
        prompt: 'If P, then D and N',
        options: [
          { id: 0, label: '$ P \\rightarrow D \\cdot N $' },
          { id: 1, label: '$ ((P \\rightarrow D) \\cdot N) $' },
          { id: 2, label: '$ (P \\rightarrow D) \\cdot N $' },
          { id: 3, label: '$ (P \\rightarrow (D \\cdot N)) $' },
        ],
        correctId: [3],
        answer: '',
      },
      {
        id: '6.56',
        prompt: 'Not if R then C',
        options: [
          { id: 0, label: '$ (\\sim R \\rightarrow \\sim C) $' },
          { id: 1, label: '$ \\sim R \\rightarrow C $' },
          { id: 2, label: '$ \\sim(R \\rightarrow C) $' },
          { id: 3, label: '$ (\\sim R \\rightarrow C) $' },
        ],
        correctId: [2],
        answer: '',
      },
      {
        id: '6.57',
        prompt: "It is false that if you aren't bright then you're careful",
        options: [
          { id: 0, label: '$ B \\rightarrow C $' },
          { id: 1, label: '$ \\sim(\\sim B \\rightarrow C) $' },
          { id: 2, label: '$ (B \\rightarrow C) $' },
          { id: 3, label: '$ \\sim\\sim B \\rightarrow C $' },
        ],
        correctId: [1],
        answer: '',
      },
      {
        id: '6.58',
        prompt: "You're either tough and cautious or else frivolous",
        options: [
          { id: 0, label: '$ (T \\cdot C) \\vee F $' },
          { id: 1, label: '$ (T \\cdot (C \\vee F)) $' },
          { id: 2, label: '$ T \\cdot C \\vee F $' },
          { id: 3, label: '$ ((T \\cdot C) \\vee F) $' },
        ],
        correctId: [3],
        answer: '',
      },
      {
        id: '6.59',
        prompt: "You're both weak and either charming or prosperous",
        options: [
          { id: 0, label: '$ (W \\cdot (C \\vee P)) $' },
          { id: 1, label: '$ (W \\cdot C) \\vee P $' },
          { id: 2, label: '$ W \\cdot C \\vee P $' },
          { id: 3, label: '$ ((W \\cdot C) \\vee P) $' },
        ],
        correctId: [0],
        answer: '',
      },
      {
        id: '6.60',
        prompt: "If you're tall then you're realistic, and you're boastful",
        options: [
          { id: 0, label: '$ T \\rightarrow R \\cdot B $' },
          { id: 1, label: '$ (T \\rightarrow (R \\cdot B)) $' },
          { id: 2, label: '$ (T \\rightarrow R) \\cdot B $' },
          { id: 3, label: '$ ((T \\rightarrow R) \\cdot B) $' },
        ],
        correctId: [3],
        answer: '',
      },
      {
        id: '6.61',
        prompt: "If you're clean then you're powerful, or you're lively",
        options: [
          { id: 0, label: '$ ((C \\rightarrow P) \\vee L) $' },
          { id: 1, label: '$ C \\rightarrow P \\vee L $' },
          { id: 2, label: '$ (C \\rightarrow P) \\vee L $' },
          { id: 3, label: '$ (C \\rightarrow (P \\vee L)) $' },
        ],
        correctId: [0],
        answer: '',
      },
      {
        id: '6.62',
        prompt: "You're short, and creative or dishonest",
        options: [
          { id: 0, label: '$ (S \\cdot C) \\vee D $' },
          { id: 1, label: '$ (S \\cdot (C \\vee D)) $' },
          { id: 2, label: '$ S \\cdot C \\vee D $' },
          { id: 3, label: '$ ((S \\cdot C) \\vee D) $' },
        ],
        correctId: [1],
        answer: '',
      },
    ],
  },
  {
    set: 'Set Q',
    slugs: ['informal', 'definitions'],
    id: 3,
    title: 'Meanings and Definitions',
    header: 'What is wrong with this definition?',
    questions: [
      {
        id: '3.1',
        prompt: 'Science is that cold and empty worship of experiments.',
        options: [
          { id: 0, label: 'Too broad' },
          { id: 1, label: 'Too narrow' },
          { id: 2, label: 'Circular' },
          { id: 3, label: 'Uses poorly understood terms' },
          { id: 4, label: 'Poor match in vagueness' },
          { id: 5, label: 'Poor match in emotional tone' },
          { id: 6, label: 'Has non-essential properties' },
        ],
        correctId: [3, 5],
        answer: 'This violates 4 and 6',
      },
      {
        id: '3.2',
        prompt: 'A tent is a movable dwelling made of canvas.',
        options: [
          { id: 0, label: 'Too broad' },
          { id: 1, label: 'Too narrow' },
          { id: 2, label: 'Circular' },
          { id: 3, label: 'Uses poorly understood terms' },
          { id: 4, label: 'Poor match in vagueness' },
          { id: 5, label: 'Poor match in emotional tone' },
          { id: 6, label: 'Has non-essential properties' },
        ],
        correctId: [1],
        answer: 'This violates 2 (tents might be made of nylon)',
      },
      {
        id: '3.3',
        prompt: 'Philosophy is the study of the human condition.',
        options: [
          { id: 0, label: 'Too broad' },
          { id: 1, label: 'Too narrow' },
          { id: 2, label: 'Circular' },
          { id: 3, label: 'Uses poorly understood terms' },
          { id: 4, label: 'Poor match in vagueness' },
          { id: 5, label: 'Poor match in emotional tone' },
          { id: 6, label: 'Has non-essential properties' },
        ],
        correctId: [0],
        answer: 'This violates 1.',
      },
      {
        id: '3.4',
        prompt: 'Logic is that dreadful discipline that analyses reasoning.',
        options: [
          { id: 0, label: 'Too broad' },
          { id: 1, label: 'Too narrow' },
          { id: 2, label: 'Circular' },
          { id: 3, label: 'Uses poorly understood terms' },
          { id: 4, label: 'Poor match in vagueness' },
          { id: 5, label: 'Poor match in emotional tone' },
          { id: 6, label: 'Has non-essential properties' },
        ],
        correctId: [5],
        answer: 'This violates 6.',
      },
      {
        id: '3.5',
        prompt: 'An old person is anyone over seventy.',
        options: [
          { id: 0, label: 'Too broad' },
          { id: 1, label: 'Too narrow' },
          { id: 2, label: 'Circular' },
          { id: 3, label: 'Uses poorly understood terms' },
          { id: 4, label: 'Poor match in vagueness' },
          { id: 5, label: 'Poor match in emotional tone' },
          { id: 6, label: 'Has non-essential properties' },
        ],
        correctId: [4],
        answer: 'This violates 5.',
      },
      {
        id: '3.6',
        prompt: 'A game is an amusing competition between various players.',
        options: [
          { id: 0, label: 'Too broad' },
          { id: 1, label: 'Too narrow' },
          { id: 2, label: 'Circular' },
          { id: 3, label: 'Uses poorly understood terms' },
          { id: 4, label: 'Poor match in vagueness' },
          { id: 5, label: 'Poor match in emotional tone' },
          { id: 6, label: 'Has non-essential properties' },
        ],
        correctId: [1],
        answer:
          'This violates 2 (solitary and many computer games can involve only a single player).',
      },
      {
        id: '3.7',
        prompt: 'A logician is an obnoxious hair-splitter.',
        options: [
          { id: 0, label: 'Too broad' },
          { id: 1, label: 'Too narrow' },
          { id: 2, label: 'Circular' },
          { id: 3, label: 'Uses poorly understood terms' },
          { id: 4, label: 'Poor match in vagueness' },
          { id: 5, label: 'Poor match in emotional tone' },
          { id: 6, label: 'Has non-essential properties' },
        ],
        correctId: [5],
        answer: 'This violates 6.',
      },
      {
        id: '3.8',
        prompt: 'A fish is an animal that lives mainly in the water.',
        options: [
          { id: 0, label: 'Too broad' },
          { id: 1, label: 'Too narrow' },
          { id: 2, label: 'Circular' },
          { id: 3, label: 'Uses poorly understood terms' },
          { id: 4, label: 'Poor match in vagueness' },
          { id: 5, label: 'Poor match in emotional tone' },
          { id: 6, label: 'Has non-essential properties' },
        ],
        correctId: [0],
        answer: 'This violates 1 (whales are not fish).',
      },
      {
        id: '3.9',
        prompt: 'A male is whatever has male reproductive organs.',
        options: [
          { id: 0, label: 'Too broad' },
          { id: 1, label: 'Too narrow' },
          { id: 2, label: 'Circular' },
          { id: 3, label: 'Uses poorly understood terms' },
          { id: 4, label: 'Poor match in vagueness' },
          { id: 5, label: 'Poor match in emotional tone' },
          { id: 6, label: 'Has non-essential properties' },
        ],
        correctId: [1, 2],
        answer: 'This violates 3 (and 2, if we consider castration).',
      },
      {
        id: '3.10',
        prompt: 'A police officer is a mere cop.',
        options: [
          { id: 0, label: 'Too broad' },
          { id: 1, label: 'Too narrow' },
          { id: 2, label: 'Circular' },
          { id: 3, label: 'Uses poorly understood terms' },
          { id: 4, label: 'Poor match in vagueness' },
          { id: 5, label: 'Poor match in emotional tone' },
          { id: 6, label: 'Has non-essential properties' },
        ],
        correctId: [5],
        answer: 'This violates 6.',
      },
      {
        id: '3.11',
        prompt: '"Uncle" means "brother of a parent".',
        options: [
          { id: 0, label: 'Too broad' },
          { id: 1, label: 'Too narrow' },
          { id: 2, label: 'Circular' },
          { id: 3, label: 'Uses poorly understood terms' },
          { id: 4, label: 'Poor match in vagueness' },
          { id: 5, label: 'Poor match in emotional tone' },
          { id: 6, label: 'Has non-essential properties' },
        ],
        correctId: [1],
        answer:
          'This violates 2 (an only child can be an uncle by being married to a sister of a parent).',
      },
      {
        id: '3.12',
        prompt: 'Knowledge is a true belief that is absolutely certain.',
        options: [
          { id: 0, label: 'Too broad' },
          { id: 1, label: 'Too narrow' },
          { id: 2, label: 'Circular' },
          { id: 3, label: 'Uses poorly understood terms' },
          { id: 4, label: 'Poor match in vagueness' },
          { id: 5, label: 'Poor match in emotional tone' },
          { id: 6, label: 'Has non-essential properties' },
        ],
        correctId: [1],
        answer: 'This violates 2 (most knowledge is not absolutely certain).',
      },
      {
        id: '3.13',
        prompt: 'A bachelor is an unmarried man who weighs over 50 pounds.',
        options: [
          { id: 0, label: 'Too broad' },
          { id: 1, label: 'Too narrow' },
          { id: 2, label: 'Circular' },
          { id: 3, label: 'Uses poorly understood terms' },
          { id: 4, label: 'Poor match in vagueness' },
          { id: 5, label: 'Poor match in emotional tone' },
          { id: 6, label: 'Has non-essential properties' },
        ],
        correctId: [6],
        answer: 'This violates 7.',
      },
      {
        id: '3.14',
        prompt: 'Triangles are what you study in geometry.',
        options: [
          { id: 0, label: 'Too broad' },
          { id: 1, label: 'Too narrow' },
          { id: 2, label: 'Circular' },
          { id: 3, label: 'Uses poorly understood terms' },
          { id: 4, label: 'Poor match in vagueness' },
          { id: 5, label: 'Poor match in emotional tone' },
          { id: 6, label: 'Has non-essential properties' },
        ],
        correctId: [0],
        answer: 'This violates 1 (you study other things too).',
      },
      {
        id: '3.15',
        prompt: 'Architecture is frozen music.',
        options: [
          { id: 0, label: 'Too broad' },
          { id: 1, label: 'Too narrow' },
          { id: 2, label: 'Circular' },
          { id: 3, label: 'Uses poorly understood terms' },
          { id: 4, label: 'Poor match in vagueness' },
          { id: 5, label: 'Poor match in emotional tone' },
          { id: 6, label: 'Has non-essential properties' },
        ],
        correctId: [3],
        answer: 'This violates 4.',
      },
      {
        id: '3.16',
        prompt: 'An apple is a red fruit.',
        options: [
          { id: 0, label: 'Too broad' },
          { id: 1, label: 'Too narrow' },
          { id: 2, label: 'Circular' },
          { id: 3, label: 'Uses poorly understood terms' },
          { id: 4, label: 'Poor match in vagueness' },
          { id: 5, label: 'Poor match in emotional tone' },
          { id: 6, label: 'Has non-essential properties' },
        ],
        correctId: [0, 1],
        answer:
          'This violates 1 (consider strawberries) and 2 (consider green apples).',
      },
      {
        id: '3.17',
        prompt: 'A warm day is one that is over 86 degrees Fahrenheit.',
        options: [
          { id: 0, label: 'Too broad' },
          { id: 1, label: 'Too narrow' },
          { id: 2, label: 'Circular' },
          { id: 3, label: 'Uses poorly understood terms' },
          { id: 4, label: 'Poor match in vagueness' },
          { id: 5, label: 'Poor match in emotional tone' },
          { id: 6, label: 'Has non-essential properties' },
        ],
        correctId: [4],
        answer: 'This violates 5.',
      },
      {
        id: '3.18',
        prompt: 'Religion is a way of life based on belief in a supreme being.',
        options: [
          { id: 0, label: 'Too broad' },
          { id: 1, label: 'Too narrow' },
          { id: 2, label: 'Circular' },
          { id: 3, label: 'Uses poorly understood terms' },
          { id: 4, label: 'Poor match in vagueness' },
          { id: 5, label: 'Poor match in emotional tone' },
          { id: 6, label: 'Has non-essential properties' },
        ],
        correctId: [1],
        answer: 'This violates 2 (some religions believe in many gods).',
      },
      {
        id: '3.19',
        prompt: 'A university instructor is just an egghead.',
        options: [
          { id: 0, label: 'Too broad' },
          { id: 1, label: 'Too narrow' },
          { id: 2, label: 'Circular' },
          { id: 3, label: 'Uses poorly understood terms' },
          { id: 4, label: 'Poor match in vagueness' },
          { id: 5, label: 'Poor match in emotional tone' },
          { id: 6, label: 'Has non-essential properties' },
        ],
        correctId: [5],
        answer: 'This violates 6.',
      },
      {
        id: '3.20',
        prompt: '"True" means "proved to be true".',
        options: [
          { id: 0, label: 'Too broad' },
          { id: 1, label: 'Too narrow' },
          { id: 2, label: 'Circular' },
          { id: 3, label: 'Uses poorly understood terms' },
          { id: 4, label: 'Poor match in vagueness' },
          { id: 5, label: 'Poor match in emotional tone' },
          { id: 6, label: 'Has non-essential properties' },
        ],
        correctId: [1, 2],
        answer: 'This violates 2 and especially 3.',
      },
      {
        id: '3.21',
        prompt: 'A chair is whatever is used as a chair.',
        options: [
          { id: 0, label: 'Too broad' },
          { id: 1, label: 'Too narrow' },
          { id: 2, label: 'Circular' },
          { id: 3, label: 'Uses poorly understood terms' },
          { id: 4, label: 'Poor match in vagueness' },
          { id: 5, label: 'Poor match in emotional tone' },
          { id: 6, label: 'Has non-essential properties' },
        ],
        correctId: [2],
        answer: 'This violates 3.',
      },
      {
        id: '3.22',
        prompt: 'A teacher is one who instructs children.',
        options: [
          { id: 0, label: 'Too broad' },
          { id: 1, label: 'Too narrow' },
          { id: 2, label: 'Circular' },
          { id: 3, label: 'Uses poorly understood terms' },
          { id: 4, label: 'Poor match in vagueness' },
          { id: 5, label: 'Poor match in emotional tone' },
          { id: 6, label: 'Has non-essential properties' },
        ],
        correctId: [1],
        answer: 'This violates 2.',
      },
      {
        id: '3.23',
        prompt: 'A net is anything with interstitial vacuities.',
        options: [
          { id: 0, label: 'Too broad' },
          { id: 1, label: 'Too narrow' },
          { id: 2, label: 'Circular' },
          { id: 3, label: 'Uses poorly understood terms' },
          { id: 4, label: 'Poor match in vagueness' },
          { id: 5, label: 'Poor match in emotional tone' },
          { id: 6, label: 'Has non-essential properties' },
        ],
        correctId: [3],
        answer: 'This violates 4.',
      },
      {
        id: '3.24',
        prompt: 'Cars are vehicles powered by gasoline.',
        options: [
          { id: 0, label: 'Too broad' },
          { id: 1, label: 'Too narrow' },
          { id: 2, label: 'Circular' },
          { id: 3, label: 'Uses poorly understood terms' },
          { id: 4, label: 'Poor match in vagueness' },
          { id: 5, label: 'Poor match in emotional tone' },
          { id: 6, label: 'Has non-essential properties' },
        ],
        correctId: [0, 1],
        answer:
          'This violates 1 (consider motorcycles) and 2 (some cars run on hydrogen, electricity, or ethanol).',
      },
      {
        id: '3.25',
        prompt: 'Bread is the staff of life.', // stuff? Not sure if it was a typo from Gensler.
        options: [
          { id: 0, label: 'Too broad' },
          { id: 1, label: 'Too narrow' },
          { id: 2, label: 'Circular' },
          { id: 3, label: 'Uses poorly understood terms' },
          { id: 4, label: 'Poor match in vagueness' },
          { id: 5, label: 'Poor match in emotional tone' },
          { id: 6, label: 'Has non-essential properties' },
        ],
        correctId: [3],
        answer: 'This violates 4.',
      },
      {
        id: '3.26',
        prompt: '"God" means "object of ultimate concern".',
        options: [
          { id: 0, label: 'Too broad' },
          { id: 1, label: 'Too narrow' },
          { id: 2, label: 'Circular' },
          { id: 3, label: 'Uses poorly understood terms' },
          { id: 4, label: 'Poor match in vagueness' },
          { id: 5, label: 'Poor match in emotional tone' },
          { id: 6, label: 'Has non-essential properties' },
        ],
        correctId: [0, 1],
        answer:
          'This violates 1 and 2 (one might have an ultimate concern for something other than God).',
      },
      {
        id: '3.27',
        prompt: 'A piano is any musical instrument with keys to select notes.',
        options: [
          { id: 0, label: 'Too broad' },
          { id: 1, label: 'Too narrow' },
          { id: 2, label: 'Circular' },
          { id: 3, label: 'Uses poorly understood terms' },
          { id: 4, label: 'Poor match in vagueness' },
          { id: 5, label: 'Poor match in emotional tone' },
          { id: 6, label: 'Has non-essential properties' },
        ],
        correctId: [0],
        answer: 'This violates 1 (consider pipe organs).',
      },
      {
        id: '3.28',
        prompt:
          'A pro football player is someone who works for a pro football team.',
        options: [
          { id: 0, label: 'Too broad' },
          { id: 1, label: 'Too narrow' },
          { id: 2, label: 'Circular' },
          { id: 3, label: 'Uses poorly understood terms' },
          { id: 4, label: 'Poor match in vagueness' },
          { id: 5, label: 'Poor match in emotional tone' },
          { id: 6, label: 'Has non-essential properties' },
        ],
        correctId: [0],
        answer: 'This violates 1 (coaches also work for such teams).',
      },
      {
        id: '3.29',
        prompt: 'A man is a featherless biped.',
        options: [
          { id: 0, label: 'Too broad' },
          { id: 1, label: 'Too narrow' },
          { id: 2, label: 'Circular' },
          { id: 3, label: 'Uses poorly understood terms' },
          { id: 4, label: 'Poor match in vagueness' },
          { id: 5, label: 'Poor match in emotional tone' },
          { id: 6, label: 'Has non-essential properties' },
        ],
        correctId: [0, 1, 6],
        answer:
          'This violates 7 (and maybe 1 and 2 — if you consider plucked chickens and humans with one leg).',
      },
      {
        id: '3.30',
        prompt: 'Punishment is anything unpleasant done to a person.',
        options: [
          { id: 0, label: 'Too broad' },
          { id: 1, label: 'Too narrow' },
          { id: 2, label: 'Circular' },
          { id: 3, label: 'Uses poorly understood terms' },
          { id: 4, label: 'Poor match in vagueness' },
          { id: 5, label: 'Poor match in emotional tone' },
          { id: 6, label: 'Has non-essential properties' },
        ],
        correctId: [0],
        answer:
          'This violates 1 (dentists drilling your teeth are not punishing you).',
      },
      {
        id: '3.31',
        prompt: 'A king is the ruler of a country.',
        options: [
          { id: 0, label: 'Too broad' },
          { id: 1, label: 'Too narrow' },
          { id: 2, label: 'Circular' },
          { id: 3, label: 'Uses poorly understood terms' },
          { id: 4, label: 'Poor match in vagueness' },
          { id: 5, label: 'Poor match in emotional tone' },
          { id: 6, label: 'Has non-essential properties' },
        ],
        correctId: [0],
        answer: 'This violates 1 (consider presidents and dictators).',
      },
      {
        id: '3.32',
        prompt: 'Backpacking is the enduring of misery by living out of doors.',
        options: [
          { id: 0, label: 'Too broad' },
          { id: 1, label: 'Too narrow' },
          { id: 2, label: 'Circular' },
          { id: 3, label: 'Uses poorly understood terms' },
          { id: 4, label: 'Poor match in vagueness' },
          { id: 5, label: 'Poor match in emotional tone' },
          { id: 6, label: 'Has non-essential properties' },
        ],
        correctId: [0, 1, 5],
        answer: 'This violates 1, 2 and 6.',
      },
      {
        id: '3.33',
        prompt: 'Knowledge is true belief.',
        options: [
          { id: 0, label: 'Too broad' },
          { id: 1, label: 'Too narrow' },
          { id: 2, label: 'Circular' },
          { id: 3, label: 'Uses poorly understood terms' },
          { id: 4, label: 'Poor match in vagueness' },
          { id: 5, label: 'Poor match in emotional tone' },
          { id: 6, label: 'Has non-essential properties' },
        ],
        correctId: [0],
        answer: 'This violates 1 (a true belief might be a lucky guess).',
      },
      {
        id: '3.34',
        prompt:
          'A belief is the closing of a phase of an intellectual symphony.',
        options: [
          { id: 0, label: 'Too broad' },
          { id: 1, label: 'Too narrow' },
          { id: 2, label: 'Circular' },
          { id: 3, label: 'Uses poorly understood terms' },
          { id: 4, label: 'Poor match in vagueness' },
          { id: 5, label: 'Poor match in emotional tone' },
          { id: 6, label: 'Has non-essential properties' },
        ],
        correctId: [3],
        answer: 'This violates 4.',
      },
      {
        id: '3.35',
        prompt: 'A politician is a scoundrel involved in politics.',
        options: [
          { id: 0, label: 'Too broad' },
          { id: 1, label: 'Too narrow' },
          { id: 2, label: 'Circular' },
          { id: 3, label: 'Uses poorly understood terms' },
          { id: 4, label: 'Poor match in vagueness' },
          { id: 5, label: 'Poor match in emotional tone' },
          { id: 6, label: 'Has non-essential properties' },
        ],
        correctId: [1, 5],
        answer: 'This violates 2 (some are honest) and 6.',
      },
      {
        id: '3.36',
        prompt:
          'Philosophy is the attempt to transcend cognitive subjectivity.',
        options: [
          { id: 0, label: 'Too broad' },
          { id: 1, label: 'Too narrow' },
          { id: 2, label: 'Circular' },
          { id: 3, label: 'Uses poorly understood terms' },
          { id: 4, label: 'Poor match in vagueness' },
          { id: 5, label: 'Poor match in emotional tone' },
          { id: 6, label: 'Has non-essential properties' },
        ],
        correctId: [3],
        answer: 'This violates 4.',
      },
      {
        id: '3.37',
        prompt: 'A doctor is a man who is licensed to practice medicine.',
        options: [
          { id: 0, label: 'Too broad' },
          { id: 1, label: 'Too narrow' },
          { id: 2, label: 'Circular' },
          { id: 3, label: 'Uses poorly understood terms' },
          { id: 4, label: 'Poor match in vagueness' },
          { id: 5, label: 'Poor match in emotional tone' },
          { id: 6, label: 'Has non-essential properties' },
        ],
        correctId: [1],
        answer: 'This violates 2 (many doctors are women).',
      },
      {
        id: '3.38',
        prompt:
          '"Human being" means "whatever is descended from human beings".',
        options: [
          { id: 0, label: 'Too broad' },
          { id: 1, label: 'Too narrow' },
          { id: 2, label: 'Circular' },
          { id: 3, label: 'Uses poorly understood terms' },
          { id: 4, label: 'Poor match in vagueness' },
          { id: 5, label: 'Poor match in emotional tone' },
          { id: 6, label: 'Has non-essential properties' },
        ],
        correctId: [2],
        answer: 'This violates 3.',
      },
      {
        id: '3.39',
        prompt:
          'A computer is a box made by Dell that has a keyboard and a screen.',
        options: [
          { id: 0, label: 'Too broad' },
          { id: 1, label: 'Too narrow' },
          { id: 2, label: 'Circular' },
          { id: 3, label: 'Uses poorly understood terms' },
          { id: 4, label: 'Poor match in vagueness' },
          { id: 5, label: 'Poor match in emotional tone' },
          { id: 6, label: 'Has non-essential properties' },
        ],
        correctId: [1, 6],
        answer: 'This violates 2 and 7 — many other companies make computers.',
      },
      {
        id: '3.40',
        prompt: 'A lie is a falsehood that you assert to be true.',
        options: [
          { id: 0, label: 'Too broad' },
          { id: 1, label: 'Too narrow' },
          { id: 2, label: 'Circular' },
          { id: 3, label: 'Uses poorly understood terms' },
          { id: 4, label: 'Poor match in vagueness' },
          { id: 5, label: 'Poor match in emotional tone' },
          { id: 6, label: 'Has non-essential properties' },
        ],
        correctId: [0],
        answer:
          'This violates 1 (if you do not know that it is false, it is just a mistake and not a lie).',
      },
      {
        id: '3.41',
        prompt:
          'Philosophy is the discipline developed by Aristotle and Plato.',
        options: [
          { id: 0, label: 'Too broad' },
          { id: 1, label: 'Too narrow' },
          { id: 2, label: 'Circular' },
          { id: 3, label: 'Uses poorly understood terms' },
          { id: 4, label: 'Poor match in vagueness' },
          { id: 5, label: 'Poor match in emotional tone' },
          { id: 6, label: 'Has non-essential properties' },
        ],
        correctId: [6],
        answer: 'This violates 7.',
      },
      {
        id: '3.42',
        prompt: 'An adolescent is a person between 9 and 19 years-old.',
        options: [
          { id: 0, label: 'Too broad' },
          { id: 1, label: 'Too narrow' },
          { id: 2, label: 'Circular' },
          { id: 3, label: 'Uses poorly understood terms' },
          { id: 4, label: 'Poor match in vagueness' },
          { id: 5, label: 'Poor match in emotional tone' },
          { id: 6, label: 'Has non-essential properties' },
        ],
        correctId: [4],
        answer: 'This violates 5.',
      },
      {
        id: '3.43',
        prompt: 'An adult is anyone over 17.',
        options: [
          { id: 0, label: 'Too broad' },
          { id: 1, label: 'Too narrow' },
          { id: 2, label: 'Circular' },
          { id: 3, label: 'Uses poorly understood terms' },
          { id: 4, label: 'Poor match in vagueness' },
          { id: 5, label: 'Poor match in emotional tone' },
          { id: 6, label: 'Has non-essential properties' },
        ],
        correctId: [4],
        answer: 'This violates 5.',
      },
      {
        id: '3.44',
        prompt: 'Philosophy is what you study in philosophy classes.',
        options: [
          { id: 0, label: 'Too broad' },
          { id: 1, label: 'Too narrow' },
          { id: 2, label: 'Circular' },
          { id: 3, label: 'Uses poorly understood terms' },
          { id: 4, label: 'Poor match in vagueness' },
          { id: 5, label: 'Poor match in emotional tone' },
          { id: 6, label: 'Has non-essential properties' },
        ],
        correctId: [2],
        answer: 'This violates 3.',
      },
      {
        id: '3.45',
        prompt: 'A cold day is one that is under 20 degrees Fahrenheit.',
        options: [
          { id: 0, label: 'Too broad' },
          { id: 1, label: 'Too narrow' },
          { id: 2, label: 'Circular' },
          { id: 3, label: 'Uses poorly understood terms' },
          { id: 4, label: 'Poor match in vagueness' },
          { id: 5, label: 'Poor match in emotional tone' },
          { id: 6, label: 'Has non-essential properties' },
        ],
        correctId: [4],
        answer: 'This violates 5.',
      },
      {
        id: '3.46',
        prompt: "An honest person is one who doesn't steal.",
        options: [
          { id: 0, label: 'Too broad' },
          { id: 1, label: 'Too narrow' },
          { id: 2, label: 'Circular' },
          { id: 3, label: 'Uses poorly understood terms' },
          { id: 4, label: 'Poor match in vagueness' },
          { id: 5, label: 'Poor match in emotional tone' },
          { id: 6, label: 'Has non-essential properties' },
        ],
        correctId: [1],
        answer: "This violates 2 (consider liars who don't steal).",
      },
      {
        id: '3.47',
        prompt: '"Murder" means "killing of a human being."',
        options: [
          { id: 0, label: 'Too broad' },
          { id: 1, label: 'Too narrow' },
          { id: 2, label: 'Circular' },
          { id: 3, label: 'Uses poorly understood terms' },
          { id: 4, label: 'Poor match in vagueness' },
          { id: 5, label: 'Poor match in emotional tone' },
          { id: 6, label: 'Has non-essential properties' },
        ],
        correctId: [0],
        answer: 'This violates 1 (consider accidental killing).',
      },
      {
        id: '3.48',
        prompt: 'A liberal is a permissive do-gooder who knows nothing.',
        options: [
          { id: 0, label: 'Too broad' },
          { id: 1, label: 'Too narrow' },
          { id: 2, label: 'Circular' },
          { id: 3, label: 'Uses poorly understood terms' },
          { id: 4, label: 'Poor match in vagueness' },
          { id: 5, label: 'Poor match in emotional tone' },
          { id: 6, label: 'Has non-essential properties' },
        ],
        correctId: [0, 1, 5],
        answer: 'This violates 1, 2 and especially 6.',
      },
      {
        id: '3.49',
        prompt: 'Logic is that wonderful discipline that analyses reasoning.',
        options: [
          { id: 0, label: 'Too broad' },
          { id: 1, label: 'Too narrow' },
          { id: 2, label: 'Circular' },
          { id: 3, label: 'Uses poorly understood terms' },
          { id: 4, label: 'Poor match in vagueness' },
          { id: 5, label: 'Poor match in emotional tone' },
          { id: 6, label: 'Has non-essential properties' },
        ],
        correctId: [5],
        answer: 'This violates 6.',
      },
      {
        id: '3.50',
        prompt: '"Chair" means "what you sit on."',
        options: [
          { id: 0, label: 'Too broad' },
          { id: 1, label: 'Too narrow' },
          { id: 2, label: 'Circular' },
          { id: 3, label: 'Uses poorly understood terms' },
          { id: 4, label: 'Poor match in vagueness' },
          { id: 5, label: 'Poor match in emotional tone' },
          { id: 6, label: 'Has non-essential properties' },
        ],
        correctId: [0, 1],
        answer:
          'This violates 1 (we sit on other things) and perhaps 2 (if there are decorative chairs that no one sits on).',
      },
      {
        id: '3.51',
        prompt: 'A conservative is an inflexible person who never thinks.',
        options: [
          { id: 0, label: 'Too broad' },
          { id: 1, label: 'Too narrow' },
          { id: 2, label: 'Circular' },
          { id: 3, label: 'Uses poorly understood terms' },
          { id: 4, label: 'Poor match in vagueness' },
          { id: 5, label: 'Poor match in emotional tone' },
          { id: 6, label: 'Has non-essential properties' },
        ],
        correctId: [0, 1, 5],
        answer: 'This violates 1, 2 and especially 6.',
      },
      {
        id: '3.52',
        prompt: 'A wrong action is one that is against the law.',
        options: [
          { id: 0, label: 'Too broad' },
          { id: 1, label: 'Too narrow' },
          { id: 2, label: 'Circular' },
          { id: 3, label: 'Uses poorly understood terms' },
          { id: 4, label: 'Poor match in vagueness' },
          { id: 5, label: 'Poor match in emotional tone' },
          { id: 6, label: 'Has non-essential properties' },
        ],
        correctId: [0, 1],
        answer: 'This violates 1 and 2.',
      },
      {
        id: '3.53',
        prompt: 'A child is anyone between 2 and 12 years old.',
        options: [
          { id: 0, label: 'Too broad' },
          { id: 1, label: 'Too narrow' },
          { id: 2, label: 'Circular' },
          { id: 3, label: 'Uses poorly understood terms' },
          { id: 4, label: 'Poor match in vagueness' },
          { id: 5, label: 'Poor match in emotional tone' },
          { id: 6, label: 'Has non-essential properties' },
        ],
        correctId: [4],
        answer: 'This violates 5.',
      },
      {
        id: '3.54',
        prompt:
          'A football game is whatever is played by the rules of football.',
        options: [
          { id: 0, label: 'Too broad' },
          { id: 1, label: 'Too narrow' },
          { id: 2, label: 'Circular' },
          { id: 3, label: 'Uses poorly understood terms' },
          { id: 4, label: 'Poor match in vagueness' },
          { id: 5, label: 'Poor match in emotional tone' },
          { id: 6, label: 'Has non-essential properties' },
        ],
        correctId: [2],
        answer: 'This violates 3.',
      },
      {
        id: '3.55',
        prompt: 'A kitten is a young female cat.',
        options: [
          { id: 0, label: 'Too broad' },
          { id: 1, label: 'Too narrow' },
          { id: 2, label: 'Circular' },
          { id: 3, label: 'Uses poorly understood terms' },
          { id: 4, label: 'Poor match in vagueness' },
          { id: 5, label: 'Poor match in emotional tone' },
          { id: 6, label: 'Has non-essential properties' },
        ],
        correctId: [1],
        answer: 'This violates 2 (kittens can be male).',
      },
      {
        id: '3.56',
        prompt: 'Logic is defined as that subject that is treated by LogiCola.',
        options: [
          { id: 0, label: 'Too broad' },
          { id: 1, label: 'Too narrow' },
          { id: 2, label: 'Circular' },
          { id: 3, label: 'Uses poorly understood terms' },
          { id: 4, label: 'Poor match in vagueness' },
          { id: 5, label: 'Poor match in emotional tone' },
          { id: 6, label: 'Has non-essential properties' },
        ],
        correctId: [6],
        answer: 'This violates 7.',
      },
      {
        id: '3.57',
        prompt: 'Knowledge is the cognizance of a reality by an intellect.',
        options: [
          { id: 0, label: 'Too broad' },
          { id: 1, label: 'Too narrow' },
          { id: 2, label: 'Circular' },
          { id: 3, label: 'Uses poorly understood terms' },
          { id: 4, label: 'Poor match in vagueness' },
          { id: 5, label: 'Poor match in emotional tone' },
          { id: 6, label: 'Has non-essential properties' },
        ],
        correctId: [3],
        answer: 'This violates 4.',
      },
      {
        id: '3.58',
        prompt: 'A bird is an animal that can fly.',
        options: [
          { id: 0, label: 'Too broad' },
          { id: 1, label: 'Too narrow' },
          { id: 2, label: 'Circular' },
          { id: 3, label: 'Uses poorly understood terms' },
          { id: 4, label: 'Poor match in vagueness' },
          { id: 5, label: 'Poor match in emotional tone' },
          { id: 6, label: 'Has non-essential properties' },
        ],
        correctId: [0, 1],
        answer: 'This violates 1 (consider ostriches) and 2 (consider bats).',
      },
      {
        id: '3.59',
        prompt: '"Metaphysics" means "any sleep-inducing subject".',
        options: [
          { id: 0, label: 'Too broad' },
          { id: 1, label: 'Too narrow' },
          { id: 2, label: 'Circular' },
          { id: 3, label: 'Uses poorly understood terms' },
          { id: 4, label: 'Poor match in vagueness' },
          { id: 5, label: 'Poor match in emotional tone' },
          { id: 6, label: 'Has non-essential properties' },
        ],
        correctId: [0, 1, 5],
        answer: 'This violates 1, 2 and 6.',
      },
      {
        id: '3.60',
        prompt: '"Tall person" means "person over 6 feet tall."',
        options: [
          { id: 0, label: 'Too broad' },
          { id: 1, label: 'Too narrow' },
          { id: 2, label: 'Circular' },
          { id: 3, label: 'Uses poorly understood terms' },
          { id: 4, label: 'Poor match in vagueness' },
          { id: 5, label: 'Poor match in emotional tone' },
          { id: 6, label: 'Has non-essential properties' },
        ],
        correctId: [4],
        answer: 'This violates 5.',
      },
    ],
  },
] satisfies Chapter[];
export { chapters };
