// The propositional logic translations were likely generated programatically by Gensler.
// TODO: Create a program that generates easy translations, four options and the solution.
// TODO: Create a program that gives hints based on the mistaken option (There's always a pattern!)

const chapters = [
  {
    id: 6,
    title: 'Propositional Translations: Easy',
    header: 'Translates into logic as:',
    questions: [
      {
        id: '6.1',
        prompt: 'Both P and either L or D',
        options: [
          { id: 0, label: '$$ (P \\cdot (L \\vee D)) $$' },
          { id: 1, label: '$$ (P \\cdot L) \\vee D $$' },
          { id: 2, label: '$$ P \\cdot L \\vee D $$' },
          { id: 3, label: '$$ ((P \\cdot L) \\vee D) $$' },
        ],
        correctId: [0],
        answer: '',
      },
      {
        id: '6.2',
        prompt: 'Not either not B or N',
        options: [
          { id: 0, label: '$$ (B \\vee N) $$' },
          { id: 1, label: '$$ B \\vee N $$' },
          { id: 2, label: '$$ \\sim\\sim B \\vee N $$' },
          { id: 3, label: '$$ \\sim(\\sim B \\vee N) $$' },
        ],
        correctId: [3],
        answer: '',
      },
      {
        id: '6.3',
        prompt: "You aren't either smart or filthy",
        options: [
          { id: 0, label: '$$ \\sim(S \\vee F) $$' },
          { id: 1, label: '$$ \\sim S \\vee F $$' },
          { id: 2, label: '$$ (\\sim S \\vee \\sim F) $$' },
          { id: 3, label: '$$ (\\sim S \\vee F) $$' },
        ],
        correctId: [0],
        answer: '',
      },
      {
        id: '6.4',
        prompt: "You aren't both not forgetful and confident",
        options: [
          { id: 0, label: '$$ (F \\cdot C) $$' },
          { id: 1, label: '$$ F \\cdot C $$' },
          { id: 2, label: '$$ \\sim(\\sim F \\cdot C) $$' },
          { id: 3, label: '$$ \\sim\\sim F \\cdot C $$' },
        ],
        correctId: [2],
        answer: '',
      },
      {
        id: '6.5',
        prompt: 'Not if not S then L',
        options: [
          { id: 0, label: '$$ \\sim(\\sim S \\rightarrow L) $$' },
          { id: 1, label: '$$ \\sim\\sim S \\rightarrow L $$' },
          { id: 2, label: '$$ S \\rightarrow L $$' },
          { id: 3, label: '$$ (S \\rightarrow L) $$' },
        ],
        correctId: [0],
        answer: '',
      },
      {
        id: '6.6',
        prompt: 'Not either not C or L',
        options: [
          { id: 0, label: '$$ \\sim\\sim C \\vee L $$' },
          { id: 1, label: '$$ (C \\vee L) $$' },
          { id: 2, label: '$$ C \\vee L $$' },
          { id: 3, label: '$$ \\sim(\\sim C \\vee L) $$' },
        ],
        correctId: [3],
        answer: '',
      },
      {
        id: '6.7',
        prompt: "If you're dull then you're logical, and you're persistent",
        options: [
          { id: 0, label: '$$ (D \\rightarrow L) \\cdot P $$' },
          { id: 1, label: '$$ (D \\rightarrow (L \\cdot P)) $$' },
          { id: 2, label: '$$ ((D \\rightarrow L) \\cdot P) $$' },
          { id: 3, label: '$$ D \\rightarrow L \\cdot P $$' },
        ],
        correctId: [2],
        answer: '',
      },
      {
        id: '6.8',
        prompt: "You're either not mean or not curious",
        options: [
          { id: 0, label: '$$ (\\sim M \\vee C) $$' },
          { id: 1, label: '$$ \\sim M \\vee \\sim C $$' },
          { id: 2, label: '$$ (\\sim M \\vee \\sim C) $$' },
          { id: 3, label: '$$ \\sim(M \\vee \\sim C) $$' },
        ],
        correctId: [2],
        answer: '',
      },
      {
        id: '6.9',
        prompt: "You're both not bashful and not careful",
        options: [
          { id: 0, label: '$$ (\\sim B \\cdot C) $$' },
          { id: 1, label: '$$ \\sim(B \\cdot \\sim C) $$' },
          { id: 2, label: '$$ \\sim B \\cdot \\sim C $$' },
          { id: 3, label: '$$ (\\sim B \\cdot \\sim C) $$' },
        ],
        correctId: [3],
        answer: '',
      },
      {
        id: '6.10',
        prompt: "You aren't both charitable and frightened",
        options: [
          { id: 0, label: '$$ (\\sim C \\cdot F) $$' },
          { id: 1, label: '$$ \\sim C \\cdot F $$' },
          { id: 2, label: '$$ (\\sim C \\cdot \\sim F) $$' },
          { id: 3, label: '$$ \\sim(C \\cdot F) $$' },
        ],
        correctId: [3],
        answer: '',
      },
      {
        id: '6.11',
        prompt: "If you're bright then you're cheerful, or you're powerful",
        options: [
          { id: 0, label: '$$ (B \\rightarrow (C \\vee P)) $$' },
          { id: 1, label: '$$ ((B \\rightarrow C) \\vee P) $$' },
          { id: 2, label: '$$ B \\rightarrow C \\vee P $$' },
          { id: 3, label: '$$ (B \\rightarrow C) \\vee P $$' },
        ],
        correctId: [1],
        answer: '',
      },
      {
        id: '6.12',
        prompt: 'Either both W and C or D',
        options: [
          { id: 0, label: '$$ ((W \\cdot C) \\vee D) $$' },
          { id: 1, label: '$$ (W \\cdot (C \\vee D)) $$' },
          { id: 2, label: '$$ (W \\cdot C) \\vee D $$' },
          { id: 3, label: '$$ W \\cdot C \\cdot D $$' },
        ],
        correctId: [0],
        answer: '',
      },
      {
        id: '6.13',
        prompt: "If you're strong, then you're famous or courageous",
        options: [
          { id: 0, label: '$$ S \\rightarrow F \\vee C $$' },
          { id: 1, label: '$$ ((S \\rightarrow F) \\vee C) $$' },
          { id: 2, label: '$$ (S \\rightarrow (F \\vee C)) $$' },
          { id: 3, label: '$$ (S \\rightarrow F) \\vee C $$' },
        ],
        correctId: [2],
        answer: '',
      },
      {
        id: '6.14',
        prompt: 'Not if C then F',
        options: [
          { id: 0, label: '$$ (\\sim C \\rightarrow F) $$' },
          { id: 1, label: '$$ (\\sim C \\rightarrow \\sim F) $$' },
          { id: 2, label: '$$ \\sim(C \\rightarrow F) $$' },
          { id: 3, label: '$$ \\sim C \\rightarrow F $$' },
        ],
        correctId: [2],
        answer: '',
      },
      {
        id: '6.15',
        prompt: "If you're short then you're greedy, or you're hideous",
        options: [
          { id: 0, label: '$$ S \\rightarrow G \\vee H $$' },
          { id: 1, label: '$$ (S \\rightarrow G) \\vee H $$' },
          { id: 2, label: '$$ (S \\rightarrow (G \\vee H)) $$' },
          { id: 3, label: '$$ ((S \\rightarrow G) \\vee H) $$' },
        ],
        correctId: [3],
        answer: '',
      },
      {
        id: '6.16',
        prompt: "If you aren't poor then you aren't beautiful",
        options: [
          { id: 0, label: '$$ \\sim(P \\rightarrow \\sim B) $$' },
          { id: 1, label: '$$ \\sim P \\rightarrow \\sim B $$' },
          { id: 2, label: '$$ (\\sim P \\rightarrow \\sim B) $$' },
          { id: 3, label: '$$ (\\sim P \\vee B) $$' },
        ],
        correctId: [2],
        answer: '',
      },
      {
        id: '6.17',
        prompt: 'Either not B or L',
        options: [
          { id: 0, label: '$$ (\\sim B \\vee \\sim L) $$' },
          { id: 1, label: '$$ \\sim B \\vee L $$' },
          { id: 2, label: '$$ \\sim(B \\vee L) $$' },
          { id: 3, label: '$$ (\\sim B \\vee L) $$' },
        ],
        correctId: [3],
        answer: '',
      },
      {
        id: '6.18',
        prompt: 'If S, then H and L',
        options: [
          { id: 0, label: '$$ (S \\rightarrow (H \\cdot L)) $$' },
          { id: 1, label: '$$ S \\rightarrow H \\cdot L $$' },
          { id: 2, label: '$$ ((S \\rightarrow H) \\cdot L) $$' },
          { id: 3, label: '$$ (S \\rightarrow H) \\cdot L $$' },
        ],
        correctId: [0],
        answer: '',
      },
      {
        id: '6.19',
        prompt: "You're tall and naive, or else dangerous",
        options: [
          { id: 0, label: '$$ ((T \\vee N) \\vee D) $$' },
          { id: 1, label: '$$ T \\cdot N \\vee D $$' },
          { id: 2, label: '$$ (T \\cdot N) \\vee D $$' },
          { id: 3, label: '$$ (T \\cdot (N \\vee D)) $$' },
        ],
        correctId: [0],
        answer: '',
      },
      {
        id: '6.20',
        prompt: 'W, and D or S',
        options: [
          { id: 0, label: '$$ ((W \\cdot D) \\vee S) $$' },
          { id: 1, label: '$$ (W \\cdot (D \\vee S)) $$' },
          { id: 2, label: '$$ (W \\cdot D) \\vee S $$' },
          { id: 3, label: '$$ W \\cdot D \\vee S $$' },
        ],
        correctId: [1],
        answer: '',
      },
      {
        id: '6.21',
        prompt: 'Either not M or B',
        options: [
          { id: 0, label: '$$ (\\sim M \\vee \\sim B) $$' },
          { id: 1, label: '$$ (\\sim M \\vee B) $$' },
          { id: 2, label: '$$ \\sim(M \\vee B) $$' },
          { id: 3, label: '$$ \\sim M \\vee B $$' },
        ],
        correctId: [1],
        answer: '',
      },
      {
        id: '6.22',
        prompt: 'Either not B or not C',
        options: [
          { id: 0, label: '$$ (\\sim B \\vee C) $$' },
          { id: 1, label: '$$ \\sim(B \\vee \\sim C) $$' },
          { id: 2, label: '$$ (\\sim B \\vee \\sim C) $$' },
          { id: 3, label: '$$ \\sim B \\vee \\sim C $$' },
        ],
        correctId: [2],
        answer: '',
      },
      {
        id: '6.23',
        prompt: 'If R then P, and C',
        options: [
          { id: 0, label: '$$ ((R \\rightarrow P) \\cdot C) $$' },
          { id: 1, label: '$$ R \\rightarrow P \\cdot C $$' },
          { id: 2, label: '$$ (R \\rightarrow (P \\cdot C)) $$' },
          { id: 3, label: '$$ (R \\rightarrow P) \\cdot C $$' },
        ],
        correctId: [0],
        answer: '',
      },
      {
        id: '6.24',
        prompt: 'Not both R and C',
        options: [
          { id: 0, label: '$$ \\sim R \\cdot C $$' },
          { id: 1, label: '$$ (\\sim R \\cdot \\sim C) $$' },
          { id: 2, label: '$$ \\sim(R \\cdot C) $$' },
          { id: 3, label: '$$ (\\sim R \\cdot C) $$' },
        ],
        correctId: [2],
        answer: '',
      },
      {
        id: '6.25',
        prompt: 'Either not C or N',
        options: [
          { id: 0, label: '$$ \\sim C \\vee N $$' },
          { id: 1, label: '$$ \\sim(C \\vee N) $$' },
          { id: 2, label: '$$ (\\sim C \\vee \\sim N) $$' },
          { id: 3, label: '$$ (\\sim C \\vee N) $$' },
        ],
        correctId: [3],
        answer: '',
      },
      {
        id: '6.26',
        prompt: 'If not C then H',
        options: [
          { id: 0, label: '$$ \\sim C \\rightarrow H $$' },
          { id: 1, label: '$$ (\\sim C \\rightarrow H) $$' },
          { id: 2, label: '$$ (\\sim C \\rightarrow \\sim H) $$' },
          { id: 3, label: '$$ \\sim(C \\rightarrow H) $$' },
        ],
        correctId: [1],
        answer: '',
      },
      {
        id: '6.27',
        prompt: 'Not either not W or C',
        options: [
          { id: 0, label: '$$ \\sim\\sim W \\vee C $$' },
          { id: 1, label: '$$ W \\vee C $$' },
          { id: 2, label: '$$ (W \\vee C) $$' },
          { id: 3, label: '$$ \\sim(\\sim W \\vee C) $$' },
        ],
        correctId: [3],
        answer: '',
      },
      {
        id: '6.28',
        prompt: 'Both not M and L',
        options: [
          { id: 0, label: '$$ (\\sim M \\cdot L) $$' },
          { id: 1, label: '$$ (\\sim M \\cdot \\sim L) $$' },
          { id: 2, label: '$$ \\sim(M \\cdot L) $$' },
          { id: 3, label: '$$ \\sim M \\cdot L $$' },
        ],
        correctId: [0],
        answer: '',
      },
      {
        id: '6.29',
        prompt: "You're both not miserable and not comical",
        options: [
          { id: 0, label: '$$ (\\sim M \\cdot C) $$' },
          { id: 1, label: '$$ \\sim M \\cdot \\sim C $$' },
          { id: 2, label: '$$ (\\sim M \\cdot \\sim C) $$' },
          { id: 3, label: '$$ \\sim(M \\cdot \\sim C) $$' },
        ],
        correctId: [2],
        answer: '',
      },
      {
        id: '6.30',
        prompt: 'Either both R and L or N',
        options: [
          { id: 0, label: '$$ (R \\cdot (L \\vee N)) $$' },
          { id: 1, label: '$$ (R \\cdot L) \\vee N $$' },
          { id: 2, label: '$$ R \\cdot L \\vee N $$' },
          { id: 3, label: '$$ ((R \\cdot L) \\vee N) $$' },
        ],
        correctId: [3],
        answer: '',
      },
      {
        id: '6.31',
        prompt: "If you're bright, then you're polite or demented",
        options: [
          { id: 0, label: '$$ (B \\rightarrow P) \\vee D $$' },
          { id: 1, label: '$$ B \\rightarrow P \\vee D $$' },
          { id: 2, label: '$$ ((B \\rightarrow P) \\vee D) $$' },
          { id: 3, label: '$$ (B \\rightarrow (P \\vee D)) $$' },
        ],
        correctId: [3],
        answer: '',
      },
      {
        id: '6.32',
        prompt: "If you're smart, then you're bashful and careful",
        options: [
          { id: 0, label: '$$ (S \\rightarrow (B \\cdot C)) $$' },
          { id: 1, label: '$$ ((S \\rightarrow B) \\cdot C) $$' },
          { id: 2, label: '$$ (S \\rightarrow B) \\cdot C $$' },
          { id: 3, label: '$$ S \\rightarrow B \\cdot C $$' },
        ],
        correctId: [0],
        answer: '',
      },
      {
        id: '6.33',
        prompt: "You're cheap and frivolous, or else generous",
        options: [
          { id: 0, label: '$$ ((C \\cdot F) \\vee G) $$' },
          { id: 1, label: '$$ C \\cdot F \\vee G $$' },
          { id: 2, label: '$$ (C \\cdot (F \\vee G)) $$' },
          { id: 3, label: '$$ (C \\cdot F) \\vee G $$' },
        ],
        correctId: [0],
        answer: '',
      },
      {
        id: '6.34',
        prompt: "You're either both wild and gentle or else cheerful",
        options: [
          { id: 0, label: '$$ W \\cdot G \\vee C $$' },
          { id: 1, label: '$$ (W \\cdot (G \\vee C)) $$' },
          { id: 2, label: '$$ (W \\cdot G) \\vee C $$' },
          { id: 3, label: '$$ ((W \\cdot G) \\vee C) $$' },
        ],
        correctId: [3],
        answer: '',
      },
      {
        id: '6.35',
        prompt: "You aren't either dull or boastful",
        options: [
          { id: 0, label: '$$ (\\sim D \\vee \\sim B) $$' },
          { id: 1, label: '$$ (\\sim D \\vee B) $$' },
          { id: 2, label: '$$ \\sim D \\vee B $$' },
          { id: 3, label: '$$ \\sim(D \\vee B) $$' },
        ],
        correctId: [3],
        answer: '',
      },
      {
        id: '6.36',
        prompt: "You aren't both not creative and notorious",
        options: [
          { id: 0, label: '$$ \\sim(\\sim C \\cdot N) $$' },
          { id: 1, label: '$$ (C \\cdot N) $$' },
          { id: 2, label: '$$ \\sim\\sim C \\cdot N $$' },
          { id: 3, label: '$$ C \\cdot N $$' },
        ],
        correctId: [0],
        answer: '',
      },
      {
        id: '6.37',
        prompt: 'Not if not B then C',
        options: [
          { id: 0, label: '$$ \\sim\\sim B \\rightarrow C $$' },
          { id: 1, label: '$$ B \\rightarrow C $$' },
          { id: 2, label: '$$ \\sim(\\sim B \\rightarrow C) $$' },
          { id: 3, label: '$$ (B \\rightarrow C) $$' },
        ],
        correctId: [2],
        answer: '',
      },
      {
        id: '6.38',
        prompt: "You're both bright and either forgetful or confident",
        options: [
          { id: 0, label: '$$ ((B \\cdot F) \\vee C) $$' },
          { id: 1, label: '$$ (B \\cdot F) \\vee C $$' },
          { id: 2, label: '$$ B \\cdot F \\vee C $$' },
          { id: 3, label: '$$ (B \\cdot (F \\vee C)) $$' },
        ],
        correctId: [3],
        answer: '',
      },
      {
        id: '6.39',
        prompt: 'Not either W or C',
        options: [
          { id: 0, label: '$$ (\\sim W \\vee \\sim C) $$' },
          { id: 1, label: '$$ \\sim W \\vee C $$' },
          { id: 2, label: '$$ (\\sim W \\vee C) $$' },
          { id: 3, label: '$$ \\sim(W \\vee C) $$' },
        ],
        correctId: [3],
        answer: '',
      },
      {
        id: '6.40',
        prompt: "You're tall, and mediocre or colorful",
        options: [
          { id: 0, label: '$$ (T \\cdot M) \\vee C $$' },
          { id: 1, label: '$$ (T \\cdot (M \\vee C)) $$' },
          { id: 2, label: '$$ ((T \\cdot M) \\vee C) $$' },
          { id: 3, label: '$$ T \\cdot M \\vee C $$' },
        ],
        correctId: [1],
        answer: '',
      },
      {
        id: '6.41',
        prompt: 'If D then M, and L',
        options: [
          { id: 0, label: '$$ D \\rightarrow M \\cdot L $$' },
          { id: 1, label: '$$ (D \\rightarrow M) \\cdot L $$' },
          { id: 2, label: '$$ (D \\rightarrow (M \\cdot L)) $$' },
          { id: 3, label: '$$ ((D \\rightarrow M) \\cdot L) $$' },
        ],
        correctId: [3],
        answer: '',
      },
      {
        id: '6.42',
        prompt: 'Not both L and N',
        options: [
          { id: 0, label: '$$ (\\sim L \\cdot \\sim N) $$' },
          { id: 1, label: '$$ \\sim L \\cdot N $$' },
          { id: 2, label: '$$ \\sim(L \\cdot N) $$' },
          { id: 3, label: '$$ (\\sim L \\cdot N) $$' },
        ],
        correctId: [2],
        answer: '',
      },
      {
        id: '6.43',
        prompt: 'Either not B or P',
        options: [
          { id: 0, label: '$$ \\sim(B \\vee P) $$' },
          { id: 1, label: '$$ \\sim B \\vee P $$' },
          { id: 2, label: '$$ (\\sim B \\vee P) $$' },
          { id: 3, label: '$$ (\\sim B \\vee \\sim P) $$' },
        ],
        correctId: [2],
        answer: '',
      },
      {
        id: '6.44',
        prompt: "You're both not sarcastic and not bashful",
        options: [
          { id: 0, label: '$$ (\\sim S \\cdot B) $$' },
          { id: 1, label: '$$ (\\sim S \\cdot \\sim B) $$' },
          { id: 2, label: '$$ \\sim(S \\cdot \\sim B) $$' },
          { id: 3, label: '$$ \\sim S \\cdot \\sim B $$' },
        ],
        correctId: [1],
        answer: '',
      },
      {
        id: '6.45',
        prompt: 'If C then S, and B',
        options: [
          { id: 0, label: '$$ (C \\rightarrow S) \\cdot B $$' },
          { id: 1, label: '$$ (C \\rightarrow (S \\cdot B)) $$' },
          { id: 2, label: '$$ C \\rightarrow S \\cdot B $$' },
          { id: 3, label: '$$ ((C \\rightarrow S) \\cdot B) $$' },
        ],
        correctId: [3],
        answer: '',
      },
      {
        id: '6.46',
        prompt: "If you're strong then you're talented, or you're cautious",
        options: [
          { id: 0, label: '$$ (S \\rightarrow T) \\vee C $$' },
          { id: 1, label: '$$ (S \\rightarrow (T \\vee C)) $$' },
          { id: 2, label: '$$ S \\rightarrow T \\vee C $$' },
          { id: 3, label: '$$ ((S \\rightarrow T) \\vee C) $$' },
        ],
        correctId: [3],
        answer: '',
      },
      {
        id: '6.47',
        prompt: "If you aren't tall then you aren't frightened",
        options: [
          { id: 0, label: '$$ (\\sim T \\rightarrow \\sim F) $$' },
          { id: 1, label: '$$ \\sim(T \\rightarrow \\sim F) $$' },
          { id: 2, label: '$$ \\sim T \\rightarrow \\sim F $$' },
          { id: 3, label: '$$ (\\sim T \\rightarrow F) $$' },
        ],
        correctId: [0],
        answer: '',
      },
      {
        id: '6.48',
        prompt: 'Both not P and not B',
        options: [
          { id: 0, label: '$$ \\sim P \\cdot \\sim B $$' },
          { id: 1, label: '$$ \\sim(P \\cdot \\sim B) $$' },
          { id: 2, label: '$$ (\\sim P \\cdot \\sim B) $$' },
          { id: 3, label: '$$ (\\sim P \\cdot B) $$' },
        ],
        correctId: [2],
        answer: '',
      },
      {
        id: '6.49',
        prompt: 'If P, then C or D',
        options: [
          { id: 0, label: '$$ (P \\rightarrow (C \\vee D)) $$' },
          { id: 1, label: '$$ ((P \\rightarrow C) \\vee D) $$' },
          { id: 2, label: '$$ P \\rightarrow C \\vee D $$' },
          { id: 3, label: '$$ (P \\rightarrow C) \\vee D $$' },
        ],
        correctId: [0],
        answer: '',
      },
      {
        id: '6.50',
        prompt: 'Both not C and F',
        options: [
          { id: 0, label: '$$ \\sim C \\cdot F $$' },
          { id: 1, label: '$$ (\\sim C \\cdot \\sim F) $$' },
          { id: 2, label: '$$ \\sim(C \\cdot F) $$' },
          { id: 3, label: '$$ (\\sim C \\cdot F) $$' },
        ],
        correctId: [3],
        answer: '',
      },
      {
        id: '6.51',
        prompt: "If you aren't tough then you're greedy",
        options: [
          { id: 0, label: '$$ (\\sim T \\rightarrow G) $$' },
          { id: 1, label: '$$ \\sim T \\rightarrow G $$' },
          { id: 2, label: '$$ (\\sim T \\rightarrow \\sim G) $$' },
          { id: 3, label: '$$ \\sim(T \\rightarrow G) $$' },
        ],
        correctId: [0],
        answer: '',
      },
      {
        id: '6.52',
        prompt: "If you're weak and hideous, then you're candid",
        options: [
          { id: 0, label: '$$ W \\cdot H \\rightarrow C $$' },
          { id: 1, label: '$$ (W \\cdot (H \\rightarrow C)) $$' },
          { id: 2, label: '$$ ((W \\cdot H) \\rightarrow C) $$' },
          { id: 3, label: '$$ (W \\cdot H) \\rightarrow C $$' },
        ],
        correctId: [2],
        answer: '',
      },
      {
        id: '6.53',
        prompt: "You aren't both not fortunate and loveable",
        options: [
          { id: 0, label: '$$ F \\cdot L $$' },
          { id: 1, label: '$$ (F \\cdot L) $$' },
          { id: 2, label: '$$ \\sim(\\sim F \\cdot L) $$' },
          { id: 3, label: '$$ \\sim\\sim F \\cdot L $$' },
        ],
        correctId: [2],
        answer: '',
      },
      {
        id: '6.54',
        prompt: "You're cruel and lonely, or else humorous",
        options: [
          { id: 0, label: '$$ ((C \\cdot L) \\vee H) $$' },
          { id: 1, label: '$$ (C \\cdot L) \\vee H $$' },
          { id: 2, label: '$$ C \\cdot L \\vee H $$' },
          { id: 3, label: '$$ (C \\cdot (L \\vee H)) $$' },
        ],
        correctId: [0],
        answer: '',
      },
      {
        id: '6.55',
        prompt: 'If P, then D and N',
        options: [
          { id: 0, label: '$$ P \\rightarrow D \\cdot N $$' },
          { id: 1, label: '$$ ((P \\rightarrow D) \\cdot N) $$' },
          { id: 2, label: '$$ (P \\rightarrow D) \\cdot N $$' },
          { id: 3, label: '$$ (P \\rightarrow (D \\cdot N)) $$' },
        ],
        correctId: [3],
        answer: '',
      },
      {
        id: '6.56',
        prompt: 'Not if R then C',
        options: [
          { id: 0, label: '$$ (\\sim R \\rightarrow \\sim C) $$' },
          { id: 1, label: '$$ \\sim R \\rightarrow C $$' },
          { id: 2, label: '$$ \\sim(R \\rightarrow C) $$' },
          { id: 3, label: '$$ (\\sim R \\rightarrow C) $$' },
        ],
        correctId: [2],
        answer: '',
      },
      {
        id: '6.57',
        prompt: "It is false that if you aren't bright then you're careful",
        options: [
          { id: 0, label: '$$ B \\rightarrow C $$' },
          { id: 1, label: '$$ \\sim(\\sim B \\rightarrow C) $$' },
          { id: 2, label: '$$ (B \\rightarrow C) $$' },
          { id: 3, label: '$$ \\sim\\sim B \\rightarrow C $$' },
        ],
        correctId: [1],
        answer: '',
      },
      {
        id: '6.58',
        prompt: "You're either tough and cautious or else frivolous",
        options: [
          { id: 0, label: '$$ (T \\cdot C) \\vee F $$' },
          { id: 1, label: '$$ (T \\cdot (C \\vee F)) $$' },
          { id: 2, label: '$$ T \\cdot C \\vee F $$' },
          { id: 3, label: '$$ ((T \\cdot C) \\vee F) $$' },
        ],
        correctId: [3],
        answer: '',
      },
      {
        id: '6.59',
        prompt: "You're both weak and either charming or prosperous",
        options: [
          { id: 0, label: '$$ (W \\cdot (C \\vee P)) $$' },
          { id: 1, label: '$$ (W \\cdot C) \\vee P $$' },
          { id: 2, label: '$$ W \\cdot C \\vee P $$' },
          { id: 3, label: '$$ ((W \\cdot C) \\vee P) $$' },
        ],
        correctId: [0],
        answer: '',
      },
      {
        id: '6.60',
        prompt: "If you're tall then you're realistic, and you're boastful",
        options: [
          { id: 0, label: '$$ T \\rightarrow R \\cdot B $$' },
          { id: 1, label: '$$ (T \\rightarrow (R \\cdot B)) $$' },
          { id: 2, label: '$$ (T \\rightarrow R) \\cdot B $$' },
          { id: 3, label: '$$ ((T \\rightarrow R) \\cdot B) $$' },
        ],
        correctId: [3],
        answer: '',
      },
      {
        id: '6.61',
        prompt: "If you're clean then you're powerful, or you're lively",
        options: [
          { id: 0, label: '$$ ((C \\rightarrow P) \\vee L) $$' },
          { id: 1, label: '$$ C \\rightarrow P \\vee L $$' },
          { id: 2, label: '$$ (C \\rightarrow P) \\vee L $$' },
          { id: 3, label: '$$ (C \\rightarrow (P \\vee L)) $$' },
        ],
        correctId: [0],
        answer: '',
      },
      {
        id: '6.62',
        prompt: "You're short, and creative or dishonest",
        options: [
          { id: 0, label: '$$ (S \\cdot C) \\vee D $$' },
          { id: 1, label: '$$ (S \\cdot (C \\vee D)) $$' },
          { id: 2, label: '$$ S \\cdot C \\vee D $$' },
          { id: 3, label: '$$ ((S \\cdot C) \\vee D) $$' },
        ],
        correctId: [1],
        answer: '',
      },
    ],
  },
  {
    id: 3,
    title: 'Meanings and Definitions',
    header: 'What is wrong with this definition?',
    questions: [
      {
        id: '3.1',
        prompt: 'Science is that cold and empty worship of experiments.',
        options: [
          { id: 0, label: 'Too broad' },
          { id: 1, label: 'Too narrow' },
          { id: 2, label: 'Circular' },
          { id: 3, label: 'Uses poorly understood terms' },
          { id: 4, label: 'Poor match in vagueness' },
          { id: 5, label: 'Poor match in emotional tone' },
          { id: 6, label: 'Has non-essential properties' },
        ],
        correctId: [3, 5],
        answer: 'This violates 4 and 6',
      },
      {
        id: '3.2',
        prompt: 'A tent is a movable dwelling made of canvas.',
        options: [
          { id: 0, label: 'Too broad' },
          { id: 1, label: 'Too narrow' },
          { id: 2, label: 'Circular' },
          { id: 3, label: 'Uses poorly understood terms' },
          { id: 4, label: 'Poor match in vagueness' },
          { id: 5, label: 'Poor match in emotional tone' },
          { id: 6, label: 'Has non-essential properties' },
        ],
        correctId: [1],
        answer: 'This violates 2 (tents might be made of nylon)',
      },
      {
        id: '3.3',
        prompt: 'Philosophy is the study of the human condition.',
        options: [
          { id: 0, label: 'Too broad' },
          { id: 1, label: 'Too narrow' },
          { id: 2, label: 'Circular' },
          { id: 3, label: 'Uses poorly understood terms' },
          { id: 4, label: 'Poor match in vagueness' },
          { id: 5, label: 'Poor match in emotional tone' },
          { id: 6, label: 'Has non-essential properties' },
        ],
        correctId: [0],
        answer: 'This violates 1.',
      },
      {
        id: '3.4',
        prompt: 'Logic is that dreadful discipline that analyses reasoning.',
        options: [
          { id: 0, label: 'Too broad' },
          { id: 1, label: 'Too narrow' },
          { id: 2, label: 'Circular' },
          { id: 3, label: 'Uses poorly understood terms' },
          { id: 4, label: 'Poor match in vagueness' },
          { id: 5, label: 'Poor match in emotional tone' },
          { id: 6, label: 'Has non-essential properties' },
        ],
        correctId: [5],
        answer: 'This violates 6.',
      },
      {
        id: '3.5',
        prompt: 'An old person is anyone over seventy.',
        options: [
          { id: 0, label: 'Too broad' },
          { id: 1, label: 'Too narrow' },
          { id: 2, label: 'Circular' },
          { id: 3, label: 'Uses poorly understood terms' },
          { id: 4, label: 'Poor match in vagueness' },
          { id: 5, label: 'Poor match in emotional tone' },
          { id: 6, label: 'Has non-essential properties' },
        ],
        correctId: [4],
        answer: 'This violates 5.',
      },
      {
        id: '3.6',
        prompt: 'A game is an amusing competition between various players.',
        options: [
          { id: 0, label: 'Too broad' },
          { id: 1, label: 'Too narrow' },
          { id: 2, label: 'Circular' },
          { id: 3, label: 'Uses poorly understood terms' },
          { id: 4, label: 'Poor match in vagueness' },
          { id: 5, label: 'Poor match in emotional tone' },
          { id: 6, label: 'Has non-essential properties' },
        ],
        correctId: [1],
        answer:
          'This violates 2 (solitary and many computer games can involve only a single player).',
      },
      {
        id: '3.7',
        prompt: 'A logician is an obnoxious hair-splitter.',
        options: [
          { id: 0, label: 'Too broad' },
          { id: 1, label: 'Too narrow' },
          { id: 2, label: 'Circular' },
          { id: 3, label: 'Uses poorly understood terms' },
          { id: 4, label: 'Poor match in vagueness' },
          { id: 5, label: 'Poor match in emotional tone' },
          { id: 6, label: 'Has non-essential properties' },
        ],
        correctId: [5],
        answer: 'This violates 6.',
      },
      {
        id: '3.8',
        prompt: 'A fish is an animal that lives mainly in the water.',
        options: [
          { id: 0, label: 'Too broad' },
          { id: 1, label: 'Too narrow' },
          { id: 2, label: 'Circular' },
          { id: 3, label: 'Uses poorly understood terms' },
          { id: 4, label: 'Poor match in vagueness' },
          { id: 5, label: 'Poor match in emotional tone' },
          { id: 6, label: 'Has non-essential properties' },
        ],
        correctId: [0],
        answer: 'This violates 1 (whales are not fish).',
      },
      {
        id: '3.9',
        prompt: 'A male is whatever has male reproductive organs.',
        options: [
          { id: 0, label: 'Too broad' },
          { id: 1, label: 'Too narrow' },
          { id: 2, label: 'Circular' },
          { id: 3, label: 'Uses poorly understood terms' },
          { id: 4, label: 'Poor match in vagueness' },
          { id: 5, label: 'Poor match in emotional tone' },
          { id: 6, label: 'Has non-essential properties' },
        ],
        correctId: [1, 2],
        answer: 'This violates 3 (and 2, if we consider castration).',
      },
      {
        id: '3.10',
        prompt: 'A police officer is a mere cop.',
        options: [
          { id: 0, label: 'Too broad' },
          { id: 1, label: 'Too narrow' },
          { id: 2, label: 'Circular' },
          { id: 3, label: 'Uses poorly understood terms' },
          { id: 4, label: 'Poor match in vagueness' },
          { id: 5, label: 'Poor match in emotional tone' },
          { id: 6, label: 'Has non-essential properties' },
        ],
        correctId: [5],
        answer: 'This violates 6.',
      },
      {
        id: '3.11',
        prompt: '"Uncle" means "brother of a parent".',
        options: [
          { id: 0, label: 'Too broad' },
          { id: 1, label: 'Too narrow' },
          { id: 2, label: 'Circular' },
          { id: 3, label: 'Uses poorly understood terms' },
          { id: 4, label: 'Poor match in vagueness' },
          { id: 5, label: 'Poor match in emotional tone' },
          { id: 6, label: 'Has non-essential properties' },
        ],
        correctId: [1],
        answer:
          'This violates 2 (an only child can be an uncle by being married to a sister of a parent).',
      },
      {
        id: '3.12',
        prompt: 'Knowledge is a true belief that is absolutely certain.',
        options: [
          { id: 0, label: 'Too broad' },
          { id: 1, label: 'Too narrow' },
          { id: 2, label: 'Circular' },
          { id: 3, label: 'Uses poorly understood terms' },
          { id: 4, label: 'Poor match in vagueness' },
          { id: 5, label: 'Poor match in emotional tone' },
          { id: 6, label: 'Has non-essential properties' },
        ],
        correctId: [1],
        answer: 'This violates 2 (most knowledge is not absolutely certain).',
      },
      {
        id: '3.13',
        prompt: 'A bachelor is an unmarried man who weighs over 50 pounds.',
        options: [
          { id: 0, label: 'Too broad' },
          { id: 1, label: 'Too narrow' },
          { id: 2, label: 'Circular' },
          { id: 3, label: 'Uses poorly understood terms' },
          { id: 4, label: 'Poor match in vagueness' },
          { id: 5, label: 'Poor match in emotional tone' },
          { id: 6, label: 'Has non-essential properties' },
        ],
        correctId: [6],
        answer: 'This violates 7.',
      },
      {
        id: '3.14',
        prompt: 'Triangles are what you study in geometry.',
        options: [
          { id: 0, label: 'Too broad' },
          { id: 1, label: 'Too narrow' },
          { id: 2, label: 'Circular' },
          { id: 3, label: 'Uses poorly understood terms' },
          { id: 4, label: 'Poor match in vagueness' },
          { id: 5, label: 'Poor match in emotional tone' },
          { id: 6, label: 'Has non-essential properties' },
        ],
        correctId: [0],
        answer: 'This violates 1 (you study other things too).',
      },
      {
        id: '3.15',
        prompt: 'Architecture is frozen music.',
        options: [
          { id: 0, label: 'Too broad' },
          { id: 1, label: 'Too narrow' },
          { id: 2, label: 'Circular' },
          { id: 3, label: 'Uses poorly understood terms' },
          { id: 4, label: 'Poor match in vagueness' },
          { id: 5, label: 'Poor match in emotional tone' },
          { id: 6, label: 'Has non-essential properties' },
        ],
        correctId: [3],
        answer: 'This violates 4.',
      },
      {
        id: '3.16',
        prompt: 'An apple is a red fruit.',
        options: [
          { id: 0, label: 'Too broad' },
          { id: 1, label: 'Too narrow' },
          { id: 2, label: 'Circular' },
          { id: 3, label: 'Uses poorly understood terms' },
          { id: 4, label: 'Poor match in vagueness' },
          { id: 5, label: 'Poor match in emotional tone' },
          { id: 6, label: 'Has non-essential properties' },
        ],
        correctId: [0, 1],
        answer:
          'This violates 1 (consider strawberries) and 2 (consider green apples).',
      },
      {
        id: '3.17',
        prompt: 'A warm day is one that is over 86 degrees Fahrenheit.',
        options: [
          { id: 0, label: 'Too broad' },
          { id: 1, label: 'Too narrow' },
          { id: 2, label: 'Circular' },
          { id: 3, label: 'Uses poorly understood terms' },
          { id: 4, label: 'Poor match in vagueness' },
          { id: 5, label: 'Poor match in emotional tone' },
          { id: 6, label: 'Has non-essential properties' },
        ],
        correctId: [4],
        answer: 'This violates 5.',
      },
      {
        id: '3.18',
        prompt: 'Religion is a way of life based on belief in a supreme being.',
        options: [
          { id: 0, label: 'Too broad' },
          { id: 1, label: 'Too narrow' },
          { id: 2, label: 'Circular' },
          { id: 3, label: 'Uses poorly understood terms' },
          { id: 4, label: 'Poor match in vagueness' },
          { id: 5, label: 'Poor match in emotional tone' },
          { id: 6, label: 'Has non-essential properties' },
        ],
        correctId: [1],
        answer: 'This violates 2 (some religions believe in many gods).',
      },
      {
        id: '3.19',
        prompt: 'A university instructor is just an egghead.',
        options: [
          { id: 0, label: 'Too broad' },
          { id: 1, label: 'Too narrow' },
          { id: 2, label: 'Circular' },
          { id: 3, label: 'Uses poorly understood terms' },
          { id: 4, label: 'Poor match in vagueness' },
          { id: 5, label: 'Poor match in emotional tone' },
          { id: 6, label: 'Has non-essential properties' },
        ],
        correctId: [5],
        answer: 'This violates 6.',
      },
      {
        id: '3.20',
        prompt: '"True" means "proved to be true".',
        options: [
          { id: 0, label: 'Too broad' },
          { id: 1, label: 'Too narrow' },
          { id: 2, label: 'Circular' },
          { id: 3, label: 'Uses poorly understood terms' },
          { id: 4, label: 'Poor match in vagueness' },
          { id: 5, label: 'Poor match in emotional tone' },
          { id: 6, label: 'Has non-essential properties' },
        ],
        correctId: [1, 2],
        answer: 'This violates 2 and especially 3.',
      },
      {
        id: '3.21',
        prompt: 'A chair is whatever is used as a chair.',
        options: [
          { id: 0, label: 'Too broad' },
          { id: 1, label: 'Too narrow' },
          { id: 2, label: 'Circular' },
          { id: 3, label: 'Uses poorly understood terms' },
          { id: 4, label: 'Poor match in vagueness' },
          { id: 5, label: 'Poor match in emotional tone' },
          { id: 6, label: 'Has non-essential properties' },
        ],
        correctId: [2],
        answer: 'This violates 3.',
      },
      {
        id: '3.22',
        prompt: 'A teacher is one who instructs children.',
        options: [
          { id: 0, label: 'Too broad' },
          { id: 1, label: 'Too narrow' },
          { id: 2, label: 'Circular' },
          { id: 3, label: 'Uses poorly understood terms' },
          { id: 4, label: 'Poor match in vagueness' },
          { id: 5, label: 'Poor match in emotional tone' },
          { id: 6, label: 'Has non-essential properties' },
        ],
        correctId: [1],
        answer: 'This violates 2.',
      },
      {
        id: '3.23',
        prompt: 'A net is anything with interstitial vaculties.',
        options: [
          { id: 0, label: 'Too broad' },
          { id: 1, label: 'Too narrow' },
          { id: 2, label: 'Circular' },
          { id: 3, label: 'Uses poorly understood terms' },
          { id: 4, label: 'Poor match in vagueness' },
          { id: 5, label: 'Poor match in emotional tone' },
          { id: 6, label: 'Has non-essential properties' },
        ],
        correctId: [3],
        answer: 'This violates 4.',
      },
      {
        id: '3.24',
        prompt: 'Cars are vehicles powered by gasoline.',
        options: [
          { id: 0, label: 'Too broad' },
          { id: 1, label: 'Too narrow' },
          { id: 2, label: 'Circular' },
          { id: 3, label: 'Uses poorly understood terms' },
          { id: 4, label: 'Poor match in vagueness' },
          { id: 5, label: 'Poor match in emotional tone' },
          { id: 6, label: 'Has non-essential properties' },
        ],
        correctId: [0, 1],
        answer:
          'This violates 1 (consider motorcycles) and 2 (some cars run on hydrogen, electricity, or ethanol).',
      },
      {
        id: '3.25',
        prompt: 'Bread is the staff (stuff?) of life.',
        options: [
          { id: 0, label: 'Too broad' },
          { id: 1, label: 'Too narrow' },
          { id: 2, label: 'Circular' },
          { id: 3, label: 'Uses poorly understood terms' },
          { id: 4, label: 'Poor match in vagueness' },
          { id: 5, label: 'Poor match in emotional tone' },
          { id: 6, label: 'Has non-essential properties' },
        ],
        correctId: [3],
        answer: 'This violates 4.',
      },
      {
        id: '3.26',
        prompt: '"God" means "object of ultimate concern".',
        options: [
          { id: 0, label: 'Too broad' },
          { id: 1, label: 'Too narrow' },
          { id: 2, label: 'Circular' },
          { id: 3, label: 'Uses poorly understood terms' },
          { id: 4, label: 'Poor match in vagueness' },
          { id: 5, label: 'Poor match in emotional tone' },
          { id: 6, label: 'Has non-essential properties' },
        ],
        correctId: [0, 1],
        answer:
          'This violates 1 and 2 (one might have an ultimate concern for something other than God).',
      },
      {
        id: '3.27',
        prompt: 'A piano is any musical instrument with keys to select notes.',
        options: [
          { id: 0, label: 'Too broad' },
          { id: 1, label: 'Too narrow' },
          { id: 2, label: 'Circular' },
          { id: 3, label: 'Uses poorly understood terms' },
          { id: 4, label: 'Poor match in vagueness' },
          { id: 5, label: 'Poor match in emotional tone' },
          { id: 6, label: 'Has non-essential properties' },
        ],
        correctId: [0],
        answer: 'This violates 1 (consider pipe organs).',
      },
      {
        id: '3.28',
        prompt:
          'A pro football player is someone who works for a pro football team.',
        options: [
          { id: 0, label: 'Too broad' },
          { id: 1, label: 'Too narrow' },
          { id: 2, label: 'Circular' },
          { id: 3, label: 'Uses poorly understood terms' },
          { id: 4, label: 'Poor match in vagueness' },
          { id: 5, label: 'Poor match in emotional tone' },
          { id: 6, label: 'Has non-essential properties' },
        ],
        correctId: [0],
        answer: 'This violates 1 (coaches also work for such teams).',
      },
      {
        id: '3.29',
        prompt: 'A man is a featherless biped.',
        options: [
          { id: 0, label: 'Too broad' },
          { id: 1, label: 'Too narrow' },
          { id: 2, label: 'Circular' },
          { id: 3, label: 'Uses poorly understood terms' },
          { id: 4, label: 'Poor match in vagueness' },
          { id: 5, label: 'Poor match in emotional tone' },
          { id: 6, label: 'Has non-essential properties' },
        ],
        correctId: [0, 1, 6],
        answer:
          'This violates 7 (and maybe 1 and 2 — if you consider plucked chickens and humans with one leg).',
      },
      {
        id: '3.30',
        prompt: 'Punishment is anything unpleasant done to a person.',
        options: [
          { id: 0, label: 'Too broad' },
          { id: 1, label: 'Too narrow' },
          { id: 2, label: 'Circular' },
          { id: 3, label: 'Uses poorly understood terms' },
          { id: 4, label: 'Poor match in vagueness' },
          { id: 5, label: 'Poor match in emotional tone' },
          { id: 6, label: 'Has non-essential properties' },
        ],
        correctId: [0],
        answer:
          'This violates 1 (dentists drilling your teeth are not punishing you).',
      },
      {
        id: '3.31',
        prompt: 'A king is the ruler of a country.',
        options: [
          { id: 0, label: 'Too broad' },
          { id: 1, label: 'Too narrow' },
          { id: 2, label: 'Circular' },
          { id: 3, label: 'Uses poorly understood terms' },
          { id: 4, label: 'Poor match in vagueness' },
          { id: 5, label: 'Poor match in emotional tone' },
          { id: 6, label: 'Has non-essential properties' },
        ],
        correctId: [0],
        answer: 'This violates 1 (consider presidents and dictators).',
      },
      {
        id: '3.32',
        prompt: 'Backpacking is the enduring of misery by living out of doors.',
        options: [
          { id: 0, label: 'Too broad' },
          { id: 1, label: 'Too narrow' },
          { id: 2, label: 'Circular' },
          { id: 3, label: 'Uses poorly understood terms' },
          { id: 4, label: 'Poor match in vagueness' },
          { id: 5, label: 'Poor match in emotional tone' },
          { id: 6, label: 'Has non-essential properties' },
        ],
        correctId: [0, 1, 5],
        answer: 'This violates 1, 2 and 6.',
      },
      {
        id: '3.33',
        prompt: 'Knowledge is true belief.',
        options: [
          { id: 0, label: 'Too broad' },
          { id: 1, label: 'Too narrow' },
          { id: 2, label: 'Circular' },
          { id: 3, label: 'Uses poorly understood terms' },
          { id: 4, label: 'Poor match in vagueness' },
          { id: 5, label: 'Poor match in emotional tone' },
          { id: 6, label: 'Has non-essential properties' },
        ],
        correctId: [0],
        answer: 'This violates 1 (a true belief might be a lucky guess).',
      },
      {
        id: '3.34',
        prompt:
          'A belief is the closing of a phase of an intellectual symphony.',
        options: [
          { id: 0, label: 'Too broad' },
          { id: 1, label: 'Too narrow' },
          { id: 2, label: 'Circular' },
          { id: 3, label: 'Uses poorly understood terms' },
          { id: 4, label: 'Poor match in vagueness' },
          { id: 5, label: 'Poor match in emotional tone' },
          { id: 6, label: 'Has non-essential properties' },
        ],
        correctId: [3],
        answer: 'This violates 4.',
      },
      {
        id: '3.35',
        prompt: 'A politician is a scoundrel involved in politics.',
        options: [
          { id: 0, label: 'Too broad' },
          { id: 1, label: 'Too narrow' },
          { id: 2, label: 'Circular' },
          { id: 3, label: 'Uses poorly understood terms' },
          { id: 4, label: 'Poor match in vagueness' },
          { id: 5, label: 'Poor match in emotional tone' },
          { id: 6, label: 'Has non-essential properties' },
        ],
        correctId: [1, 5],
        answer: 'This violates 2 (some are honest) and 6.',
      },
      {
        id: '3.36',
        prompt:
          'Philosophy is the attempt to transcend cognitive subjectivity.',
        options: [
          { id: 0, label: 'Too broad' },
          { id: 1, label: 'Too narrow' },
          { id: 2, label: 'Circular' },
          { id: 3, label: 'Uses poorly understood terms' },
          { id: 4, label: 'Poor match in vagueness' },
          { id: 5, label: 'Poor match in emotional tone' },
          { id: 6, label: 'Has non-essential properties' },
        ],
        correctId: [3],
        answer: 'This violates 4.',
      },
      {
        id: '3.37',
        prompt: 'A doctor is a man who is licensed to practice medicine.',
        options: [
          { id: 0, label: 'Too broad' },
          { id: 1, label: 'Too narrow' },
          { id: 2, label: 'Circular' },
          { id: 3, label: 'Uses poorly understood terms' },
          { id: 4, label: 'Poor match in vagueness' },
          { id: 5, label: 'Poor match in emotional tone' },
          { id: 6, label: 'Has non-essential properties' },
        ],
        correctId: [1],
        answer: 'This violates 2 (many doctors are women).',
      },
      {
        id: '3.38',
        prompt:
          '"Human being" means "whatever is descended from human beings".',
        options: [
          { id: 0, label: 'Too broad' },
          { id: 1, label: 'Too narrow' },
          { id: 2, label: 'Circular' },
          { id: 3, label: 'Uses poorly understood terms' },
          { id: 4, label: 'Poor match in vagueness' },
          { id: 5, label: 'Poor match in emotional tone' },
          { id: 6, label: 'Has non-essential properties' },
        ],
        correctId: [2],
        answer: 'This violates 3.',
      },
      {
        id: '3.39',
        prompt:
          'A computer is a box made by Dell that has a keyboard and a screen.',
        options: [
          { id: 0, label: 'Too broad' },
          { id: 1, label: 'Too narrow' },
          { id: 2, label: 'Circular' },
          { id: 3, label: 'Uses poorly understood terms' },
          { id: 4, label: 'Poor match in vagueness' },
          { id: 5, label: 'Poor match in emotional tone' },
          { id: 6, label: 'Has non-essential properties' },
        ],
        correctId: [1, 6],
        answer: 'This violates 2 and 7 — many other companies make computers.',
      },
      {
        id: '3.40',
        prompt: 'A lie is a falsehood that you assert to be true.',
        options: [
          { id: 0, label: 'Too broad' },
          { id: 1, label: 'Too narrow' },
          { id: 2, label: 'Circular' },
          { id: 3, label: 'Uses poorly understood terms' },
          { id: 4, label: 'Poor match in vagueness' },
          { id: 5, label: 'Poor match in emotional tone' },
          { id: 6, label: 'Has non-essential properties' },
        ],
        correctId: [0],
        answer:
          'This violates 1 (if you do not know that it is false, it is just a mistake and not a lie).',
      },
      {
        id: '3.41',
        prompt:
          'Philosophy is the discipline developed by Aristotle and Plato.',
        options: [
          { id: 0, label: 'Too broad' },
          { id: 1, label: 'Too narrow' },
          { id: 2, label: 'Circular' },
          { id: 3, label: 'Uses poorly understood terms' },
          { id: 4, label: 'Poor match in vagueness' },
          { id: 5, label: 'Poor match in emotional tone' },
          { id: 6, label: 'Has non-essential properties' },
        ],
        correctId: [6],
        answer: 'This violates 7.',
      },
      {
        id: '3.42',
        prompt: 'An adolescent is a person between 9 and 19 years-old.',
        options: [
          { id: 0, label: 'Too broad' },
          { id: 1, label: 'Too narrow' },
          { id: 2, label: 'Circular' },
          { id: 3, label: 'Uses poorly understood terms' },
          { id: 4, label: 'Poor match in vagueness' },
          { id: 5, label: 'Poor match in emotional tone' },
          { id: 6, label: 'Has non-essential properties' },
        ],
        correctId: [4],
        answer: 'This violates 5.',
      },
      {
        id: '3.43',
        prompt: 'An adult is anyone over 17.',
        options: [
          { id: 0, label: 'Too broad' },
          { id: 1, label: 'Too narrow' },
          { id: 2, label: 'Circular' },
          { id: 3, label: 'Uses poorly understood terms' },
          { id: 4, label: 'Poor match in vagueness' },
          { id: 5, label: 'Poor match in emotional tone' },
          { id: 6, label: 'Has non-essential properties' },
        ],
        correctId: [4],
        answer: 'This violates 5.',
      },
      {
        id: '3.44',
        prompt: 'Philosophy is what you study in philosophy classes.',
        options: [
          { id: 0, label: 'Too broad' },
          { id: 1, label: 'Too narrow' },
          { id: 2, label: 'Circular' },
          { id: 3, label: 'Uses poorly understood terms' },
          { id: 4, label: 'Poor match in vagueness' },
          { id: 5, label: 'Poor match in emotional tone' },
          { id: 6, label: 'Has non-essential properties' },
        ],
        correctId: [2],
        answer: 'This violates 3.',
      },
      {
        id: '3.45',
        prompt: 'A cold day is one that is under 20 degrees Fahrenheit.',
        options: [
          { id: 0, label: 'Too broad' },
          { id: 1, label: 'Too narrow' },
          { id: 2, label: 'Circular' },
          { id: 3, label: 'Uses poorly understood terms' },
          { id: 4, label: 'Poor match in vagueness' },
          { id: 5, label: 'Poor match in emotional tone' },
          { id: 6, label: 'Has non-essential properties' },
        ],
        correctId: [4],
        answer: 'This violates 5.',
      },
      {
        id: '3.46',
        prompt: "An honest person is one who doesn't steal.",
        options: [
          { id: 0, label: 'Too broad' },
          { id: 1, label: 'Too narrow' },
          { id: 2, label: 'Circular' },
          { id: 3, label: 'Uses poorly understood terms' },
          { id: 4, label: 'Poor match in vagueness' },
          { id: 5, label: 'Poor match in emotional tone' },
          { id: 6, label: 'Has non-essential properties' },
        ],
        correctId: [1],
        answer: "This violates 2 (consider liars who don't steal).",
      },
      {
        id: '3.47',
        prompt: '"Murder" means "killing of a human being."',
        options: [
          { id: 0, label: 'Too broad' },
          { id: 1, label: 'Too narrow' },
          { id: 2, label: 'Circular' },
          { id: 3, label: 'Uses poorly understood terms' },
          { id: 4, label: 'Poor match in vagueness' },
          { id: 5, label: 'Poor match in emotional tone' },
          { id: 6, label: 'Has non-essential properties' },
        ],
        correctId: [0],
        answer: 'This violates 1 (consider accidental killing).',
      },
      {
        id: '3.48',
        prompt: 'A liberal is a permissive do-gooder who knows nothing.',
        options: [
          { id: 0, label: 'Too broad' },
          { id: 1, label: 'Too narrow' },
          { id: 2, label: 'Circular' },
          { id: 3, label: 'Uses poorly understood terms' },
          { id: 4, label: 'Poor match in vagueness' },
          { id: 5, label: 'Poor match in emotional tone' },
          { id: 6, label: 'Has non-essential properties' },
        ],
        correctId: [0, 1, 5],
        answer: 'This violates 1, 2 and especially 6.',
      },
      {
        id: '3.49',
        prompt: 'Logic is that wonderful discipline that analyses reasoning.',
        options: [
          { id: 0, label: 'Too broad' },
          { id: 1, label: 'Too narrow' },
          { id: 2, label: 'Circular' },
          { id: 3, label: 'Uses poorly understood terms' },
          { id: 4, label: 'Poor match in vagueness' },
          { id: 5, label: 'Poor match in emotional tone' },
          { id: 6, label: 'Has non-essential properties' },
        ],
        correctId: [5],
        answer: 'This violates 6.',
      },
      {
        id: '3.50',
        prompt: '"Chair" means "what you sit on."',
        options: [
          { id: 0, label: 'Too broad' },
          { id: 1, label: 'Too narrow' },
          { id: 2, label: 'Circular' },
          { id: 3, label: 'Uses poorly understood terms' },
          { id: 4, label: 'Poor match in vagueness' },
          { id: 5, label: 'Poor match in emotional tone' },
          { id: 6, label: 'Has non-essential properties' },
        ],
        correctId: [0, 1],
        answer:
          'This violates 1 (we sit on other things) and perhaps 2 (if there are decorative chairs that no one sits on).',
      },
      {
        id: '3.51',
        prompt: 'A conservative is an inflexible person who never thinks.',
        options: [
          { id: 0, label: 'Too broad' },
          { id: 1, label: 'Too narrow' },
          { id: 2, label: 'Circular' },
          { id: 3, label: 'Uses poorly understood terms' },
          { id: 4, label: 'Poor match in vagueness' },
          { id: 5, label: 'Poor match in emotional tone' },
          { id: 6, label: 'Has non-essential properties' },
        ],
        correctId: [0, 1, 5],
        answer: 'This violates 1, 2 and especially 6.',
      },
      {
        id: '3.52',
        prompt: 'A wrong action is one that is against the law.',
        options: [
          { id: 0, label: 'Too broad' },
          { id: 1, label: 'Too narrow' },
          { id: 2, label: 'Circular' },
          { id: 3, label: 'Uses poorly understood terms' },
          { id: 4, label: 'Poor match in vagueness' },
          { id: 5, label: 'Poor match in emotional tone' },
          { id: 6, label: 'Has non-essential properties' },
        ],
        correctId: [0, 1],
        answer: 'This violates 1 and 2.',
      },
      {
        id: '3.53',
        prompt: 'A child is anyone between 2 and 12 years old.',
        options: [
          { id: 0, label: 'Too broad' },
          { id: 1, label: 'Too narrow' },
          { id: 2, label: 'Circular' },
          { id: 3, label: 'Uses poorly understood terms' },
          { id: 4, label: 'Poor match in vagueness' },
          { id: 5, label: 'Poor match in emotional tone' },
          { id: 6, label: 'Has non-essential properties' },
        ],
        correctId: [4],
        answer: 'This violates 5.',
      },
      {
        id: '3.54',
        prompt:
          'A football game is whatever is played by the rules of football.',
        options: [
          { id: 0, label: 'Too broad' },
          { id: 1, label: 'Too narrow' },
          { id: 2, label: 'Circular' },
          { id: 3, label: 'Uses poorly understood terms' },
          { id: 4, label: 'Poor match in vagueness' },
          { id: 5, label: 'Poor match in emotional tone' },
          { id: 6, label: 'Has non-essential properties' },
        ],
        correctId: [2],
        answer: 'This violates 3.',
      },
      {
        id: '3.55',
        prompt: 'A kitten is a young female cat.',
        options: [
          { id: 0, label: 'Too broad' },
          { id: 1, label: 'Too narrow' },
          { id: 2, label: 'Circular' },
          { id: 3, label: 'Uses poorly understood terms' },
          { id: 4, label: 'Poor match in vagueness' },
          { id: 5, label: 'Poor match in emotional tone' },
          { id: 6, label: 'Has non-essential properties' },
        ],
        correctId: [1],
        answer: 'This violates 2 (kittens can be male).',
      },
      {
        id: '3.56',
        prompt: 'Logic is defined as that subject that is treated by LogiCola.',
        options: [
          { id: 0, label: 'Too broad' },
          { id: 1, label: 'Too narrow' },
          { id: 2, label: 'Circular' },
          { id: 3, label: 'Uses poorly understood terms' },
          { id: 4, label: 'Poor match in vagueness' },
          { id: 5, label: 'Poor match in emotional tone' },
          { id: 6, label: 'Has non-essential properties' },
        ],
        correctId: [6],
        answer: 'This violates 7.',
      },
      {
        id: '3.57',
        prompt: 'Knowledge is the cognizance of a reality by an intellect.',
        options: [
          { id: 0, label: 'Too broad' },
          { id: 1, label: 'Too narrow' },
          { id: 2, label: 'Circular' },
          { id: 3, label: 'Uses poorly understood terms' },
          { id: 4, label: 'Poor match in vagueness' },
          { id: 5, label: 'Poor match in emotional tone' },
          { id: 6, label: 'Has non-essential properties' },
        ],
        correctId: [3],
        answer: 'This violates 4.',
      },
      {
        id: '3.58',
        prompt: 'A bird is an animal that can fly.',
        options: [
          { id: 0, label: 'Too broad' },
          { id: 1, label: 'Too narrow' },
          { id: 2, label: 'Circular' },
          { id: 3, label: 'Uses poorly understood terms' },
          { id: 4, label: 'Poor match in vagueness' },
          { id: 5, label: 'Poor match in emotional tone' },
          { id: 6, label: 'Has non-essential properties' },
        ],
        correctId: [0, 1],
        answer: 'This violates 1 (consider ostriches) and 2 (consider bats).',
      },
      {
        id: '3.59',
        prompt: '"Metaphysics" means "any sleep-inducing subject".',
        options: [
          { id: 0, label: 'Too broad' },
          { id: 1, label: 'Too narrow' },
          { id: 2, label: 'Circular' },
          { id: 3, label: 'Uses poorly understood terms' },
          { id: 4, label: 'Poor match in vagueness' },
          { id: 5, label: 'Poor match in emotional tone' },
          { id: 6, label: 'Has non-essential properties' },
        ],
        correctId: [0, 1, 5],
        answer: 'This violates 1, 2 and 6.',
      },
      {
        id: '3.60',
        prompt: '"Tall person" means "person over 6 feet tall."',
        options: [
          { id: 0, label: 'Too broad' },
          { id: 1, label: 'Too narrow' },
          { id: 2, label: 'Circular' },
          { id: 3, label: 'Uses poorly understood terms' },
          { id: 4, label: 'Poor match in vagueness' },
          { id: 5, label: 'Poor match in emotional tone' },
          { id: 6, label: 'Has non-essential properties' },
        ],
        correctId: [4],
        answer: 'This violates 5.',
      },
    ],
  },
  {
    id: 6.1,
    title: 'Easier Translations',
    header: 'Translates into logic as:',
    questions: [
      {
        id: '6.1a.1',
        prompt: 'Not both A and B',
        options: [
          { id: 0, label: '~(A V B)' },
          { id: 1, label: '~(A · B)' },
          { id: 2, label: '(~A · ~B)' },
          { id: 3, label: '(~A V ~B)' },
        ],
        correctId: [1],
        answer: '',
      },
      {
        id: '6.1a.2',
        prompt: 'Both A and either B or C',
        options: [
          { id: 0, label: '(A · (B V C))' },
          { id: 1, label: '(A V (B · C))' },
          { id: 2, label: '~(A · (B V C))' },
          { id: 3, label: '(A · B) V (A · C)' },
        ],
        correctId: [0],
        answer: '',
      },
      {
        id: '6.1a.3',
        prompt: 'Either both A and B or C',
        options: [
          { id: 0, label: '(A · (B V C))' },
          { id: 1, label: '~((A · B) V C)' },
          { id: 2, label: '((A · B) V C)' },
          { id: 3, label: '(A V B) · C' },
        ],
        correctId: [2],
        answer: '',
      },
      {
        id: '6.1a.4',
        prompt: 'If A, then B or C',
        options: [
          { id: 0, label: '(A · (B V C))' },
          { id: 1, label: '(A → (B V C))' },
          { id: 2, label: '~(A → (B V C))' },
          { id: 3, label: '(A V B) → C' },
        ],
        correctId: [1],
        answer: '',
      },
      {
        id: '6.1a.5',
        prompt: 'If A then B, or C',
        options: [
          { id: 0, label: '(A → (B V C))' },
          { id: 1, label: '~((A → B) V C)' },
          { id: 2, label: '(A V B) → C' },
          { id: 3, label: '(A → B) V C' },
        ],
        correctId: [3],
        answer: '',
      },
      {
        id: '6.1a.6',
        prompt: 'If not A, then not either B or C',
        options: [
          { id: 0, label: '~A → ~(B V C)' },
          { id: 1, label: '~(A → (B V C))' },
          { id: 2, label: '~(~A → (~B V C))' },
          { id: 3, label: '~A → (B V ~C)' },
        ],
        correctId: [0],
        answer: '',
      },
      {
        id: '6.1a.7',
        prompt: 'If not A, then either not B or C',
        options: [
          { id: 0, label: '~A → (~B V C)' },
          { id: 1, label: '(A → (B V C))' },
          { id: 2, label: '~(~A → (~B V C))' },
          { id: 3, label: '~A → (B V ~C)' },
        ],
        correctId: [0],
        answer: '',
      },
      {
        id: '6.1a.8',
        prompt: 'Either A or B, and C',
        options: [
          { id: 0, label: '(A · (B V C))' },
          { id: 1, label: '((A V B) · C)' },
          { id: 2, label: '~((A V B) · C)' },
          { id: 3, label: '(A V B) → C' },
        ],
        correctId: [1],
        answer: '',
      },
      {
        id: '6.1a.9',
        prompt: 'Either A, or B and C',
        options: [
          { id: 0, label: '(A · (B V C))' },
          { id: 1, label: '~(A V (B · C))' },
          { id: 2, label: '(A V B) · C' },
          { id: 3, label: '(A V (B · C))' },
        ],
        correctId: [3],
        answer: '',
      },
      {
        id: '6.1a.10',
        prompt: 'If A then not both not B and not C',
        options: [
          { id: 0, label: '(A → ~(~B · ~C))' },
          { id: 1, label: '(A · (B V C))' },
          { id: 2, label: '~(A → ~(~B · ~C))' },
          { id: 3, label: '(A → (B · C))' },
        ],
        correctId: [0],
        answer: '',
      },
      {
        id: '6.1a.11',
        prompt:
          'If you get an error message, then the disk is bad or it is a Macintosh disk.',
        options: [
          { id: 0, label: '(E · (B V M))' },
          { id: 1, label: '~(E → (B V M))' },
          { id: 2, label: 'E → (B V M)' },
          { id: 3, label: 'E → (B · M)' },
        ],
        correctId: [2],
        answer: '',
      },
      {
        id: '6.1a.12',
        prompt:
          'If I bring my digital camera, then if my batteries don’t die then I’ll take pictures of my backpack trip and put the pictures on my Web site',
        options: [
          { id: 0, label: '(C → (~B → (T · W)))' },
          { id: 1, label: '(C · (B → (T V W)))' },
          { id: 2, label: '(C → ((~B) V (T · W)))' },
          { id: 3, label: '((C · B) → (T · W))' },
        ],
        correctId: [0],
        answer: '',
      },
      {
        id: '6.1a.13',
        prompt:
          'If you both don’t exercise and eat too much then you’ll gain weight',
        options: [
          { id: 0, label: '(((~X) · M) → G)' },
          { id: 1, label: '((X V M) → G)' },
          { id: 2, label: '((~X V M) → G)' },
          { id: 3, label: '(((~X) · (~M)) → G)' },
        ],
        correctId: [0],
        answer: '',
      },
      {
        id: '6.1a.14',
        prompt: 'The statue isn’t by either Cellini or Michelangelo',
        options: [
          { id: 0, label: '~(C V M)' },
          { id: 1, label: '(~C · ~M)' },
          { id: 2, label: '(C → ~M)' },
          { id: 3, label: '(~C → M)' },
        ],
        correctId: [0],
        answer: '',
      },
      {
        id: '6.1a.15',
        prompt:
          'If I don’t have either $2 in exact change or a bus pass I won’t ride the bus',
        options: [
          { id: 0, label: '~((E V P) → R)' },
          { id: 1, label: '((~E · ~P) → ~R)' },
          { id: 2, label: '(~(E V P) → ~R)' },
          { id: 3, label: '((E V P) → ~R)' },
        ],
        correctId: [2],
        answer: '',
      },
      {
        id: '6.1a.16',
        prompt:
          'If Michigan and Ohio State play each other then Michigan will win',
        options: [
          { id: 0, label: '((M · O) → W)' },
          { id: 1, label: '(M → (O V W))' },
          { id: 2, label: '(M V (O → W))' },
          { id: 3, label: '(P → M)' },
        ],
        correctId: [3],
        answer: '',
      },
      {
        id: '6.1a.17',
        prompt:
          'Either you went through both Dayton and Cinci, or you went through Louisville',
        options: [
          { id: 0, label: '((D · C) V L)' },
          { id: 1, label: '(D → (C V L))' },
          { id: 2, label: '((D V C) · L)' },
          { id: 3, label: '(D · (C V L))' },
        ],
        correctId: [0],
        answer: '',
      },
      {
        id: '6.1a.18',
        prompt:
          'If she had hamburgers then she ate junk food, and she ate French fries',
        options: [
          { id: 0, label: '(H → (J · F))' },
          { id: 1, label: '((H → J) · F)' },
          { id: 2, label: '(H → (J V F))' },
          { id: 3, label: '((H V J) → F)' },
        ],
        correctId: [1],
        answer: '',
      },
      {
        id: '6.1a.19',
        prompt: 'I’m going to Rome or Florence and you’re going to London',
        options: [
          { id: 0, label: '((R V F) · L)' },
          { id: 1, label: '((R · F) V L)' },
          { id: 2, label: '(R → (F · L))' },
          { id: 3, label: '(R V (F · L))' },
        ],
        correctId: [0],
        answer: '',
      },
      {
        id: '6.1a.20',
        prompt: 'Everyone is male or female',
        options: [
          { id: 0, label: '(M V F)' },
          { id: 1, label: '(M → F)' },
          { id: 2, label: '(M · F)' },
          { id: 3, label: 'E' },
        ],
        correctId: [3],
        answer: '',
      },
    ],
  },
  {
    id: 6.8,
    title: 'Harder Translations',
    header: 'Translates into logic as:',
    questions: [
      {
        id: '6.8a.1',
        prompt: 'If she goes, then you’ll be alone but I’ll be here.',
        options: [
          { id: 0, label: '(S → (A · I))' },
          { id: 1, label: '(~S → (A · I))' },
          { id: 2, label: '(S → (~A · ~I))' },
          { id: 3, label: '(S V (A · I))' },
        ],
        correctId: [0],
        answer: '',
      },
      {
        id: '6.8a.2',
        prompt: 'Your car will start only if you have fuel.',
        options: [
          { id: 0, label: '(S → F)' },
          { id: 1, label: '(~S → F)' },
          { id: 2, label: '(S → ~F)' },
          { id: 3, label: '(S V F)' },
        ],
        correctId: [0],
        answer: '',
      },
      {
        id: '6.8a.3',
        prompt: 'I will quit unless you give me a raise.',
        options: [
          { id: 0, label: '(Q V R)' },
          { id: 1, label: '(~Q V R)' },
          { id: 2, label: '(Q V ~R)' },
          { id: 3, label: '(Q → R)' },
        ],
        correctId: [0],
        answer: '',
      },
      {
        id: '6.8a.4',
        prompt: 'Taking the final is a sufficient condition for passing.',
        options: [
          { id: 0, label: '(T → P)' },
          { id: 1, label: '(~T → P)' },
          { id: 2, label: '(T → ~P)' },
          { id: 3, label: '(T V P)' },
        ],
        correctId: [0],
        answer: '',
      },
      {
        id: '6.8a.5',
        prompt: 'Taking the final is necessary for you to pass.',
        options: [
          { id: 0, label: '(~T → ~P)' },
          { id: 1, label: '(T → ~P)' },
          { id: 2, label: '(~T → P)' },
          { id: 3, label: '(T V ~P)' },
        ],
        correctId: [0],
        answer: '',
      },
      {
        id: '6.8a.6',
        prompt: 'You’re a man just if you’re a rational animal.',
        options: [
          { id: 0, label: '(M ≡ R)' },
          { id: 1, label: '(M → R)' },
          { id: 2, label: '(~M ≡ R)' },
          { id: 3, label: '(M V R)' },
        ],
        correctId: [0],
        answer: '',
      },
      {
        id: '6.8a.7',
        prompt: 'Unless you have faith, you’ll die.',
        options: [
          { id: 0, label: '(F V D)' },
          { id: 1, label: '(~F V D)' },
          { id: 2, label: '(F V ~D)' },
          { id: 3, label: '(F → D)' },
        ],
        correctId: [0],
        answer: '',
      },
      {
        id: '6.8a.8',
        prompt: 'She neither asserted it nor hinted at it.',
        options: [
          { id: 0, label: '(~A · ~H)' },
          { id: 1, label: '(A · ~H)' },
          { id: 2, label: '(~A · H)' },
          { id: 3, label: '(A V ~H)' },
        ],
        correctId: [0],
        answer: '',
      },
      {
        id: '6.8a.9',
        prompt:
          'Getting at least 96 is a necessary and sufficient condition for getting an A.',
        options: [
          { id: 0, label: '(N ≡ A)' },
          { id: 1, label: '(N → A)' },
          { id: 2, label: '(~N ≡ A)' },
          { id: 3, label: '(N V A)' },
        ],
        correctId: [0],
        answer: '',
      },
      {
        id: '6.8a.10',
        prompt: 'Only if you exercise are you fully alive.',
        options: [
          { id: 0, label: '(A → E)' },
          { id: 1, label: '(~A → E)' },
          { id: 2, label: '(A → ~E)' },
          { id: 3, label: '(A V E)' },
        ],
        correctId: [0],
        answer: '',
      },
      {
        id: '6.8a.11',
        prompt: 'I’ll go, assuming that you go.',
        options: [
          { id: 0, label: '(Y → I)' },
          { id: 1, label: '(~Y → I)' },
          { id: 2, label: '(Y → ~I)' },
          { id: 3, label: '(Y V I)' },
        ],
        correctId: [0],
        answer: '',
      },
      {
        id: '6.8a.12',
        prompt: 'Assuming that your belief is false, you don’t know.',
        options: [
          { id: 0, label: '(F → ~K)' },
          { id: 1, label: '(~F → ~K)' },
          { id: 2, label: '(F → K)' },
          { id: 3, label: '(F V ~K)' },
        ],
        correctId: [0],
        answer: '',
      },
      {
        id: '6.8a.13',
        prompt:
          'Having a true belief is a necessary condition for having knowledge.',
        options: [
          { id: 0, label: '(~T → ~K)' },
          { id: 1, label: '(T → ~K)' },
          { id: 2, label: '(~T → K)' },
          { id: 3, label: '(T V ~K)' },
        ],
        correctId: [0],
        answer: '',
      },
      {
        id: '6.8a.14',
        prompt: 'You get mashed potatoes or French fries, but not both.',
        options: [
          { id: 0, label: '((M V F) · ~(M & F))' },
          { id: 1, label: '(M → F)' },
          { id: 2, label: '(~M V F)' },
          { id: 3, label: '(M V ~F)' },
        ],
        correctId: [0],
        answer: '',
      },
      {
        id: '6.8a.15',
        prompt: 'You’re wrong if you say that.',
        options: [
          { id: 0, label: '(S → W)' },
          { id: 1, label: '(~S → W)' },
          { id: 2, label: '(S → ~W)' },
          { id: 3, label: '(S V W)' },
        ],
        correctId: [0],
        answer: '',
      },
    ],
  },
];
export { chapters };
