import { describe, expect, it } from 'vitest';
import {
  camoBody,
  clearRectFor,
  FOOTER_BAND_PX,
  mulberry32,
  quiltAccentPool,
  quiltPixBody,
  r1,
} from './patterns';
import labFixtures from './__fixtures__/patterns-lab.json';

/**
 * The pattern accent pool — the lab's SET_SURFACES + Set A's magenta,
 * VERBATIM (the list every judged prototype render was made with; see
 * QUIZ_SURFACE_POOL in components/quiz/quizColors.ts). Repeated
 * literally here so a pool edit fails a test instead of passing
 * silently: refreshing this pool recolours every render and is Malik's
 * call, not a port-time tidy-up.
 */
const POOL_CANDIDATES = [
  '#1C3601',
  '#E7F099',
  '#E6ACF4',
  '#C8F0E3',
  '#ADE2E9',
  '#F2CDA6',
  '#F233DF',
];

const SET_C = { surface: '#E7F099', ink: '#02302C' };
const SET_R = { surface: '#F2CDA6', ink: '#190B45' };

/**
 * Byte-parity with the pattern lab: fixtures were generated by running
 * the lab's own quiltBase/quiltpix/filteredPool in Node. If these fail,
 * the app's quilt has drifted from every composition judged in the lab.
 */
/**
 * Rect-normalized comparison (2026-08-24): the app emits EDGE-rounded
 * one-decimal rect coordinates (lib/patterns.ts `r1`/`rectAttrs` —
 * ~176 KB off the landing page's HTML), while the lab fixtures carry
 * full float precision. Parity stays GEOMETRIC: every rect on both
 * sides is passed through the same edge-rounding (the imported `r1`,
 * never a copy), so structure, colours, ordering and any real geometry
 * drift still fail the test — only serialization precision is
 * forgiven. Applied to BOTH sides; it is idempotent on the app output.
 * Non-rect numbers (fill-opacity etc.) are left untouched.
 */
function normalizeCoords(svg: string): string {
  return svg.replace(
    /<rect x="([^"]+)" y="([^"]+)" width="([^"]+)" height="([^"]+)"/g,
    (_, xs, ys, ws, hs) => {
      const x0 = Number(xs);
      const y0 = Number(ys);
      const x = r1(x0);
      const y = r1(y0);
      const w = r1(r1(x0 + Number(ws)) - x);
      const h = r1(r1(y0 + Number(hs)) - y);
      return `<rect x="${x}" y="${y}" width="${w}" height="${h}"`;
    }
  );
}

describe('lab parity', () => {
  it('filters and orders the accent pool exactly as the lab does', () => {
    expect(quiltAccentPool(SET_C.surface, SET_C.ink, POOL_CANDIDATES)).toEqual(
      labFixtures.poolC
    );
    expect(quiltAccentPool(SET_R.surface, SET_R.ink, POOL_CANDIDATES)).toEqual(
      labFixtures.poolR
    );
  });

  it('open field: Set C, 800×600, seed 7, scale 1', () => {
    const pool = quiltAccentPool(SET_C.surface, SET_C.ink, POOL_CANDIDATES);
    expect(
      normalizeCoords(quiltPixBody({
        w: 800,
        h: 600,
        ink: SET_C.ink,
        pool,
        scale: 1,
        seed: 7,
        clear: null,
      })
      )
    ).toBe(normalizeCoords(labFixtures.openField));
  });

  it('panel clearing: Set C, 800×600, seed 42 (desktop plate numbers)', () => {
    const pool = quiltAccentPool(SET_C.surface, SET_C.ink, POOL_CANDIDATES);
    expect(
      normalizeCoords(quiltPixBody({
        w: 800,
        h: 600,
        ink: SET_C.ink,
        pool,
        scale: 1,
        seed: 42,
        clear: clearRectFor('panel', 800, 600, false),
      })
      )
    ).toBe(normalizeCoords(labFixtures.panel));
  });

  it('footer strip: Set R, 1000×700, seed 7, mobile 0.6 scale', () => {
    const pool = quiltAccentPool(SET_R.surface, SET_R.ink, POOL_CANDIDATES);
    expect(
      normalizeCoords(quiltPixBody({
        w: 1000,
        h: 700,
        ink: SET_R.ink,
        pool,
        scale: 0.6,
        seed: 7,
        clear: clearRectFor('footer', 1000, 700, false),
      })
      )
    ).toBe(normalizeCoords(labFixtures.footer));
  });

  it('camo classic, open field: Set C, 800×600, seed 7', () => {
    const pool = quiltAccentPool(SET_C.surface, SET_C.ink, POOL_CANDIDATES);
    expect(
      normalizeCoords(camoBody('camo', {
        w: 800,
        h: 600,
        ink: SET_C.ink,
        pool,
        scale: 1,
        seed: 7,
        clear: null,
      })
      )
    ).toBe(normalizeCoords(labFixtures.camoOpen));
  });

  it('camo classic with the panel clearing: Set C, seed 42', () => {
    const pool = quiltAccentPool(SET_C.surface, SET_C.ink, POOL_CANDIDATES);
    expect(
      normalizeCoords(camoBody('camo', {
        w: 800,
        h: 600,
        ink: SET_C.ink,
        pool,
        scale: 1,
        seed: 42,
        clear: clearRectFor('panel', 800, 600, false),
      })
      )
    ).toBe(normalizeCoords(labFixtures.camoPanel));
  });

  it('camo giant with the footer strip: Set R, seed 99, mobile scale', () => {
    const pool = quiltAccentPool(SET_R.surface, SET_R.ink, POOL_CANDIDATES);
    expect(
      normalizeCoords(camoBody('camo-giant', {
        w: 1000,
        h: 700,
        ink: SET_R.ink,
        pool,
        scale: 0.6,
        seed: 99,
        clear: clearRectFor('footer', 1000, 700, false),
      })
      )
    ).toBe(normalizeCoords(labFixtures.camoGiantFooter));
  });
});

describe('clearRectFor', () => {
  it('footer clears everything above the fixed 112px strip', () => {
    expect(clearRectFor('footer', 1000, 700, false)).toEqual({
      x: -1,
      y: -1,
      w: 1002,
      h: 700 - FOOTER_BAND_PX + 1,
      r: 0,
    });
  });

  it('panel: lab construction (760 cap, r=28), centred at 50%, 560 cap', () => {
    expect(clearRectFor('panel', 800, 600, false)).toEqual({
      x: 48,
      y: 300 - 234,
      w: 704,
      h: 468, // 78% of 600 — under the 560 cap
      r: 28,
    });
    // The cap engages on tall screens, where 78% would overshoot.
    expect(clearRectFor('panel', 1200, 900, false).h).toBe(560);
  });

  it('mobile panel: 74% with the same 560 cap, centred at 50%', () => {
    const c = clearRectFor('panel', 390, 800, true);
    expect(c.h).toBe(Math.min(560, 800 * 0.74));
    expect(c.y).toBe(400 - c.h / 2);
  });
});

describe('determinism', () => {
  it('mulberry32 is stable for a given seed', () => {
    const a = mulberry32(7);
    const b = mulberry32(7);
    expect([a(), a(), a()]).toEqual([b(), b(), b()]);
  });

  it('the same options render the same pattern (resize contract: one seed, one scatter)', () => {
    const pool = quiltAccentPool(SET_C.surface, SET_C.ink, POOL_CANDIDATES);
    const opts = {
      w: 400,
      h: 300,
      ink: SET_C.ink,
      pool,
      scale: 1,
      seed: 12345,
      clear: null,
    };
    expect(quiltPixBody(opts)).toBe(quiltPixBody(opts));
  });
});
