import { describe, expect, it } from 'vitest';
import {
  CURSOR_W,
  FOCUS_GAP,
  FOCUS_W,
  focusR,
  gemClip,
  pixelPts,
  ringBand,
  sheetLeftClip,
  sheetLeftPts,
  spriteClip,
  spritePts,
} from './pixel';
import labFixtures from './__fixtures__/pixel-lab.json';

/**
 * Byte-parity with the pattern lab. The fixtures were generated by running
 * the lab's own generator functions (docs/pattern-lab.html) in Node — the
 * TS port must emit identical strings, or the app's silhouettes silently
 * drift from every judgement made in the lab.
 */
describe('lab parity', () => {
  it('sprite pill clip, R=24 (list options)', () => {
    expect(spriteClip(0, 24)).toBe(labFixtures.s24_0);
  });

  it('sprite pill clip inset by a 4px ring (footprint rule)', () => {
    expect(spriteClip(4, 24)).toBe(labFixtures.s24_4);
  });

  it('sprite chip clip, R=12 (grid cells, guide button)', () => {
    expect(spriteClip(0, 12)).toBe(labFixtures.s12_0);
  });

  it('sprite chip clip, R=8 (keycaps, notation chips, close chip)', () => {
    expect(spriteClip(0, 8)).toBe(labFixtures.s8_0);
  });

  it('sprite caps, R=4 on the 2px grid (mobile progress bar)', () => {
    expect(spriteClip(0, 4, 2)).toBe(labFixtures.s4_2);
  });

  it('focus-band silhouette, R=28 (24 + 4px stand-off)', () => {
    expect(spriteClip(0, 28)).toBe(labFixtures.s28_0);
  });

  it('pixel silhouette at pu=8', () => {
    expect(`polygon(${pixelPts(0, 8).join(', ')})`).toBe(labFixtures.p8_0);
  });

  it('gem silhouette (pixel corners at pu=4)', () => {
    expect(gemClip()).toBe(labFixtures.p4_0);
  });

  it('4px selection band on the R=24 sprite', () => {
    expect(ringBand('sprite', 4, 24)).toBe(labFixtures.band_sprite_4_24);
  });

  it('2px focus band on the R=28 stand-off silhouette', () => {
    expect(ringBand('sprite', 2, 28)).toBe(labFixtures.band_sprite_2_28);
  });

  it('2px cursor band on the R=12 grid cell', () => {
    expect(ringBand('sprite', 2, 12)).toBe(labFixtures.band_sprite_2_12);
  });

  it('pixel-mode band', () => {
    expect(ringBand('pixel', 4, 24, 8)).toBe(labFixtures.band_pixel_4_8);
  });
});

describe('geometry', () => {
  it('R=24/u=4 corner has the documented [16, 8, 4, 4, 0, 0] profile', () => {
    // The profile shows up as the distinct x-insets of the top-left stair
    // points before the mirror takes over.
    const pts = spritePts(0, 24, 4);
    const leading = pts.slice(0, 8).map((p) => parseInt(p, 10));
    expect(leading).toEqual([0, 0, 4, 4, 8, 8, 16, 16]);
  });

  it('emits points starting and ending on the left edge (ringBand contract)', () => {
    const pts = spritePts(0, 24, 4);
    expect(pts[0]).toBe('0px 24px');
    expect(pts[pts.length - 1]).toBe('0px calc(100% - 24px)');
  });

  it('band splices its hole at 50% on the left edge, evenodd', () => {
    const band = ringBand('sprite', 4, 24);
    expect(band.startsWith('polygon(evenodd, 0px 50%')).toBe(true);
    // outer closes at 0px 50%, inner opens at wpx 50% and closes there too
    expect(band).toContain('0px 50%, 4px 50%');
    expect(band.endsWith('4px 50%)')).toBe(true);
  });

  it('inset shifts every literal coordinate by exactly the ring width', () => {
    const outer = spritePts(0, 24, 4);
    const inner = spritePts(4, 24, 4);
    expect(inner.length).toBe(outer.length);
    // First point moves from (0, 24) to (4, 28): both axes gain the inset.
    expect(inner[0]).toBe('4px 28px');
  });

  it('focus band stands off by gap + width and grows its radius to match', () => {
    expect(FOCUS_W).toBe(2);
    expect(FOCUS_GAP).toBe(2);
    expect(focusR(24)).toBe(28);
    expect(focusR(12)).toBe(16);
  });

  it('cursor mark is full-width 2px (the 45% tint failed WCAG 1.4.11)', () => {
    expect(CURSOR_W).toBe(2);
  });
});

describe('sheetLeftPts — the reference sheet silhouette', () => {
  it('steps the left corners exactly like the R=12 sprite, squares the right', () => {
    // R=12/u=4 profile is [4, 0, 0] — one stair per corner.
    expect(sheetLeftClip(0, 12)).toBe(
      'polygon(0px 12px, 0px 4px, 4px 4px, 4px 0%, 100% 0%, 100% 100%, ' +
        '4px 100%, 4px calc(100% - 4px), 0px calc(100% - 4px), ' +
        '0px calc(100% - 12px))'
    );
  });

  it('leftInset shifts only the left edge — the 2px rule mechanism', () => {
    const outer = sheetLeftPts(0, 12);
    const inner = sheetLeftPts(2, 12);
    expect(inner.length).toBe(outer.length);
    // Left-edge x moves by the inset; the square right corners do not.
    expect(inner[0]).toBe('2px 12px');
    expect(inner).toContain('100% 0%');
    expect(inner).toContain('100% 100%');
  });

  it('left-corner stair x/y pairs match the full sprite silhouette', () => {
    // The sheet's top-left corner must be indistinguishable from
    // spriteClip(0, 12)'s — same grammar, fewer corners.
    const sprite = spritePts(0, 12);
    const sheet = sheetLeftPts(0, 12);
    expect(sheet.slice(0, 3)).toEqual(sprite.slice(0, 3));
  });
});
