import { describe, expect, it } from 'vitest';
import {
  stimulationOf,
  temperatureOf,
  duruIntensity,
  suggestPartners,
  labL,
  contrastRatio,
  oklchChroma,
  FLOORS,
} from './stimulation';
import { perceptualDist } from './patterns';

/**
 * These pin the port against the numbers `docs/color-system.md` records under
 * "The recovered stimulation setting" — the scores measured in the lab's
 * Colour studio for the two sets Malik generated by hand with ColorMoods in
 * 2024. Those two scores are what recovered the ≈0.54 target every later set
 * was generated against, so if this file drifts, the blog post's claim and
 * the palette's provenance both stop being true.
 */
describe('the recovered stimulation setting', () => {
  it('scores Set C at the documented 0.551', () => {
    const { score } = stimulationOf('#E7F099', '#02302C');
    expect(score).toBeCloseTo(0.551, 2);
  });

  it('scores Set J at the documented 0.540', () => {
    const { score } = stimulationOf('#E6ACF4', '#1C3601');
    expect(score).toBeCloseTo(0.54, 2);
  });

  it('scores Set L at the 0.583 the colour handoff records', () => {
    const { score } = stimulationOf('#CFF6DD', '#3F0167');
    expect(score).toBeCloseTo(0.583, 2);
  });

  it('puts every shipped set inside the 0.45–0.58 study band', () => {
    const sets: [string, string, string][] = [
      ['A', '#FFABC6', '#4A1040'],
      ['C', '#E7F099', '#02302C'],
      ['J', '#E6ACF4', '#1C3601'],
      ['L', '#CFF6DD', '#3F0167'],
      ['N', '#9EDAFF', '#4A1040'],
      ['Q', '#D9CCF9', '#3E1060'],
      ['R', '#E4BDF7', '#751100'],
    ];
    for (const [name, surface, ink] of sets) {
      const { score } = stimulationOf(surface, ink);
      expect(score, `Set ${name} scored ${score.toFixed(3)}`).toBeGreaterThan(
        0.44
      );
      expect(score, `Set ${name} scored ${score.toFixed(3)}`).toBeLessThan(0.59);
    }
  });

  it('keeps vibration at zero on every shipped pair — the big ΔL is the insurance', () => {
    const pairs: [string, string][] = [
      ['#FFABC6', '#4A1040'],
      ['#E7F099', '#02302C'],
      ['#CFF6DD', '#3F0167'],
      ['#9EDAFF', '#4A1040'],
    ];
    for (const [surface, ink] of pairs) {
      expect(stimulationOf(surface, ink).vibr).toBe(0);
    }
  });
});

describe('what the score does not catch', () => {
  /**
   * docs/color-system.md records a pair that scored 0.578 with vibration 0 —
   * comfortably inside the band, no warning in the instrument — and was
   * rejected anyway for crossing the warm/cool divide. The point this pins is
   * the general one: the score is computed from intensity, lightness and hue
   * distance, and NONE of those terms knows anything about temperature. Two
   * pairs can score identically with opposite temperature behaviour.
   *
   * Deliberately not asserting the historical pair's own numbers: the exact
   * navy isn't recorded, and a test that reconstructs a hex to hit a
   * remembered score is testing the reconstruction, not the model.
   */
  it('scores a warm-plus-cool pair inside the band with no vibration warning', () => {
    const { score, vibr } = stimulationOf('#FFA759', '#1B2A6B');
    expect(score).toBeGreaterThan(0.45);
    expect(score).toBeLessThan(0.62);
    expect(vibr).toBe(0);
    expect(temperatureOf('#FFA759')).toBe('warm');
    expect(temperatureOf('#1B2A6B')).toBe('cool');
  });
});

describe('intensity is not saturation', () => {
  it('rates a mid-value orange above a fully saturated navy', () => {
    expect(duruIntensity('#F8830B')).toBeGreaterThan(duruIntensity('#0A1A6B'));
  });
});

describe('suggestPartners', () => {
  const inks = suggestPartners('#CFF6DD', 0.54, 'ink', perceptualDist);
  const surfaces = suggestPartners('#3F0167', 0.54, 'surface', perceptualDist);

  it('returns candidates that land near the target and never buzz', () => {
    expect(inks.length).toBeGreaterThan(3);
    for (const s of inks) {
      expect(Math.abs(s.score - 0.54)).toBeLessThan(0.06);
      expect(s.vibr).toBeLessThanOrEqual(0.25);
    }
  });

  /**
   * The bug this pins: the first version optimised stimulation alone and
   * happily returned a near-white surface under a bright green ink — ΔL 0.07,
   * 1.21:1, unreadable. Stimulation is a taste metric and says nothing about
   * legibility, so the floors are checked BEFORE the score is consulted.
   */
  it('never proposes a pair that fails AA or collapses the lightness gap', () => {
    for (const s of [...inks, ...surfaces]) {
      expect(s.contrast).toBeGreaterThanOrEqual(FLOORS.contrast);
      expect(s.dL).toBeGreaterThanOrEqual(FLOORS.dL);
    }
  });

  it('clears the contrast the shipped sets actually hold, not just AA', () => {
    // Every shipped pair measures 7.0:1 or better; suggestions should be in
    // that company rather than scraping the legal minimum.
    for (const s of [...inks, ...surfaces]) {
      expect(s.contrast).toBeGreaterThan(6);
    }
  });

  /**
   * A pastel is a saturated hue pushed light, not a desaturated one — the
   * shipped surfaces run OKLCH chroma 0.05–0.12. Sweeping low HSL saturation
   * produced greys, which is the opposite of the house style.
   */
  it('keeps suggested surfaces in the pastel band', () => {
    for (const s of surfaces) {
      expect(oklchChroma(s.hex)).toBeLessThanOrEqual(0.14);
      expect(labL(s.hex)).toBeGreaterThan(70);
    }
  });

  it('keeps suggested inks dark and chromatic rather than near-black', () => {
    for (const s of inks) {
      expect(labL(s.hex)).toBeLessThan(45);
      expect(oklchChroma(s.hex)).toBeGreaterThan(0.02);
    }
  });

  it('never proposes a surface darker than an ink', () => {
    const darkestSurface = Math.min(...surfaces.map((s) => labL(s.hex)));
    const lightestInk = Math.max(...inks.map((s) => labL(s.hex)));
    expect(darkestSurface).toBeGreaterThan(lightestInk);
  });

  it('dedupes perceptually, so the list is not one colour eight times', () => {
    for (let i = 0; i < inks.length; i++) {
      for (let j = i + 1; j < inks.length; j++) {
        expect(perceptualDist(inks[i]!.hex, inks[j]!.hex)).toBeGreaterThan(0.09);
      }
    }
  });

  it('agrees with contrastRatio on the shipped Set L pair', () => {
    expect(contrastRatio('#CFF6DD', '#3F0167')).toBeCloseTo(12.67, 1);
  });
});
