/**
 * Renders the social identity — the two covers and the avatar — from the
 * app's OWN pattern engine.
 *
 *   pnpm brand:assets            # the decided set
 *   pnpm brand:assets --all      # every scheme, for judging
 *
 * WHY IT IMPORTS lib/patterns.ts DIRECTLY. `docs/brand-lab.html` carries a
 * hand-port of the same generator so it can run over file:// with no build
 * step, and a hand-port is a copy that can drift. This script has no such
 * excuse — Node strips the types and imports the shipped module, so the
 * exported artwork is generated by the very code the quiz screens run. If
 * an asset here ever disagrees with the lab, the LAB is what's wrong.
 *
 * Two things the lab has that the shipped generator does not, both applied
 * here in the same terms:
 *   1. the accent RATE dial — lab-only tuning; assets ship at the app's
 *      hard-coded 0.28, so nothing here needs it;
 *   2. the centred lattice — a cover-only transform (see `latticeOffset`).
 */

import fs from 'node:fs/promises';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import {
  patternBody,
  perceptualDist,
  quiltAccentPool,
} from '../lib/patterns.ts';

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const OUT = path.join(ROOT, 'docs/brand');
const MARK = path.join(ROOT, 'public/logicola-wordmark.svg');

/* ---- the palette (docs/brand-decisions.md) ------------------------------ */

const BRAND = { cream: '#EDEDE3', green: '#05A24B' };

/**
 * The five shipped accents — every one a colour the app paints today.
 * Reasoned in docs/brand-decisions.md § Colour; note in particular that
 * this deliberately does NOT reach for the old cover's chord, which is the
 * palette being retired.
 */
const ACCENTS = ['#674900', '#BD00AD', '#8D0381', '#745400', '#824616'];

/**
 * Cell pitch multiplier. 1.53 by eye (Malik, 2026-08-12) — the quilt at
 * 1.0 read as a mosaic at cover size rather than as a pattern. LinkedIn's
 * 191px strip takes 0.6 of that, or its cells are so tall the cover is two
 * rows of half-cropped shapes.
 */
const SCALE = 1.53;

/**
 * Accent probability. NOT the share you get: cells whose left or upper
 * neighbour is already an accent are rejected, so 0.28 measures ~21% of
 * the artwork and the rule's own ceiling is ~52%.
 */
const RATE = 0.28;

/** Which pool the decided set uses. */
const POOL = 'accents';

const SETS = {
  A: { surface: '#FFABC6', ink: '#4A1040', accent: '#674900' },
  C: { surface: '#E7F099', ink: '#02302C', accent: '#BD00AD' },
  J: { surface: '#E6ACF4', ink: '#1C3601', accent: '#674900' },
  L: { surface: '#CFF6DD', ink: '#3F0167', accent: '#BD00AD' },
  N: { surface: '#9EDAFF', ink: '#4A1040', accent: '#8D0381' },
  Q: { surface: '#D9CCF9', ink: '#3E1060', accent: '#745400' },
  R: { surface: '#E4BDF7', ink: '#751100', accent: '#824616' },
};

/** The six shipped inks. */
const INKS = ['#4A1040', '#02302C', '#1C3601', '#3F0167', '#3E1060', '#751100'];

/** Everything the product owns — the widest pool that clears the gate. */
const EVERYTHING = [
  ...Object.values(SETS).flatMap((v) => [v.surface, v.ink, v.accent]),
  '#FA6C5B',
  BRAND.green,
];

/** The seven set surfaces — the colours a student knows each set by. */
const SURFACES = Object.values(SETS).map((v) => v.surface);

const POOLS = {
  accents: ACCENTS,
  inks: INKS,
  everything: EVERYTHING,
  sets: SURFACES,
  setsMix: [...SURFACES, ...INKS],
  duoPlum: ['#4A1040'],
  duoLilac: ['#E6ACF4'],
};

/**
 * Pools whose members skip the GROUND gate.
 *
 * `quiltAccentPool` rejects anything within 0.17 of the ground, so a
 * pattern cannot muddy a surface a student reads against for twenty
 * minutes. Six of seven set surfaces fail it on cream for that reason.
 * A cover carries no text, and the 2024 cover is the proof: its cream
 * tiles sat on a near-white ground and read fine, because a quilt tile is
 * a shape with an edge and a gap around it. These pools keep the INK gate
 * — a tile the colour of the dominant really does vanish — and drop the
 * other one.
 */
const UNGATED = new Set(['sets', 'setsMix']);

const SCHEMES = {
  brand: { ground: BRAND.cream, ink: BRAND.green },
  setL: { ground: '#CFF6DD', ink: '#3F0167' },
  brandInk: { ground: BRAND.cream, ink: '#02302C' },
  brandMint: { ground: '#CFF6DD', ink: BRAND.green },
  // Gensler's own help-page ground and link colour, from the 2008 binary.
  brandOriginal: { ground: '#BBFFFF', ink: '#000077' },
  ...Object.fromEntries(
    Object.entries(SETS).map(([k, v]) => [
      'set' + k,
      { ground: v.surface, ink: v.ink },
    ])
  ),
};

/* ---- the canvases — measured off live pages ----------------------------- */

const CANVASES = [
  { id: 'x-header', w: 1500, h: 500, scale: SCALE, kind: 'cover' },
  { id: 'linkedin-cover', w: 1128, h: 191, scale: SCALE * 0.6, kind: 'cover' },
  { id: 'avatar', w: 400, h: 400, scale: SCALE, kind: 'mark' },
];

/* ---- the mark ----------------------------------------------------------- */

/**
 * The wordmark, read from `public/logicola-wordmark.svg` — the canonical
 * vector, which the repo had been missing entirely (the only marks on disk
 * were a 32px GIF, a raster PWA icon and a favicon can that is a
 * different object).
 *
 * Roles, not literals: `body` is the can, `knock` the lettering cut out
 * of it (it is a can, not a cartridge — see docs/brand-decisions.md). DOCUMENT ORDER IS LOAD-BEARING — the counters inside the
 * letters are body-coloured paths painted back over the knockout, so
 * sorting these by fill would fill in every 'o' and 'a'.
 *
 * This reads the SVG rather than scraping the lab's inline copy: the first
 * version did scrape it, and the very next `prettier --write` reformatted
 * the array across lines and broke the parse. Parsing your own source is a
 * standing invitation for the formatter to break the build.
 */
async function loadLogo() {
  const src = await fs.readFile(MARK, 'utf8');
  const paths = [...src.matchAll(/<path\s+d="([^"]+)"\s+fill="([^"]+)"/g)].map(
    (m) => [/^#f/i.test(m[2]) ? 'w' : 'g', m[1]]
  );
  if (paths.length !== 16)
    throw new Error(
      `public/logicola-wordmark.svg parsed to ${paths.length} paths, expected 16`
    );
  return paths;
}
const MARK_W = 265;
const MARK_H = 190;

function markSvg(logo, x, y, height, body, knock) {
  const k = height / MARK_H;
  return (
    `<g transform="translate(${x} ${y}) scale(${k})">` +
    logo
      .map(
        ([role, d]) => `<path d="${d}" fill="${role === 'g' ? body : knock}"/>`
      )
      .join('') +
    '</g>'
  );
}

/* ---- composition -------------------------------------------------------- */

/**
 * Split the lattice's overflow evenly across both edges.
 *
 * The generators lay cells from (0,0) and run one column and row past the
 * canvas, so a card ends with whatever sliver happens to fall at its right
 * edge. On a quiz card nobody notices; on a 1500px cover a 3px orphan
 * column reads as a printing error where a half-cell reads as a crop.
 */
function latticeOffset(w, h, scale) {
  const t = 62 * scale; // quilt cell pitch, from lib/patterns.ts
  const span = (len) => Math.ceil(len / t) * t + t;
  return { ox: -(span(w) - w) / 2, oy: -(span(h) - h) / 2 };
}

function coverSvg(canvas, scheme, poolName = POOL, rate = RATE) {
  const { w, h, scale } = canvas;
  const candidates = POOLS[poolName].filter(
    (c) => c !== scheme.ink && c !== scheme.ground
  );
  const pool = UNGATED.has(poolName)
    ? candidates.filter((c) => perceptualDist(c, scheme.ink) > 0.09)
    : quiltAccentPool(scheme.ground, scheme.ink, candidates);
  const { ox, oy } = latticeOffset(w, h, scale);
  const body = patternBody('quilt', {
    w: w - ox * 2,
    h: h - oy * 2,
    ink: scheme.ink,
    pool,
    scale,
    seed: 7,
    clear: null,
    rate,
  });
  return (
    `<svg xmlns="http://www.w3.org/2000/svg" width="${w}" height="${h}" viewBox="0 0 ${w} ${h}">` +
    `<rect width="${w}" height="${h}" fill="${scheme.ground}"/>` +
    `<g transform="translate(${ox} ${oy})">${body}</g></svg>`
  );
}

function avatarSvg(canvas, scheme, logo) {
  const { w, h } = canvas;
  // 0.50 of the height puts the wordmark at 66% of the width — sized against
  // the INSCRIBED CIRCLE, since both platforms crop the avatar round.
  const mh = h * 0.5;
  const mw = (mh * MARK_W) / MARK_H;
  return (
    `<svg xmlns="http://www.w3.org/2000/svg" width="${w}" height="${h}" viewBox="0 0 ${w} ${h}">` +
    `<rect width="${w}" height="${h}" fill="${scheme.ground}"/>` +
    markSvg(logo, (w - mw) / 2, (h - mh) / 2, mh, scheme.ink, scheme.ground) +
    '</svg>'
  );
}

/* ---- output ------------------------------------------------------------- */

/**
 * SVG is the master; PNG is a convenience. Both failure modes here are
 * environmental (playwright not installed, or installed without its browser
 * binary) and neither should cost you the SVGs — so this reports and
 * returns rather than throwing. The lab's own PNG buttons are the other way
 * to get raster, and they need nothing installed.
 */
async function rasterise(files) {
  let browser;
  try {
    const { chromium } = await import('@playwright/test');
    browser = await chromium.launch();
  } catch (err) {
    const needsBinary = /Executable doesn't exist/.test(err?.message ?? '');
    console.warn(
      needsBinary
        ? '  PNG skipped — run `npx playwright install chromium` for raster,\n' +
            '  or use the PNG buttons in docs/brand-lab.html.'
        : `  PNG skipped — ${err?.message ?? err}`
    );
    return 0;
  }
  let n = 0;
  try {
    const page = await browser.newPage();
    for (const { file, svg, w, h } of files) {
      await page.setViewportSize({ width: w, height: h });
      await page.setContent(
        `<style>html,body{margin:0;padding:0}svg{display:block}</style>${svg}`,
        { waitUntil: 'load' }
      );
      await page.screenshot({
        path: file.replace(/\.svg$/, '.png'),
        clip: { x: 0, y: 0, width: w, height: h },
      });
      n++;
    }
  } finally {
    await browser.close();
  }
  return n;
}

/**
 * The shortlist, for judging at full size. Every one keeps a LIGHT ground:
 * the colour system's light-surface rule is total ("the catalogue has one
 * structure, not two"), and a green-ground variant that read all seven set
 * surfaces was built and cut for breaking it.
 */
const SHORTLIST = [
  // The duotone, at the two ends of the original's own intensity dial.
  ['duo-lilac', 'brand', 'duoLilac', 1.0],
  ['duo-plum', 'brand', 'duoPlum', 1.0],
  // More of the sets, ungated so the pale surfaces survive.
  ['sets-surfaces-75', 'brand', 'sets', 0.75],
  ['sets-full-75', 'brand', 'setsMix', 0.75],
  ['sets-full-100', 'brand', 'setsMix', 1.0],
  // The gated wide pool, for reference.
  ['cream-everything-100', 'brand', 'everything', 1.0],
  // The original's own pair, against the closest set to it.
  ['original-sets-75', 'brandOriginal', 'setsMix', 0.75],
  ['original-surfaces-75', 'brandOriginal', 'sets', 0.75],
  ['setL-sets-75', 'setL', 'setsMix', 0.75],
];

async function compare() {
  const written = [];
  const x = CANVASES.find((c) => c.id === 'x-header');
  for (const [name, scheme, pool, rate] of SHORTLIST) {
    const svg = coverSvg(x, SCHEMES[scheme], pool, rate);
    const file = path.join(OUT, `compare-${name}.svg`);
    await fs.writeFile(file, svg);
    written.push({ file, svg, w: x.w, h: x.h });
  }
  return written;
}

async function main() {
  const all = process.argv.includes('--all');
  if (process.argv.includes('--compare')) {
    // Covers only — the shortlist is a colour question, and the avatar is
    // the same file in every one of them.
    await fs.mkdir(OUT, { recursive: true });
    const written = await compare();
    const pngs = await rasterise(written);
    console.log(`Wrote ${written.length} SVG + ${pngs} PNG comparison covers`);
    return;
  }
  const logo = await loadLogo();
  await fs.mkdir(OUT, { recursive: true });

  const schemes = all ? Object.keys(SCHEMES) : ['brand'];
  const written = [];

  for (const name of schemes) {
    const scheme = SCHEMES[name];
    for (const canvas of CANVASES) {
      const svg =
        canvas.kind === 'mark'
          ? avatarSvg(canvas, scheme, logo)
          : coverSvg(canvas, scheme);
      const stem = name === 'brand' ? canvas.id : `${canvas.id}-${name}`;
      const file = path.join(OUT, `logicola-${stem}.svg`);
      await fs.writeFile(file, svg);
      written.push({ file, svg, w: canvas.w, h: canvas.h });
    }
  }

  const pngs = await rasterise(written);
  console.log(
    `Wrote ${written.length} SVG + ${pngs} PNG to docs/brand/ ` +
      `(${schemes.length} scheme${schemes.length > 1 ? 's' : ''})`
  );
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
