import { Set } from '../types';
import { feedback_single_person } from '../constants';

const setA: Set = {
  name: 'Set A',
  logicType: 'Syllogistic',
  slugs: ['syllogistic', 'translations'],
  id: 1,
  title: 'Syllogistic Translations: Easy',
  header: 'Translates into logic as:',
  subSets: [
    {
      name: 'Set A',
      logicType: 'Basic Translations',
      shuffleOptions: true,
      slugs: ['syllogistic', 'translations', 'basic'],
      id: 1,
      title: 'Syllogistic Translations: Easy',
      header: 'Translates into logic as:',
      questions: [
        {
          id: '1.1',
          prompt: "You aren't the cleanest biologist.",
          options: [
            { id: 0, label: 'u is not B' },
            { id: 1, label: 'U is not b' },
            { id: 2, label: 'U is not B' },
            { id: 3, label: 'u is not b' },
          ],
          correctId: [3],
          answer: '',
        },
        {
          id: '1.2',
          prompt: "You aren't a short convict.",
          options: [
            { id: 0, label: 'u is not c' },
            { id: 1, label: 'U is not c' },
            { id: 2, label: 'u is not C' },
            { id: 3, label: 'U is not C' },
          ],
          correctId: [2],
          answer:
            '"A short convict" could describe many persons, and so translates into a capital letter.',
        },
        {
          id: '1.3',
          prompt: "The dancer isn't the most cheerful person.",
          options: [
            { id: 0, label: 'D is not C' },
            { id: 1, label: 'D is not c' },
            { id: 2, label: 'd is not C' },
            { id: 3, label: 'd is not c' },
          ],
          correctId: [3],
          answer: '',
        },
        {
          id: '1.4',
          prompt: 'All soldiers in Berlin forgive people who are remarkable.',
          options: [
            { id: 0, label: 'S is F' },
            { id: 1, label: 'all S is F' },
            { id: 2, label: 'all s is F' },
            { id: 3, label: 'all F is S' },
          ],
          correctId: [1],
          answer: '',
        },
        {
          id: '1.5',
          prompt: "You aren't the smartest criminal.",
          options: [
            { id: 0, label: 'u is not C' },
            { id: 1, label: 'U is not C' },
            { id: 2, label: 'U is not c' },
            { id: 3, label: 'u is not c' },
          ],
          correctId: [3],
          answer: '',
        },
        {
          id: '1.6',
          prompt: "You aren't a slow druggist.",
          options: [
            { id: 0, label: 'U is not d' },
            { id: 1, label: 'u is not D' },
            { id: 2, label: 'U is not D' },
            { id: 3, label: 'u is not d' },
          ],
          correctId: [1],
          answer: '',
        },
        {
          id: '1.7',
          prompt: "I'm the cheapest poet in Paris.",
          options: [
            { id: 0, label: 'I is P' },
            { id: 1, label: 'i is P' },
            { id: 2, label: 'I is p' },
            { id: 3, label: 'i is p' },
          ],
          correctId: [3],
          answer: `"The cheapest poet" ${feedback_single_person}`,
        },
        {
          id: '1.8',
          prompt: 'All detectives in London hate people who are frantic.',
          options: [
            { id: 0, label: 'all H is D' },
            { id: 1, label: 'all D is H' },
            { id: 2, label: 'all d is H' },
            { id: 3, label: 'D is H' },
          ],
          correctId: [1],
          answer: '',
        },
        {
          id: '1.9',
          prompt: "You aren't the wildest plumber.",
          options: [
            { id: 0, label: 'u is not P' },
            { id: 1, label: 'u is not p' },
            { id: 2, label: 'U is not P' },
            { id: 3, label: 'U is not p' },
          ],
          correctId: [1],
          answer: `"The wildest plumber" ${feedback_single_person}`,
        },
        {
          id: '1.10',
          prompt: "You aren't a short customer.",
          options: [
            { id: 0, label: 'U is not c' },
            { id: 1, label: 'U is not C' },
            { id: 2, label: 'u is not c' },
            { id: 3, label: 'u is not C' },
          ],
          correctId: [3],
          answer: '',
        },
        {
          id: '1.11',
          prompt: "I'm the boldest guitarist in New York.",
          options: [
            { id: 0, label: 'I is G' },
            { id: 1, label: 'i is g' },
            { id: 2, label: 'i is G' },
            { id: 3, label: 'I is g' },
          ],
          correctId: [1],
          answer: '',
        },
        {
          id: '1.12',
          prompt: 'All judges in Madrid appreciate people who are tactful.',
          options: [
            { id: 0, label: 'J is A' },
            { id: 1, label: 'all J is A' },
            { id: 2, label: 'all A is J' },
            { id: 3, label: 'all j is A' },
          ],
          correctId: [1],
          answer: '',
        },
        {
          id: '1.13',
          prompt: "You aren't the slowest dentist.",
          options: [
            { id: 0, label: 'U is not d' },
            { id: 1, label: 'u is not d' },
            { id: 2, label: 'u is not D' },
            { id: 3, label: 'U is not D' },
          ],
          correctId: [1],
          answer: '',
        },
        {
          id: '1.14',
          prompt: "Some prisoners don't blame any frivolous people.",
          options: [
            { id: 0, label: 'P is not B' },
            { id: 1, label: 'some P is B' },
            { id: 2, label: 'some P is not B' },
            { id: 3, label: 'some p is not B' },
          ],
          correctId: [2],
          answer: '',
        },
        {
          id: '1.15',
          prompt: "I'm the cleanest musician in Moscow.",
          options: [
            { id: 0, label: 'I is M' },
            { id: 1, label: 'i is M' },
            { id: 2, label: 'I is m' },
            { id: 3, label: 'i is m' },
          ],
          correctId: [3],
          answer: '',
        },
        {
          id: '1.16',
          prompt:
            'All pessimists in Detroit encourage people who are dishonest.',
          options: [
            { id: 0, label: 'P is E' },
            { id: 1, label: 'all E is P' },
            { id: 2, label: 'all P is E' },
            { id: 3, label: 'all p is E' },
          ],
          correctId: [2],
          answer: '',
        },
        {
          id: '1.17',
          prompt: "You aren't the meanest politician.",
          options: [
            { id: 0, label: 'U is not P' },
            { id: 1, label: 'U is not p' },
            { id: 2, label: 'u is not p' },
            { id: 3, label: 'u is not P' },
          ],
          correctId: [2],
          answer: `"The meanest politician" ${feedback_single_person}`,
        },
        {
          id: '1.18',
          prompt: "Some republicans don't hate any filthy people.",
          options: [
            { id: 0, label: 'some R is H' },
            { id: 1, label: 'some R is not H' },
            { id: 2, label: 'R is not H' },
            { id: 3, label: 'some r is not H' },
          ],
          correctId: [1],
          answer: '',
        },
        /* {
                id: '1.19',
                prompt: "I'm the smartest doctor in Chicago.",
                options: [
                  { id: 0, label: 'some R is H' },
                  { id: 1, label: 'some R is not H' },
                  { id: 2, label: 'R is not H' },
                  { id: 3, label: 'some r is not H' },
                ],
                correctId: [0],
                answer: `"The smartest doctor" ${feedback_single_person}`,
              }, */
        {
          id: '1.20',
          prompt: 'All pickpockets in Rome hurt people who are fortunate.',
          options: [
            { id: 0, label: 'all H is P' },
            { id: 1, label: 'All P is H' },
            { id: 2, label: 'P is H' },
            { id: 3, label: 'all p is H' },
          ],
          correctId: [1],
          answer: '',
        },
        {
          id: '1.21',
          prompt: "You aren't the strongest banker.",
          options: [
            { id: 0, label: 'U is not b' },
            { id: 1, label: 'u is not b' },
            { id: 2, label: 'U is not B' },
            { id: 3, label: 'u is not B' },
          ],
          correctId: [1],
          answer: `"The strongest banker" ${feedback_single_person}`,
        },
        {
          id: '1.22',
          prompt: "Some Germans don't blame any miserable people.",
          options: [
            { id: 0, label: 'some G is B' },
            { id: 1, label: 'some g is not B' },
            { id: 2, label: 'some G is not B' },
            { id: 3, label: 'G is not B' },
          ],
          correctId: [2],
          answer: '',
        },
        {
          id: '1.23',
          prompt: "I'm the cruelest bachelor in Santa Monica.",
          options: [
            { id: 0, label: 'I is b' },
            { id: 1, label: 'i is B' },
            { id: 2, label: 'i is b' },
            { id: 3, label: 'I is B' },
          ],
          correctId: [2],
          answer: `"The cruelest bachelor" ${feedback_single_person}`,
        },
        {
          id: '1.24',
          prompt: 'All carpenters in Virginia bother people who are dangerous.',
          options: [
            { id: 0, label: 'all c is B' },
            { id: 1, label: 'all B is C' },
            { id: 2, label: 'all C is B' },
            { id: 3, label: 'C is B' },
          ],
          correctId: [2],
          answer: '',
        },
        {
          id: '1.25',
          prompt: "You aren't the brightest convict.",
          options: [
            { id: 0, label: 'u is not C' },
            { id: 1, label: 'u is not c' },
            { id: 2, label: 'U is not C' },
            { id: 3, label: 'U is not c' },
          ],
          correctId: [2],
          answer: `"The brightest" ${feedback_single_person}`,
        },
        {
          id: '1.25',
          prompt: 'Some vicious criminals are boring.',
          options: [
            { id: 0, label: 'C is b' },
            { id: 1, label: 'some C is B' },
            { id: 2, label: 'some C is b' },
            { id: 3, label: 'C is B' },
          ],
          correctId: [2],
          answer: '',
        },
        {
          id: '1.26',
          prompt: "I'm the slowest diabetic in Boston.",
          options: [
            { id: 0, label: 'I is d' },
            { id: 1, label: 'I is D' },
            { id: 2, label: 'i is d' },
            { id: 3, label: 'i is D' },
          ],
          correctId: [2],
          answer: `"The slowest diabetic" ${feedback_single_person}`,
        },
        {
          id: '1.27',
          prompt:
            'All backpackers in Mexico City know people who are prosperous.',
          options: [
            { id: 0, label: 'B is K' },
            { id: 1, label: 'all b is K' },
            { id: 2, label: 'all B is K' },
            { id: 3, label: 'all K is B' },
          ],
          correctId: [2],
          answer: ``,
        },
        {
          id: '1.28',
          prompt: "You aren't the tallest cannibal.",
          options: [
            { id: 0, label: 'u is not C' },
            { id: 1, label: 'u is not c' },
            { id: 2, label: 'U is not C' },
            { id: 3, label: 'U is not c' },
          ],
          correctId: [1],
          answer: ``,
        },
        {
          id: '1.29',
          prompt: 'Some notorious fugitives are dishonest.',
          options: [
            { id: 0, label: 'F is D' },
            { id: 1, label: 'F is d' },
            { id: 2, label: 'some F is D' },
            { id: 3, label: 'some F is d' },
          ],
          correctId: [2],
          answer: ``,
        },
        {
          id: '1.30',
          prompt: "I'm the meanest bandit in Bratislava.",
          options: [
            { id: 0, label: 'i is B' },
            { id: 1, label: 'I is B' },
            { id: 2, label: 'I is b' },
            { id: 3, label: 'i is b' },
          ],
          correctId: [3],
          answer: `"The meanest bandit" ${feedback_single_person}`,
        },
        {
          id: '1.31',
          prompt: "This terrorist isn't a candid person.",
          options: [
            { id: 0, label: 't is not C' },
            { id: 1, label: 'T is not c' },
            { id: 2, label: 'T is not C' },
            { id: 3, label: 't is not c' },
          ],
          correctId: [0],
          answer: ``,
        },
        {
          id: '1.32',
          prompt: "I'm the smartest biologist in Kiev.",
          options: [
            { id: 0, label: 'I is b' },
            { id: 1, label: 'I is B' },
            { id: 2, label: 'i is b' },
            { id: 3, label: 'i is B' },
          ],
          correctId: [2],
          answer: ``,
        },
        {
          id: '1.33',
          prompt: 'Some miserable convicts are gloomy.',
          options: [
            { id: 0, label: 'C is G' },
            { id: 1, label: 'some C is G' },
            { id: 2, label: 'some C is g' },
            { id: 3, label: 'C is g' },
          ],
          correctId: [1],
          answer: ``,
        },
        {
          id: '1.34',
          prompt: "You aren't the wildest criminal.",
          options: [
            { id: 0, label: 'u is not c' },
            { id: 1, label: 'u is not C' },
            { id: 2, label: 'U is not C' },
            { id: 3, label: 'u is not c' },
          ],
          correctId: [3],
          answer: ``,
        },
        {
          id: '1.35',
          prompt: 'No dangerous foreigner is poetic',
          options: [
            { id: 0, label: 'all F is not P' },
            { id: 1, label: 'f is not P' },
            { id: 2, label: 'F is not P' },
            { id: 3, label: 'no F is P' },
          ],
          correctId: [3],
          answer: ``,
        },
        {
          id: '1.36',
          prompt: "I'm the shortest diabetic in Berlin.",
          options: [
            { id: 0, label: 'i is d' },
            { id: 1, label: 'I is d' },
            { id: 2, label: 'i is D' },
            { id: 3, label: 'I is D' },
          ],
          correctId: [0],
          answer: ``,
        },
        {
          id: '1.37',
          prompt: 'Some boring druggists are sociable.',
          options: [
            { id: 0, label: 'D is S' },
            { id: 1, label: 'some D is s' },
            { id: 2, label: 'some D is S' },
            { id: 3, label: 'D is s' },
          ],
          correctId: [2],
          answer: ``,
        },
        {
          id: '1.38',
          prompt: "You aren't the brightest farmer.",
          options: [
            { id: 0, label: 'u is not f' },
            { id: 1, label: 'u is not F' },
            { id: 2, label: 'U is not f' },
            { id: 3, label: 'U is not F' },
          ],
          correctId: [0],
          answer: ``,
        },
        {
          id: '1.39',
          prompt: 'No prosperous cannibal is gentle.',
          options: [
            { id: 0, label: 'c is not G' },
            { id: 1, label: 'no C is G' },
            { id: 2, label: 'C is not G' },
            { id: 3, label: 'all C is not G' },
          ],
          correctId: [1],
          answer: ``,
        },
        {
          id: '1.40',
          prompt: 'Adriano is a boastful person in Barcelona.',
          options: [
            { id: 0, label: 'M is B' },
            { id: 1, label: 'm is b' },
            { id: 2, label: 'M is b' },
            { id: 3, label: 'm is B' },
          ],
          correctId: [3],
          answer: ``,
        },
        {
          id: '1.41',
          prompt: 'Some dishonest plumbers are cowardly.',
          options: [
            { id: 0, label: 'some P is c' },
            { id: 1, label: 'P is C' },
            { id: 2, label: 'P is c' },
            { id: 3, label: 'some P is C' },
          ],
          correctId: [3],
          answer: ``,
        },
        {
          id: '1.42',
          prompt: 'All customers in Milan hate people who are famous.',
          options: [
            { id: 0, label: 'all H is C' },
            { id: 1, label: 'all C is H' },
            { id: 2, label: 'all c is H' },
            { id: 3, label: 'C is H' },
          ],
          correctId: [1],
          answer: ``,
        },
        {
          id: '1.43',
          prompt: 'No brilliant clown is greedy.',
          options: [
            { id: 0, label: 'no C is G' },
            { id: 1, label: 'c is not G' },
            { id: 2, label: 'C is not G' },
            { id: 3, label: 'all C is not G' },
          ],
          correctId: [0],
          answer: ``,
        },
        {
          id: '1.44',
          prompt: "I'm the richest judge in Hamburg",
          options: [
            { id: 0, label: 'I is j' },
            { id: 1, label: 'i is J' },
            { id: 2, label: 'I is J' },
            { id: 3, label: 'i is j' },
          ],
          correctId: [3],
          answer: ``,
        },
        {
          id: '1.45',
          prompt: 'Some disgusting prisioners are miserable.',
          options: [
            { id: 0, label: 'some P is m' },
            { id: 1, label: 'P is M' },
            { id: 2, label: 'some P is M' },
            { id: 3, label: 'P is m' },
          ],
          correctId: [2],
          answer: ``,
        },
        {
          id: '1.46',
          prompt: "Some musicians don't hurt any naive people",
          options: [
            { id: 0, label: 'some M is not H' },
            { id: 1, label: 'some M is H' },
            { id: 2, label: 'M is not H' },
            { id: 3, label: 'some m is not H' },
          ],
          correctId: [0],
          answer: ``,
        },
        {
          id: '1.47',
          prompt: 'No demented pessimist is romantic',
          options: [
            { id: 0, label: 'no P is R' },
            { id: 1, label: 'P is not R' },
            { id: 2, label: 'p is not R' },
            { id: 3, label: 'all P is not R' },
          ],
          correctId: [0],
          answer: ``,
        },
        {
          id: '1.48',
          prompt: "I'm the cleanest pharmacist in Dallas",
          options: [
            { id: 0, label: 'i is p' },
            { id: 1, label: 'i is P' },
            { id: 2, label: 'I is p' },
            { id: 3, label: 'I is P' },
          ],
          correctId: [0],
          answer: ``,
        },
        {
          id: '1.49',
          prompt: "You aren't the shortest republican",
          options: [
            { id: 0, label: 'U is not R' },
            { id: 1, label: 'u is not r' },
            { id: 2, label: 'u is not R' },
            { id: 3, label: 'U is not r' },
          ],
          correctId: [1],
          answer: ``,
        },
        {
          id: '1.50',
          prompt: "Some doctors don't appreciate any frivolous people",
          options: [
            { id: 0, label: 'some d is not A' },
            { id: 1, label: 'D is not A' },
            { id: 2, label: 'some D is A' },
            { id: 3, label: 'some D is not A' },
          ],
          correctId: [3],
          answer: ``,
        },
      ],
    },
    {
      name: 'Set A',
      logicType: 'Syllogistic',
      shuffleOptions: true,
      slugs: ['syllogistic', 'translations', 'hard'],
      id: 1,
      isNew: true,
      title: 'Syllogistic Translations: Hard',
      header: 'Translates into logic as:',
      questions: [
        {
          id: '1.1',
          prompt: "People who aren't biologists aren't clean.",
          options: [
            { id: 0, label: 'all B is not C' },
            { id: 1, label: 'B is not C' },
            { id: 2, label: 'some B is not C' },
            { id: 3, label: 'no B is C' },
          ],
          correctId: [3],
          answer: '',
        },
        {
          id: '1.2',
          prompt: 'People who are dancers are wild.',
          options: [
            { id: 0, label: 'W is D' },
            { id: 1, label: 'all D is W' },
            { id: 2, label: 'D is W' },
            { id: 3, label: 'some D is W' },
          ],
          correctId: [1],
          answer: '',
        },
        {
          id: '1.3',
          prompt: "It isn't true that somre foreigners are cruel.",
          options: [
            { id: 0, label: 'no F is C' },
            { id: 1, label: 'all F is C' },
            { id: 2, label: 'some F is not C' },
            { id: 3, label: 'F is not C' },
          ],
          correctId: [0],
          answer: '',
        },
        {
          id: '1.4',
          prompt: "It is false that some druggists aren't confused.",
          options: [
            { id: 0, label: 'not some D is C' },
            { id: 1, label: 'D is C' },
            { id: 2, label: 'all D is C' },
            { id: 3, label: 'some D is C' },
          ],
          correctId: [2],
          answer: '',
        },
        {
          id: '1.5',
          prompt: "People who aren't backpackers aren't rich",
          options: [
            { id: 0, label: 'all B is not R' },
            { id: 1, label: 'B is not R' },
            { id: 2, label: 'no B is R' },
            { id: 3, label: 'some B is not R' },
          ],
          correctId: [2],
          answer: '',
        },
        {
          id: '1.6',
          prompt: 'People who are poets are bright',
          options: [
            { id: 0, label: 'all P is B' },
            { id: 1, label: 'some P is B' },
            { id: 2, label: 'P is B' },
            { id: 3, label: 'B is P' },
          ],
          correctId: [0],
          answer: '',
        },
        {
          id: '1.7',
          prompt: "It isn't true that some detectives are slow",
          options: [
            { id: 0, label: 'D is not S' },
            { id: 1, label: 'not D is S' },
            { id: 2, label: 'all D is S' },
            { id: 3, label: 'some D is not S' },
          ],
          correctId: [2],
          answer: '',
        },
        {
          id: '1.8',
          prompt: "It is false that some bandits aren't disgusting",
          options: [
            { id: 0, label: 'all B is D' },
            { id: 1, label: 'some B is D' },
            { id: 2, label: 'not some B is D' },
            { id: 3, label: 'B is D' },
          ],
          correctId: [0],
          answer: '',
        },
        {
          id: '1.9',
          prompt: "People who are customers aren't dull",
          options: [
            { id: 0, label: 'no C is D' },
            { id: 1, label: 'all C is not D' },
            { id: 2, label: 'C is not D' },
            { id: 3, label: 'some C is not D' },
          ],
          correctId: [0],
          answer: '',
        },
        {
          id: '1.10',
          prompt: 'People who are pilots are rich',
          options: [
            { id: 0, label: 'all P is R' },
            { id: 1, label: 'R is P' },
            { id: 2, label: 'some P is R' },
            { id: 3, label: 'P is R' },
          ],
          correctId: [0],
          answer: '',
        },
        {
          id: '1.11',
          prompt: "It isn't true that some dentists are rough",
          options: [
            { id: 0, label: 'all D is R' },
            { id: 1, label: 'some D is not R' },
            { id: 2, label: 'no D is R' },
            { id: 3, label: 'D is not R' },
          ],
          correctId: [2],
          answer: '',
        },
        {
          id: '1.12',
          prompt: "It is false that some novelists aren't frivolous",
          options: [
            { id: 0, label: 'all N is F' },
            { id: 1, label: 'N is F' },
            { id: 2, label: 'some N is F' },
            { id: 3, label: 'not some N is F' },
          ],
          correctId: [0],
          answer: '',
        },
        {
          id: '1.13',
          prompt: "People who are pharmacists aren't cheap",
          options: [
            { id: 0, label: 'some P is not C' },
            { id: 1, label: 'all P is not C' },
            { id: 2, label: 'P is not C' },
            { id: 3, label: 'no P is C' },
          ],
          correctId: [3],
          answer: '',
        },
        {
          id: '1.14',
          prompt: "A person isn't tall unless he or she is remarkable",
          options: [
            { id: 0, label: 'all T is R' },
            { id: 1, label: 'no T is R' },
            { id: 2, label: 'T is not R' },
            { id: 3, label: 'all R is T' },
          ],
          correctId: [0],
          answer: '',
        },
        {
          id: '1.15',
          prompt: "It isn't true that some senators are wild",
          options: [
            { id: 0, label: 'S is not W' },
            { id: 1, label: 'all S is W' },
            { id: 2, label: 'no S is W' },
            { id: 3, label: 'some S is not W' },
          ],
          correctId: [2],
          answer: '',
        },
        {
          id: '1.16',
          prompt: "It is false that some bankers aren't fanatical",
          options: [
            { id: 0, label: 'some B is F' },
            { id: 1, label: 'all B is F' },
            { id: 2, label: 'not some B is F' },
            { id: 3, label: 'B is F' },
          ],
          correctId: [1],
          answer: '',
        },
        {
          id: '1.17',
          prompt: "People who aren't backpackers aren't rich",
          options: [
            { id: 0, label: 'all D is not S' },
            { id: 1, label: 'D is not S' },
            { id: 2, label: 'some D is not S' },
            { id: 3, label: 'no D is S' },
          ],
          correctId: [3],
          answer: '',
        },
        {
          id: '1.18',
          prompt: "A person isn't mean unless he or she is comical",
          options: [
            { id: 0, label: 'M is not C' },
            { id: 1, label: 'no M is C' },
            { id: 2, label: 'all M is C' },
            { id: 3, label: 'all C is M' },
          ],
          correctId: [2],
          answer: '',
        },
        {
          id: '1.19',
          prompt: "It isn't true that some professors are rich",
          options: [
            { id: 0, label: 'P is not R' },
            { id: 1, label: 'some P is not R' },
            { id: 2, label: 'no P is R' },
            { id: 3, label: 'all P is R' },
          ],
          correctId: [2],
          answer: '',
        },
        {
          id: '1.20',
          prompt: 'No one is rough unless he or she is demented',
          options: [
            { id: 0, label: 'R is not D' },
            { id: 1, label: 'all R is D' },
            { id: 2, label: 'no R is D' },
            { id: 3, label: 'all D is R' },
          ],
          correctId: [1],
          answer: '',
        },
        {
          id: '1.21',
          prompt: "People who soldiers aren't bright",
          options: [
            { id: 0, label: 'all S is not B' },
            { id: 1, label: 'no S is B' },
            { id: 2, label: 'S is not B' },
            { id: 3, label: 'some S is not B' },
          ],
          correctId: [1],
          answer: '',
        },
        {
          id: '1.22',
          prompt: "A person isn't slow unless he or she is charitable",
          options: [
            { id: 0, label: 'all C is S' },
            { id: 1, label: 'all S is C' },
            { id: 2, label: 'no S is C' },
            { id: 3, label: 'S is not C' },
          ],
          correctId: [1],
          answer: '',
        },
        {
          id: '1.23',
          prompt: "It isn't true that some criminals are strong",
          options: [
            { id: 0, label: 'all C is S' },
            { id: 1, label: 'some C is not S' },
            { id: 2, label: 'C is not S' },
            { id: 3, label: 'no C is S' },
          ],
          correctId: [3],
          answer: '',
        },
        {
          id: '1.24',
          prompt: 'No one is wild unless he or she is faithful',
          options: [
            { id: 0, label: 'W is not F' },
            { id: 1, label: 'all W is F' },
            { id: 2, label: 'all F is W' },
            { id: 3, label: 'no W is F' },
          ],
          correctId: [1],
          answer: '',
        },
        {
          id: '1.25',
          prompt: "People who are farmers aren't short",
          options: [
            { id: 0, label: 'no F is S' },
            { id: 1, label: 'F is not S' },
            { id: 2, label: 'all F is not S' },
            { id: 3, label: 'some F is not S' },
          ],
          correctId: [0],
          answer: '',
        },
        {
          id: '1.26',
          prompt: "A person isn't bold unless he or she is mediocre",
          options: [
            { id: 0, label: 'B is not M' },
            { id: 1, label: 'all M is B' },
            { id: 2, label: 'all B is M' },
            { id: 3, label: 'no B is M' },
          ],
          correctId: [2],
          answer: '',
        },
        {
          id: '1.27',
          prompt: "It isn't true that some detectives are tough",
          options: [
            { id: 0, label: 'D is not T' },
            { id: 1, label: 'some D is not T' },
            { id: 2, label: 'all D is T' },
            { id: 3, label: 'no D is T' },
          ],
          correctId: [3],
          answer: '',
        },
        {
          id: '1.28',
          prompt: 'No one is weak unless he or she is naive',
          options: [
            { id: 0, label: 'no W is N' },
            { id: 1, label: 'all N is W' },
            { id: 2, label: 'W is not N' },
            { id: 3, label: 'all W is N' },
          ],
          correctId: [3],
          answer: '',
        },
        {
          id: '1.29',
          prompt: 'Whoever is dangerous is sarcastic',
          options: [
            { id: 0, label: 'D is S' },
            { id: 1, label: 'all S is D' },
            { id: 2, label: 'all D is S' },
            { id: 3, label: 'S is D' },
          ],
          correctId: [2],
          answer: '',
        },
        {
          id: '1.30',
          prompt: "A person isn't cruel unless he or she is talented",
          options: [
            { id: 0, label: 'no C is T' },
            { id: 1, label: 'all C is T' },
            { id: 2, label: 'C is not T' },
            { id: 3, label: 'all T is C' },
          ],
          correctId: [1],
          answer: '',
        },
        {
          id: '1.31',
          prompt: 'No one is wild unless he or she is gentle',
          options: [
            { id: 0, label: 'all G is W' },
            { id: 1, label: 'all W is G' },
            { id: 2, label: 'W is not G' },
            { id: 3, label: 'no W is G' },
          ],
          correctId: [1],
          answer: '',
        },
        {
          id: '1.32',
          prompt: 'One or more dentists are mean',
          options: [
            { id: 0, label: 'M is D' },
            { id: 1, label: 'D is M' },
            { id: 2, label: 'some D is not M' },
            { id: 3, label: 'some D is M' },
          ],
          correctId: [3],
          answer: '',
        },
        {
          id: '1.33',
          prompt: "Whoever is powerful isn't dishonest",
          options: [
            { id: 0, label: 'P is not D' },
            { id: 1, label: 'all D is not P' },
            { id: 2, label: 'no P is D' },
            { id: 3, label: 'all P is not D' },
          ],
          correctId: [2],
          answer: '',
        },
        {
          id: '1.34',
          prompt: 'Not all druggists are rough',
          options: [
            { id: 0, label: 'some D is not R' },
            { id: 1, label: 'some D is R' },
            { id: 2, label: 'D is not R' },
            { id: 3, label: 'all D is not R' },
          ],
          correctId: [0],
          answer: '',
        },
        {
          id: '1.35',
          prompt: 'No one is weak unless he or she is confused',
          options: [
            { id: 0, label: 'W is not C' },
            { id: 1, label: 'all C is W' },
            { id: 2, label: 'no W is C' },
            { id: 3, label: 'all W is C' },
          ],
          correctId: [3],
          answer: '',
        },
        {
          id: '1.36',
          prompt: 'One or more poets are cheap',
          options: [
            { id: 0, label: 'some P is C' },
            { id: 1, label: 'C is P' },
            { id: 2, label: 'P is C' },
            { id: 3, label: 'some P is not C' },
          ],
          correctId: [0],
          answer: '',
        },
        {
          id: '1.37',
          prompt: "Whoever is beautiful isn't frantic",
          options: [
            { id: 0, label: 'B is not F' },
            { id: 1, label: 'all F is not B' },
            { id: 2, label: 'all B is not F' },
            { id: 3, label: 'no B is F' },
          ],
          correctId: [3],
          answer: '',
        },
        {
          id: '1.38',
          prompt: "It is false that some grocers aren't mediocre",
          options: [
            { id: 0, label: 'all G is M' },
            { id: 1, label: 'not some G is M' },
            { id: 2, label: 'some G is M' },
            { id: 3, label: 'G is M' },
          ],
          correctId: [0],
          answer: '',
        },
        {
          id: '1.39',
          prompt: 'No one is clean unless he or she is humorous',
          options: [
            { id: 0, label: 'all H is C' },
            { id: 1, label: 'no C is H' },
            { id: 2, label: 'all C is H' },
            { id: 3, label: 'C is not H' },
          ],
          correctId: [2],
          answer: '',
        },
        {
          id: '1.40',
          prompt: "I'm a wild clown in Berlin",
          options: [
            { id: 0, label: 'i is c' },
            { id: 1, label: 'i is C' },
            { id: 2, label: 'I is C' },
            { id: 3, label: 'I is c' },
          ],
          correctId: [1],
          answer: '',
        },
        {
          id: '1.41',
          prompt: "Whoever is dangerous isn't romantic",
          options: [
            { id: 0, label: 'no D is R' },
            { id: 1, label: 'all D is not R' },
            { id: 2, label: 'D is not R' },
            { id: 3, label: 'all R is not D' },
          ],
          correctId: [0],
          answer: '',
        },
        {
          id: '1.42',
          prompt: "It is false that some prisioners aren't curious",
          options: [
            { id: 0, label: 'some P is C' },
            { id: 1, label: 'all P is C' },
            { id: 2, label: 'not some P is C' },
            { id: 3, label: 'P is C' },
          ],
          correctId: [1],
          answer: '',
        },
        {
          id: '1.43',
          prompt: 'No one is mean unless he or she is boring',
          options: [
            { id: 0, label: 'M is not B' },
            { id: 1, label: 'all M is B' },
            { id: 2, label: 'no M is B' },
            { id: 3, label: 'all B is M' },
          ],
          correctId: [1],
          answer: '',
        },
        {
          id: '1.44',
          prompt: "I'm a bright reporter in Lisbon",
          options: [
            { id: 0, label: 'I is r' },
            { id: 1, label: 'i is r' },
            { id: 2, label: 'I is R' },
            { id: 3, label: 'i is R' },
          ],
          correctId: [3],
          answer: '',
        },
        {
          id: '1.45',
          prompt: "Whoever is generous isn't frighened",
          options: [
            { id: 0, label: 'all G is not F' },
            { id: 1, label: 'no G is F' },
            { id: 2, label: 'all F is not G' },
            { id: 3, label: 'G is not F' },
          ],
          correctId: [1],
          answer: '',
        },
        {
          id: '1.46',
          prompt: "It is false that some senators aren't gentle",
          options: [
            { id: 0, label: 'all S is G' },
            { id: 1, label: 'some S is G' },
            { id: 2, label: 'not some S is G' },
            { id: 3, label: 'S is G' },
          ],
          correctId: [0],
          answer: '',
        },
        {
          id: '1.47',
          prompt: 'No one is cruel unless he or she is powerful',
          options: [
            { id: 0, label: 'no C is P' },
            { id: 1, label: 'all C is P' },
            { id: 2, label: 'all P is C' },
            { id: 3, label: 'C is not P' },
          ],
          correctId: [1],
          answer: '',
        },
        {
          id: '1.48',
          prompt: "I'm a short banker in Paris",
          options: [
            { id: 0, label: 'i is B' },
            { id: 1, label: 'I is b' },
            { id: 2, label: 'i is b' },
            { id: 3, label: 'I is B' },
          ],
          correctId: [0],
          answer: '',
        },
        {
          id: '1.49',
          prompt: "Whoever is childish isn't bitter",
          options: [
            { id: 0, label: 'C is not B' },
            { id: 1, label: 'all B is not C' },
            { id: 2, label: 'no C is B' },
            { id: 3, label: 'all C is not B' },
          ],
          correctId: [2],
          answer: '',
        },
        {
          id: '1.50',
          prompt: "It is false that some Germans aren't confused",
          options: [
            { id: 0, label: 'not some G is C' },
            { id: 1, label: 'G is C' },
            { id: 2, label: 'all G is C' },
            { id: 3, label: 'some G is C' },
          ],
          correctId: [2],
          answer: '',
        },
      ],
    },
  ],
};
export { setA };
