// AUTO-GENERATED by logicola-ghidra/tools/port_set_r.py — review, do not hand-edit passages.
// Structure + answers: logicola-ghidra/notes/exercises/2008/decoded/set_R.txt (2008 DSL).
// The parsed JSON in that repo is defective (drops section *14, mangles the last sm entry).
//
// Wording follows the 2008 DSL except where Gensler himself later revised the same
// exercise for Introduction to Logic 3rd ed. (Routledge, 2017) §4.2a — the drill set
// these passages come from. Those revisions are listed in port_set_r.py's REVISIONS
// table with their textbook citation, and are applied there, not here:
//   - 'woman’s lib sponsors' -> 'feminist sponsors'  [Introduction to Logic 3rd ed. (2017) §4.2a #4 (ah x=9)]
//   - 'the other woman’s libbers' -> 'the other feminists'  [Introduction to Logic 3rd ed. (2017) §4.2a #26 (sm x=3)]
//
// TWO INLINE MARKUP BYTES IN THE SOURCE, both flattened by this port.
// Each marks the PRECEDING character, so 'must' is stored m<BD>u<BD>s<BD>t<BD>:
//   0xBD  emphasis — exactly 5 runs in the whole file: 'must' and 'probably'
//         in aa clause (3), and the book title 'Introduction to Logic' in the
//         set intro. Small, but that clause is *about* the must/probably
//         distinction, so the emphasis is carrying its meaning.
//   0xBE  a reference to another fallacy by code — 47 runs across all 18.
//         This port resolved them to prose names ('This violates appeal to
//         emotion, false stereotype, and both clauses of ad hominem'), which
//         keeps the meaning but loses the marking: they now read as ordinary
//         prose where the original set them apart.
// The markup convention from the pattern-lab hint prototype (*emphasis*,
// `notation`) is now live in the app's hint renderer
// (components/quiz/hintBlock.tsx). 0xBD is restored for `must` in aa
// clause (3) — deliberately not `probably`; see the note at that clause.
// The 0xBE fallacy-code references (47 runs) remain flattened to prose.

export type FallacyCode =
  | 'aa'
  | 'ac'
  | 'ae'
  | 'af'
  | 'ah'
  | 'ai'
  | 'am'
  | 'bp'
  | 'bw'
  | 'ci'
  | 'cq'
  | 'fs'
  | 'ge'
  | 'op'
  | 'pc'
  | 'ph'
  | 'pw'
  | 'sm';

export interface Fallacy {
  code: FallacyCode;
  /** Option id, 0-17, in the original answer grid's order. */
  id: number;
  /**
   * The FULL term, as the 2008 reference entries give it (`e:*XX i:` blocks
   * in set_R.txt). Used where the fallacy is being named as a concept: the
   * guide. Note `op` and `pc` carry the word "fallacy" here and nowhere
   * else, exactly as the original does.
   */
  name: string;
  /**
   * The TERSE grid label, from the original's answer-grid block (`d:16 t:`
   * in set_R.txt). Two jobs: the cell in the 18-option palette, and the
   * subject of the answer sentence, which appends the word "fallacy" —
   * "the genetic fallacy", "the post hoc fallacy".
   *
   * Keeping this apart from `name` is load-bearing. Collapsing the two is
   * how "This passage illustrates the genetic fallacy fallacy" shipped, and
   * why "Post hoc ergo propter hoc" wrapped to two lines in a grid cell
   * built for "post hoc". Thirteen of the eighteen are the same string in
   * both registers; five are not.
   */
  label: string;
  description: string;
  /** Numbered clauses referenced by answer notes ('This violates (1) and (2).'). */
  clauses?: string[];
}

export interface PassageVariant {
  /** Passage with {a} {A} {b} {B} {hc} {hC} {HC} {d} {D} {E} {g} tokens. */
  template: string;
  /** Accepted fallacies, primary first (original M-code multi-answers preserved). */
  accepted: FallacyCode[];
  /** Explanation shown after answering (original N-note). */
  note?: string;
  /** Word pool for the {g} token. */
  pool?: string[];
  /** Alternate form of the same variant (original coin-flip mirror). */
  mirror?: string;
}

export interface FallacySection {
  code: FallacyCode;
  variants: PassageVariant[];
}

export const FALLACIES: Fallacy[] = [
  {
    code: 'aa',
    id: 0,
    name: 'Appeal to authority',
    label: 'Appeal to authority',
    description: 'This is fallacious if:',
    clauses: [
      'the person isn’t an authority on the subject, or',
      'there’s no consensus of such authorities, or',
      // `*must*` restores the source's 0xBD emphasis on this word (see the
      // header note). The source marks `probably` too, but two marks in one
      // clause fragment it, and `must` is the operative word: asserting
      // necessity IS the fallacy (decided 2026-08-05, redesign-handoff.md).
      'the argument concludes that the authority *must* be right (and isn’t just probably right).',
    ],
  },
  {
    code: 'ac',
    id: 1,
    name: 'Appeal to the crowd',
    label: 'Appeal to crowd',
    description: 'Most people believe A. ∴ A is true.',
  },
  {
    code: 'ae',
    id: 2,
    name: 'Appeal to emotion',
    label: 'Appeal to emotion',
    description: 'To stir up emotions instead of arguing in a logical manner.',
  },
  {
    code: 'af',
    id: 3,
    name: 'Appeal to force',
    label: 'Appeal to force',
    description: 'To use threats or intimidation to get a conclusion accepted.',
  },
  {
    code: 'ah',
    id: 4,
    name: 'Ad hominem',
    label: 'Ad hominem',
    description: '(“personal attack”). This is fallacious if:',
    clauses: [
      'the grounds of the attack are irrelevant to the person’s rational competence, or',
      'the argument concludes that the person’s belief must be wrong (and isn’t just not rationally held).',
    ],
  },
  {
    code: 'ai',
    id: 5,
    name: 'Appeal to ignorance',
    label: 'Appeal to ignorance',
    description:
      '“No one has proved A. ∴ A is false.” “No one has disproved A. ∴ A is true.” Appeal to ignorance isn’t just where someone is talking in ignorance.',
  },
  {
    code: 'am',
    id: 6,
    name: 'Ambiguous',
    label: 'Ambiguous',
    description: 'A term or phrase changes meaning within the argument.',
  },
  {
    code: 'bp',
    id: 7,
    name: 'Beside the point',
    label: 'Beside the point',
    description:
      'The person argues for a conclusion irrelevant to the issue at hand. Beside the point isn’t just where the premises don’t prove the conclusion.',
  },
  {
    code: 'bw',
    id: 8,
    name: 'Black and white',
    label: 'Black and white',
    description:
      'Oversimplifying by assuming that one or another of two extremes must be true.',
  },
  {
    code: 'ci',
    id: 9,
    name: 'Circular',
    label: 'Circular',
    description:
      'An argument is circular (or “question begging”) if it presumes the truth of what is to be proved. A series of arguments is circular if it uses a premise to prove a conclusion – and then uses that conclusion to prove the premise.',
  },
  {
    code: 'cq',
    id: 10,
    name: 'Complex question',
    label: 'Complex question',
    description:
      'A question that assumes the truth of something false or doubtful.',
  },
  {
    code: 'fs',
    id: 11,
    name: 'False stereotype',
    label: 'False stereotype',
    description:
      'Assuming that members of a certain group are more alike than they actually are.',
  },
  {
    code: 'ge',
    id: 12,
    name: 'Genetic fallacy',
    label: 'Genetic',
    description: 'We can explain why you believe A. ∴ A is false.',
  },
  {
    code: 'op',
    id: 13,
    name: 'Opposition fallacy',
    label: 'Opposition',
    description: 'Our opponents believe A. ∴ A is false.',
  },
  {
    code: 'pc',
    id: 14,
    name: 'Pro-con fallacy',
    label: 'Pro-con',
    description:
      'This fallacy presents a one-sided view. It stresses only the advantages or only the disadvantages, instead of recognizing both and weighing one against the other.',
  },
  {
    code: 'ph',
    id: 15,
    name: 'Post hoc ergo propter hoc',
    label: 'Post hoc',
    description:
      '(“after this therefore because of this”) A happened after B. ∴ A was caused by B.',
  },
  {
    code: 'pw',
    id: 16,
    name: 'Part-whole',
    label: 'Part-whole',
    description:
      'The fallacy of arguing that something true of the whole must be true of all the parts, or that something true of all the parts must be true of the whole.',
  },
  {
    code: 'sm',
    id: 17,
    name: 'Straw man',
    label: 'Straw man',
    description: 'Misrepresenting the views of an opponent.',
  },
];

export const SECTIONS: FallacySection[] = [
  {
    code: 'aa',
    variants: [
      {
        template:
          'The sports hero {a} has a TV ad in which {b} says that {d} is the best car. {a} is a great player. So {d} is probably a great car.',
        accepted: ['aa'],
        note: 'This violates (1) and (2).',
      },
      {
        template:
          'Dr. {a} and all other competent authorities say we’ll land on Mars within fifty years. So this must be true.',
        accepted: ['aa'],
        note: 'This violates (3).',
      },
      {
        template:
          'The gorgeous actress Ms. {a} says that this is the best brand of shaving cream – and that she goes wild over men who use it. So I’m getting this brand!',
        accepted: ['aa', 'ae'],
        note: 'This violates appeal to emotion and all three clauses of appeal to authority.',
      },
      {
        template:
          'My friend {a} with a PhD in physics says that atomic power plants are safe. So {b} must be right.',
        accepted: ['aa'],
        note: 'This violates (2) and (3).',
      },
      {
        template:
          'The head of the {E} party claims that {A} is by far the best candidate. So {A} must be the best candidate.',
        accepted: ['aa'],
        note: 'This violates (2) and (3).',
      },
      {
        template:
          'Dr. {a} of the biology department has spent years researching the effects of marijuana. {B} says that marijuana is harmless. So this must be true.',
        accepted: ['aa'],
        note: 'This violates (2) and (3).',
      },
    ],
  },
  {
    code: 'ac',
    variants: [
      {
        template:
          'Most people believe that {d}s are excellent cars. So they must be right.',
        accepted: ['ac'],
      },
      {
        template:
          'Recent polls say that most people favor {a}, the {E} candidate. So I’m going to vote for {hc}.',
        accepted: ['ac'],
      },
      {
        template:
          'No one accepts {a}’s theory any more. So {hC} theory must be wrong.',
        accepted: ['ac'],
      },
      {
        template:
          'Almost everyone I know thinks that {d} stock is going to fall sharply. So it surely will.',
        accepted: ['ac'],
      },
      {
        template:
          'A lot of people are saying that {a} will be the next {E} candidate. So this is sure to happen.',
        accepted: ['ac'],
      },
      {
        template:
          'This {g} gets rave reviews from most people. So the {g} must be pretty good.',
        accepted: ['ac'],
        pool: ['course', 'beer', 'book', 'cereal', 'teacher'],
      },
    ],
  },
  {
    code: 'ae',
    variants: [
      {
        template:
          'The ad shows a sexy girl racing down the mountain road in her new {d}, with catchy music. Buy a {d}! What a car!',
        accepted: ['ae'],
      },
      {
        template:
          '{a}’s theory is simply revolting! I reject it firmly and I hope you do too.',
        accepted: ['ae'],
      },
      {
        template:
          'This proposal from {a} is a typically nauseating {E} proposal and thus is to be rejected.',
        accepted: ['ae', 'op', 'fs'],
        note: 'This violates appeal to emotion, false stereotype, and opposition.',
      },
      {
        template:
          'This new {E} proposal is really exciting. I love it! We should all vote for it.',
        accepted: ['ae'],
      },
      {
        template:
          'Dr. {a}, if you don’t pass me in this course then I’ll get depressed and my self-image will sink even lower. Surely you could give me at least a D!',
        accepted: ['ae'],
      },
      {
        template:
          'As intelligent members of the jury, you can’t find my client {A} guilty. {A} grew up in a poor family, as did many of you, and found life difficult. Your vote will show whether you understand this.',
        accepted: ['ae', 'bp'],
        note: 'This violates appeal to emotion and beside the point.',
      },
      {
        template:
          'Dr. {a}, my parents will get mad at me if I get a D – and I will feel so bad inside. Please? You know how I loved your course. I surely deserve at least a C.',
        accepted: ['ae'],
      },
    ],
  },
  {
    code: 'af',
    variants: [
      {
        template: '{A}, just accept this and shut up!',
        accepted: ['af'],
      },
      {
        template:
          '{A}, you better support this measure. Otherwise you’ll lose a lot of votes from us {D}s.',
        accepted: ['af'],
      },
      {
        template:
          'Surely, {a}, you agree that I deserve a raise. After all, you wouldn’t want people to hear about how you cheat on your expense account!',
        accepted: ['af'],
      },
      {
        template:
          'You better keep quiet about my illegal activities, {A}. Neither of us wants unfortunate accidents to happen.',
        accepted: ['af'],
      },
      {
        template:
          'I’m right! If you disagree with me, you get sent to your room!',
        accepted: ['af'],
      },
      {
        template:
          'If I don’t get a good grade, Dr. {a}, I’m going to talk to the dean about you. You recall that the dean is my {g}, don’t you?',
        accepted: ['af'],
        pool: ['father', 'mother'],
      },
    ],
  },
  {
    code: 'ah',
    variants: [
      {
        template:
          '{a} recently criticized the new tax policy. But we discovered that {b} didn’t know the details of the old tax policy. {HC} view must thus be wrong.',
        accepted: ['ah'],
        note: 'This violates clause (2).',
      },
      {
        template:
          'Hume’s philosophy said human knowledge was impossible. But Hume was inconsistent, since in real life he thought he knew things. So his philosophy must be wrong.',
        accepted: ['ah'],
        note: 'This violates clause (2).',
      },
      {
        template:
          'According to some of the Nazis: Einstein’s views should be rejected because Einstein was Jewish.',
        accepted: ['ah'],
        note: 'This violates clauses (1) and (2).',
      },
      {
        template:
          'Nietzsche said that the Christian “Love thy neighbor” was shallow and wrong. But Nietzsche later went insane. This shows that he was wrong.',
        accepted: ['ah'],
        note: 'This violates clauses (1) and (2).',
      },
      {
        template:
          'Officer {a}, you can’t criticize me for stealing. Didn’t I just read in the paper about police corruption?',
        accepted: ['ah'],
        note: 'This violates clauses (1) and (2).',
      },
      {
        template:
          'We can’t take seriously {a}’s plea for lower tax rates for corporations. {a} is the head of a large company and thus {b} stands to gain from lower taxes.',
        accepted: ['ah'],
        note: 'This violates clauses (1) and (2).',
      },
      {
        template:
          'Dr. {a} told me to lose weight and give up smoking. But {b} is overweight and smokes {hc}self, so I can ignore {hC} advice.',
        accepted: ['ah'],
        note: 'This violates clauses (1) and (2).',
      },
      {
        template:
          'Karl Marx was a personal failure who couldn’t support his family. So his political theory must be wrong.',
        accepted: ['ah'],
        note: 'This violates clauses (1) and (2).',
      },
      {
        template:
          'We should reject Mendel’s genetic theories, since he was a monk and thus couldn’t have known anything about science.',
        accepted: ['ah', 'fs'],
        note: 'This violates false stereotype and both clauses of ad hominem.',
      },
      {
        template:
          'The equal rights amendment was foolish, since its feminist sponsors were nothing but bra-less bubbleheads.',
        accepted: ['ah', 'ae', 'fs'],
        note: 'This violates appeal to emotion, false stereotype, and both clauses of ad hominem.',
      },
      {
        template:
          '{a} and others who opposed the war were obviously wrong. They were just a bunch of cowardly homosexual communists.',
        accepted: ['ah', 'ae', 'fs'],
        note: 'This violates appeal to emotion, false stereotype, and both clauses of ad hominem.',
      },
    ],
  },
  {
    code: 'ai',
    variants: [
      {
        template:
          'We haven’t been able to prove that senator {a} is honest. So we must conclude that {b} is dishonest.',
        accepted: ['ai'],
        mirror:
          'We haven’t been able to prove that senator {a} is dishonest. So we must conclude that {b} is honest.',
      },
      {
        template:
          'Since we haven’t been able to prove that there is a God, we must conclude that there is no God.',
        accepted: ['ai'],
      },
      {
        template:
          'Since we haven’t been able to prove that there is no God, we must conclude that there is a God.',
        accepted: ['ai'],
      },
      {
        template:
          '{a} states that {hC} company has been unable to prove that these children’s toys are dangerous. So these toys must be safe.',
        accepted: ['ai'],
      },
      {
        template:
          '{a} states that {hC} company has been unable to prove that these cigarettes are dangerous. So they must be safe.',
        accepted: ['ai'],
      },
      {
        template:
          '{a} is probably a Communist. After all, there is nothing in the files to disprove {hC} Communist connections.',
        accepted: ['ai'],
      },
      {
        template:
          'We haven’t been able to disprove the existence of {g}. Therefore we should affirm the existence of {g}.',
        accepted: ['ai'],
        pool: ['bigfoot', 'visitors from space', 'an afterlife'],
      },
      {
        template:
          'We haven’t been able to prove the existence of {g}. Therefore we should deny the existence of {g}.',
        accepted: ['ai'],
        pool: ['bigfoot', 'visitors from space', 'an afterlife'],
      },
    ],
  },
  {
    code: 'am',
    variants: [
      {
        template:
          'Since God is love and love is an emotion, God must be an emotion.',
        accepted: ['am'],
        note: '“Love” could mean “supremely loving person” or “feeling of love.”',
      },
      {
        template:
          'Science tells us that this brick wall isn’t solid. So our common sense beliefs are wrong here.',
        accepted: ['am'],
        note: '“Solid” could mean “resisting pressure” or “without microscopic holes.”',
      },
      {
        template:
          'There are scientific laws. Where there are laws there must be a lawgiver. Hence some lawgiver set up the laws to govern our universe. This could only be God.',
        accepted: ['am'],
        note: '“Laws” could mean “observed regularities” or “something legislated.”',
      },
      {
        template:
          'Only men are rational animals. No woman is a man. Therefore no woman is a rational animal.',
        accepted: ['am'],
        note: '“Man” could mean “human being” or “adult male human being.”',
      },
      {
        template:
          'Ultimately, only pleasure is able to be desired. So only pleasure is ultimately desirable. So only pleasure is worth seeking.',
        accepted: ['am'],
        note: '“Desirable” could mean “able to be desired” or “worth being desired.”',
      },
      {
        template:
          'You agree that we ought to elect liberals. So you have to conclude that we ought to elect {a} – since {b}’s a “liberal” in my sense (= “someone opposed to setting up an hereditary monarchy”).',
        accepted: ['am'],
        note: 'This isn’t what you mean when you say you support liberals.',
      },
      {
        template:
          'Most college students are mainly concerned with sports, liquor, and sex. So this is normal. But {a} is mainly concerned with poetry. So {hC} case is abnormal and hence not healthy.',
        accepted: ['am', 'fs'],
        note: 'This shifts between the “average” and “healthy” senses of “normal.”',
      },
    ],
  },
  {
    code: 'bp',
    variants: [
      {
        template:
          'Hitler once talked to a group concerned with the threat of a Nazi-imposed dictatorship. He spent his time denouncing the evils of pacifism.',
        accepted: ['bp'],
      },
      {
        template:
          '{a}, in arguing that {b} deserved at least a B+ for {hC} work, showed {hC} professor that {b} was from a poor family and had to work long hours to pay for {hC} schooling.',
        accepted: ['bp', 'ae'],
        note: 'This violates beside the point and appeal to emotion.',
      },
      {
        template:
          '{a}, my opponent, asked me to explain irregularities in my tax returns. But why is {b} so interested with this? Maybe {b} should be concerned with {hC} former connections with the mob.',
        accepted: ['bp', 'ah', 'af'],
        note: 'This violates beside the point, ad hominem, and perhaps appeal to force (threat).',
      },
      {
        template:
          'President {a}’s veto was the right move. In these troubled times we need decisive leadership, even in the face of opposition. We should thank {hc} for {hC} courageous move.',
        accepted: ['bp', 'ae'],
        note: 'This violates beside the point (why was the veto right?) and appeal to emotion.',
      },
      {
        template:
          'You ask what concrete proposals I have. Well, we need a whole new direction. Our country under president {a} has been going down the drain. We need to change.',
        accepted: ['bp'],
        note: 'The person didn’t answer the question.',
      },
      {
        template:
          '{a}: “Playing on the basketball team is the best education you can get in college.” Friend: “Can’t classes teach you more?” {a}: “Well, most athletes are good scholars; for example ....”',
        accepted: ['bp'],
        note: 'Even if that’s true, it’s beside the point.',
      },
      {
        template:
          'The defense claims that there is doubt that {a} committed the crime. But are we going to let this horrible crime go unpunished because of this? Consider how horrible the crime was.',
        accepted: ['bp', 'ae'],
        note: 'This violates beside the point (we have to show that {a} is guilty) and appeal to emotion.',
      },
    ],
  },
  {
    code: 'bw',
    variants: [
      {
        template:
          'Our economic system in the United States is capitalism. The other approach is socialism.',
        accepted: ['bw'],
      },
      {
        template:
          'Either you’re willing to fight to defend your country, or you aren’t a good citizen.',
        accepted: ['bw'],
      },
      {
        template:
          '{a} hated my course. {B} must have been very lazy. I only get two kinds of students: energetic ones who love my course and lazy ones who hate it.',
        accepted: ['bw'],
      },
      {
        template:
          'The way I figure it, people are either logical types who have little emotion or else emotional types who care little about logical reasoning.',
        accepted: ['bw'],
      },
      {
        template: '{A}, are you an athlete or an intellectual? Tell me which.',
        accepted: ['bw'],
      },
      {
        template:
          'Either you favor a massive arms buildup, or you aren’t a patriotic American.',
        accepted: ['bw'],
      },
      {
        template:
          'I figure that a person who doesn’t think that the American free enterprise system is the greatest in the world must be a Communist.',
        accepted: ['bw'],
      },
    ],
  },
  {
    code: 'ci',
    variants: [
      {
        template:
          'God has to exist, since this world must have been created by a Supreme Being.',
        accepted: ['ci'],
      },
      {
        template: 'The soul is immortal, since it cannot die.',
        accepted: ['ci'],
      },
      {
        template:
          '{a} must like me. {B} told me {b} likes me – and {b} said that {b} always tells the truth to people {b} likes.',
        accepted: ['ci'],
      },
      {
        template:
          'How do I know it? Well, {a} told me. How does {a} know it? Well, I told {hc}.',
        accepted: ['ci'],
      },
      {
        template:
          '{a} must disagree with me, since {b} is irrational. And {a} must be irrational, since {b} disagrees with me.',
        accepted: ['ci'],
      },
      {
        template:
          'Believing in miracles is unreasonable, since no responsible person believes in them. How about {a}? Well, the mere fact that {b} believes in miracles shows that {b} is not responsible.',
        accepted: ['ci'],
      },
      {
        template:
          'The bible must tell the truth. After all, it is God’s word. How do I know that it is God’s word? Well, the bible says it is – and the bible tells the truth.',
        accepted: ['ci'],
      },
      {
        template:
          'The Rolling Stones are the greatest rock group ever – since people with true appreciation for rock prefer this group. I measure one’s appreciation for rock by how the person appreciates this great group.',
        accepted: ['ci'],
      },
      {
        template:
          'You’re wrong in disagreeing with me, {A}, because what you said is an error.',
        accepted: ['ci'],
      },
    ],
  },
  {
    code: 'cq',
    variants: [
      {
        template:
          'Why is the {E} party so much more responsive to the real needs of the people?',
        accepted: ['cq', 'ci'],
        note: 'This violates complex question and perhaps circular.',
      },
      {
        template:
          'Let’s ask how some people could be fooled into thinking that {A} is a better candidate than myself.',
        accepted: ['cq', 'ci'],
        note: 'This violates complex question and perhaps circular.',
      },
      {
        template:
          'The prosecutor asked me, “Where did you hide the money that you stole?”',
        accepted: ['cq', 'ci'],
        note: 'This violates complex question and perhaps circular.',
      },
      {
        template: 'Do you still beat your wife?',
        accepted: ['cq', 'ci'],
        note: 'This violates complex question and perhaps circular.',
      },
      {
        template:
          'So you didn’t like my book, {A}. What defect in your character do you attribute this to?',
        accepted: ['cq', 'ci'],
        note: 'This violates complex question and perhaps circular.',
      },
      {
        template:
          '{a} asked me whether I was still wasting my time at the university.',
        accepted: ['cq', 'ci'],
        note: 'This violates complex question and perhaps circular.',
      },
      {
        template: 'Do you want to be a good little boy and go to bed?',
        accepted: ['cq', 'ci'],
        note: 'This violates complex question and perhaps circular.',
      },
    ],
  },
  {
    code: 'fs',
    variants: [
      {
        template:
          '{a} is a logician. So {b} must be a non-emotional person. You probably know that logicians are non-emotional.',
        accepted: ['fs'],
      },
      {
        template:
          '{a} is a business major. So, like all other business majors, {b} must be concerned not with ideas but only with making money.',
        accepted: ['fs'],
      },
      {
        template: 'All Italians are lovers.',
        accepted: ['fs'],
      },
      {
        template: 'No New Yorkers care about their fellow human beings.',
        accepted: ['fs'],
      },
      {
        template:
          'In your paper, {A}, you express sympathy with some of the views of Karl Marx. So you must be one of those dangerous sorts who want to overthrow the government.',
        accepted: ['fs'],
      },
      {
        template:
          '{a} made an appointment to see me. But of course {b} didn’t show. Students are all irresponsible.',
        accepted: ['fs'],
      },
      {
        template:
          'Academic philosophers these days are all logical positivists. None of them accept a spiritual dimension of humanity.',
        accepted: ['fs', 'sm'],
        note: 'This violates false stereotype and straw man.',
      },
    ],
  },
  {
    code: 'ge',
    variants: [
      {
        template:
          'Any good psychologist would recognize why {A} has those beliefs. So these beliefs must be false.',
        accepted: ['ge'],
      },
      {
        template:
          'This new book by {a} explains why Christianity spread so fast in the ancient world. {B} thus refutes Christianity.',
        accepted: ['ge'],
      },
      {
        template:
          'Dr. {a} in {hC} course explains how the modern belief in universal human rights arose in a specific historical context. {B} concludes that there is no objective basis for this belief.',
        accepted: ['ge'],
      },
      {
        template:
          'Belief in God is to be explained in terms of one’s need for a father-figure. Hence this belief is false.',
        accepted: ['ge'],
      },
      {
        template:
          'Religion originated from myth. Myth, of course, consists in superstitious errors. So religion must be false.',
        accepted: ['ge'],
      },
      {
        template:
          'The main reason you buy {d}s is that your family taught you that {d} makes the best cars. So your belief that {d}s are great cars is clearly wrong.',
        accepted: ['ge'],
      },
    ],
  },
  {
    code: 'op',
    variants: [
      {
        template:
          '{A} and the other dirty {D}s say that we ought to raise taxes. So therefore we shouldn’t do this.',
        accepted: ['op'],
      },
      {
        template:
          'Our enemies – the {D}s – are against this bill. So the bill must be pretty good.',
        accepted: ['op'],
      },
      {
        template:
          'The {D}s have come out in favor of the measure. So we should come out against it.',
        accepted: ['op'],
      },
    ],
  },
  {
    code: 'pc',
    variants: [
      {
        template:
          '{a} is intelligent and has a lot of experience in politics. So you should vote for {hc}.',
        accepted: ['pc'],
        note: 'Maybe {b}’s a crook. Or maybe {hC} opponent is even more qualified.',
      },
      {
        template:
          '{d}s are inexpensive and get good gas mileage. So you should get a {d}.',
        accepted: ['pc'],
        note: 'What are the disadvantages of getting a {d}?',
      },
      {
        template:
          '{d}s are expensive and hard to get repaired. So you shouldn’t buy one.',
        accepted: ['pc'],
        note: 'What are the advantages of getting a {d}?',
      },
      {
        template:
          'We should legalize gambling in our state because it would be a new source of tax revenue, it would encourage tourists from other states to come and spend money here, and it would cost the state nothing.',
        accepted: ['pc'],
        note: 'What are the disadvantages?',
      },
    ],
  },
  {
    code: 'ph',
    variants: [
      {
        template:
          '{a} had a beer before taking the exam. Then {b} got 100%. It’s amazing what a beer can do! I’ll try it next time.',
        accepted: ['ph'],
      },
      {
        template:
          '{a} walked under a ladder. {B} got fired from {hC} job a short time later. This proves again that walking under a ladder will bring you bad luck.',
        accepted: ['ph'],
      },
      {
        template:
          'People who read the Wall Street Journal make more money than average. I’m getting a subscription. Then I’ll make more money than average.',
        accepted: ['ph'],
      },
      {
        template:
          '{a} wore this headband and then kicked two long field goals. The headband brought him good luck.',
        accepted: ['ph'],
      },
      {
        template:
          'Look at all the bad things that happened while my {E} opponent {a} was in office. If you don’t want to elect an official who will bring about such things, then vote against my opponent.',
        accepted: ['ph'],
      },
      {
        template:
          'Whenever I go camping it seems to rain. I’m going backpacking next week. So watch for rain!',
        accepted: ['ph'],
      },
      {
        template:
          'Practically every heroin addict first tried marijuana. So marijuana causes heroin addiction.',
        accepted: ['ph'],
      },
      {
        template:
          'Ms. {a} brushed her teeth with Ultra Zest and then attracted boys like a magnet! Wow – I’m going to get some Ultra Zest, because then I will attract boys too!',
        accepted: ['ph'],
      },
    ],
  },
  {
    code: 'pw',
    variants: [
      {
        template:
          'My essay is brilliant. So each part of it must be brilliant.',
        accepted: ['pw'],
      },
      {
        template:
          'Each part of my essay is brilliant. So my essay must be brilliant.',
        accepted: ['pw'],
      },
      {
        template:
          'This is a great team. So {A}, who is on this team, must be a great player.',
        accepted: ['pw'],
      },
      {
        template:
          '{A}, who is on this team, is a great player. So this must be a great team.',
        accepted: ['pw'],
      },
      {
        template:
          'Each person in this country desires his or her own happiness. So the country as a whole must desire the happiness of the whole country.',
        accepted: ['pw'],
      },
      {
        template:
          'I kept thinking “One little drink won’t hurt” as I had one little drink. I repeated this reasoning ten times.',
        accepted: ['pw'],
      },
      {
        template:
          'Each thing in the universe comes into existence and later passes out of existence. So the universe also must have come into existence and must later pass out of existence.',
        accepted: ['pw'],
      },
      {
        template:
          'This used {d} won’t cost you much. The payments will only come to about $\\$20$ a day. Now $\\$20$ is not much at all these days.',
        accepted: ['pw'],
      },
      {
        template:
          'Each part of life has a purpose. Your eyes, hands, and so forth all have a purpose. Hence life itself must have a purpose.',
        accepted: ['pw'],
      },
    ],
  },
  {
    code: 'sm',
    variants: [
      {
        template:
          '({a} proposes cutting defense spending by 10%.) My opponent {a} wants to disarm our country and hand it over on a silver platter to our enemies.',
        accepted: ['sm'],
      },
      {
        template:
          '({a} suggests closing some of the seldom used rapid transit stops.) {a}, my opponent for mayor, evidently wants to shut down all public transportation for our city!',
        accepted: ['sm'],
      },
      {
        template:
          'I oppose this bill. Contrary to what the {D}s think, this bill won’t solve all of our problems.',
        accepted: ['sm'],
      },
      {
        template:
          '{a} and the other feminists deny all difference between male and female. But this is absurd, as anyone with eyes can see.',
        accepted: ['sm', 'fs'],
        note: 'This violates straw man and false stereotype.',
      },
      {
        template:
          '{a} and the other atheists are pretty stupid. They deny God’s existence because they can’t see him. But who has seen electrons either?',
        accepted: ['sm', 'fs'],
        note: 'This violates straw man and false stereotype.',
      },
      {
        template:
          '{a} and the other Christians are pretty stupid. They all believe that the world was created in six days. None of them cares anything about science.',
        accepted: ['sm', 'fs'],
        note: 'This violates straw man and false stereotype.',
      },
    ],
  },
];

export const SURNAMES = [
  'Martinez',
  'Smith',
  'Jones',
  'Brown',
  'Greene',
  'Fernandez',
  'Connolly',
  'Wong',
  'Weiss',
  'Gensler',
  'Wilson',
  'Rogers',
  'Hilton',
  'Miller',
  'Boyle',
  'Hughes',
];

export const CARS = [
  'Honda',
  'Ford',
  'Chevrolet',
  'Pontiac',
  'Toyota',
  'Volkswagen',
  'Buick',
  'Dodge',
];

/** Party pools: {D} renders the noun, {E} the adjective (democrat -> democratic). */
export const PARTIES = [
  { noun: 'socialist', adj: 'socialist' },
  { noun: 'republican', adj: 'republican' },
  { noun: 'democrat', adj: 'democratic' },
  { noun: 'conservative', adj: 'conservative' },
  { noun: 'liberal', adj: 'liberal' },
];

/** Pronoun bundles; one is chosen per passage so pronouns agree throughout. */
export const GENDERS = [
  { b: 'he', B: 'He', hc: 'him', hC: 'his', HC: 'His' },
  { b: 'she', B: 'She', hc: 'her', hC: 'her', HC: 'Her' },
];
