// AUTO-GENERATED by logicola-ghidra/tools/port_set_r.py — review, do not hand-edit passages.
// Structure + answers: logicola-ghidra/notes/exercises/2008/decoded/set_R.txt (2008 DSL).
// The parsed JSON in that repo is defective (drops section *14, mangles the last sm entry).
//
// PASSAGE PROVENANCE. Every passage added after the 2008 port carries an
// `// Added YYYY-MM-DD` comment above it; a passage with no such comment is
// from the 2008 source. Both are generated — to change either, edit
// port_set_r.py, never this file. The dates exist so that a reader years
// from now can tell Gensler's material from ours at a glance, and can date
// anything that has gone stale without needing the git history.
//
// Wording follows the 2008 DSL except where Gensler himself later revised the same
// exercise for Introduction to Logic 3rd ed. (Routledge, 2017) §4.2a — the drill set
// these passages come from. Those revisions are listed in port_set_r.py's REVISIONS
// table with their textbook citation, and are applied there, not here:
//   - 'woman’s lib sponsors' -> 'feminist sponsors'  [Introduction to Logic 3rd ed. (2017) §4.2a #4 (ah x=9)]
//   - 'the other woman’s libbers' -> 'the other feminists'  [Introduction to Logic 3rd ed. (2017) §4.2a #26 (sm x=3)]
//
// TWO INLINE MARKUP BYTES IN THE SOURCE, both flattened by this port.
// Each marks the PRECEDING character, so 'must' is stored m<BD>u<BD>s<BD>t<BD>:
//   0xBD  emphasis — exactly 5 runs in the whole file: 'must' and 'probably'
//         in aa clause (3), and the book title 'Introduction to Logic' in the
//         set intro. Small, but that clause is *about* the must/probably
//         distinction, so the emphasis is carrying its meaning.
//   0xBE  a reference to another fallacy by code — 47 runs across all 18.
//         This port resolved them to prose names ('This violates appeal to
//         emotion, false stereotype, and both clauses of ad hominem'), which
//         keeps the meaning but loses the marking: they now read as ordinary
//         prose where the original set them apart.
// The markup convention from the pattern-lab hint prototype (*emphasis*,
// `notation`) is now live in the app's hint renderer
// (components/quiz/hintBlock.tsx). 0xBD is restored for `must` in aa
// clause (3) — deliberately not `probably`; see the note at that clause.
// The 0xBE fallacy-code references (47 runs) remain flattened to prose.

export type FallacyCode =
  | 'aa'
  | 'ac'
  | 'ae'
  | 'af'
  | 'ah'
  | 'ai'
  | 'am'
  | 'bp'
  | 'bw'
  | 'ci'
  | 'cq'
  | 'fs'
  | 'ge'
  | 'op'
  | 'pc'
  | 'ph'
  | 'pw'
  | 'sm';

export interface Fallacy {
  code: FallacyCode;
  /** Option id, 0-17, in the original answer grid's order. */
  id: number;
  /**
   * The FULL term, as the 2008 reference entries give it (`e:*XX i:` blocks
   * in set_R.txt). Used where the fallacy is being named as a concept: the
   * guide. Note `op` and `pc` carry the word "fallacy" here and nowhere
   * else, exactly as the original does.
   */
  name: string;
  /**
   * The TERSE grid label, from the original's answer-grid block (`d:16 t:`
   * in set_R.txt). Two jobs: the cell in the 18-option palette, and the
   * subject of the answer sentence, which appends the word "fallacy" —
   * "the genetic fallacy", "the post hoc fallacy".
   *
   * Keeping this apart from `name` is load-bearing. Collapsing the two is
   * how "This passage illustrates the genetic fallacy fallacy" shipped, and
   * why "Post hoc ergo propter hoc" wrapped to two lines in a grid cell
   * built for "post hoc". Thirteen of the eighteen are the same string in
   * both registers; five are not.
   */
  label: string;
  description: string;
  /** Numbered clauses referenced by answer notes ('This violates (1) and (2).'). */
  clauses?: string[];
}

export interface PassageVariant {
  /** Passage with {a} {A} {b} {B} {hc} {hC} {HC} {d} {D} {E} {g} tokens. */
  template: string;
  /** Accepted fallacies, primary first (original M-code multi-answers preserved). */
  accepted: FallacyCode[];
  /** Explanation shown after answering (original N-note). */
  note?: string;
  /** Word pool for the {g} token. */
  pool?: string[];
  /** Alternate form of the same variant (original coin-flip mirror). */
  mirror?: string;
}

export interface FallacySection {
  code: FallacyCode;
  variants: PassageVariant[];
}

export const FALLACIES: Fallacy[] = [
  {
    code: 'aa',
    id: 0,
    name: 'Appeal to authority',
    label: 'Appeal to authority',
    description: 'This is fallacious if:',
    clauses: [
      'the person isn’t an authority on the subject, or',
      'there’s no consensus of such authorities, or',
      // `*must*` restores the source's 0xBD emphasis on this word (see the
      // header note). The source marks `probably` too, but two marks in one
      // clause fragment it, and `must` is the operative word: asserting
      // necessity IS the fallacy (decided 2026-08-05, redesign-handoff.md).
      'the argument concludes that the authority *must* be right (and isn’t just probably right).',
    ],
  },
  {
    code: 'ac',
    id: 1,
    name: 'Appeal to the crowd',
    label: 'Appeal to crowd',
    description: 'Most people believe A. ∴ A is true.',
  },
  {
    code: 'ae',
    id: 2,
    name: 'Appeal to emotion',
    label: 'Appeal to emotion',
    description: 'To stir up emotions instead of arguing in a logical manner.',
  },
  {
    code: 'af',
    id: 3,
    name: 'Appeal to force',
    label: 'Appeal to force',
    description: 'To use threats or intimidation to get a conclusion accepted.',
  },
  {
    code: 'ah',
    id: 4,
    name: 'Ad hominem',
    label: 'Ad hominem',
    description: '(“personal attack”). This is fallacious if:',
    clauses: [
      'the grounds of the attack are irrelevant to the person’s rational competence, or',
      'the argument concludes that the person’s belief must be wrong (and isn’t just not rationally held).',
    ],
  },
  {
    code: 'ai',
    id: 5,
    name: 'Appeal to ignorance',
    label: 'Appeal to ignorance',
    description:
      '“No one has proved A. ∴ A is false.” “No one has disproved A. ∴ A is true.” Appeal to ignorance isn’t just where someone is talking in ignorance.',
  },
  {
    code: 'am',
    id: 6,
    name: 'Ambiguous',
    label: 'Ambiguous',
    description: 'A term or phrase changes meaning within the argument.',
  },
  {
    code: 'bp',
    id: 7,
    name: 'Beside the point',
    label: 'Beside the point',
    description:
      'The person argues for a conclusion irrelevant to the issue at hand. Beside the point isn’t just where the premises don’t prove the conclusion.',
  },
  {
    code: 'bw',
    id: 8,
    name: 'Black and white',
    label: 'Black and white',
    description:
      'Oversimplifying by assuming that one or another of two extremes must be true.',
  },
  {
    code: 'ci',
    id: 9,
    name: 'Circular',
    label: 'Circular',
    description:
      'An argument is circular (or “question begging”) if it presumes the truth of what is to be proved. A series of arguments is circular if it uses a premise to prove a conclusion – and then uses that conclusion to prove the premise.',
  },
  {
    code: 'cq',
    id: 10,
    name: 'Complex question',
    label: 'Complex question',
    description:
      'A question that assumes the truth of something false or doubtful.',
  },
  {
    code: 'fs',
    id: 11,
    name: 'False stereotype',
    label: 'False stereotype',
    description:
      'Assuming that members of a certain group are more alike than they actually are.',
  },
  {
    code: 'ge',
    id: 12,
    name: 'Genetic fallacy',
    label: 'Genetic',
    description: 'We can explain why you believe A. ∴ A is false.',
  },
  {
    code: 'op',
    id: 13,
    name: 'Opposition fallacy',
    label: 'Opposition',
    description: 'Our opponents believe A. ∴ A is false.',
  },
  {
    code: 'pc',
    id: 14,
    name: 'Pro-con fallacy',
    label: 'Pro-con',
    description:
      'This fallacy presents a one-sided view. It stresses only the advantages or only the disadvantages, instead of recognizing both and weighing one against the other.',
  },
  {
    code: 'ph',
    id: 15,
    name: 'Post hoc ergo propter hoc',
    label: 'Post hoc',
    description:
      '(“after this therefore because of this”) A happened after B. ∴ A was caused by B.',
  },
  {
    code: 'pw',
    id: 16,
    name: 'Part-whole',
    label: 'Part-whole',
    description:
      'The fallacy of arguing that something true of the whole must be true of all the parts, or that something true of all the parts must be true of the whole.',
  },
  {
    code: 'sm',
    id: 17,
    name: 'Straw man',
    label: 'Straw man',
    description: 'Misrepresenting the views of an opponent.',
  },
];

export const SECTIONS: FallacySection[] = [
  {
    code: 'aa',
    variants: [
      {
        template:
          'The sports hero {a} has a TV ad in which {b} says that {d} is the best car. {a} is a great player. So {d} is probably a great car.',
        accepted: ['aa'],
        note: 'This violates (1) and (2).',
      },
      {
        template:
          'Dr. {a} and all other competent authorities say we’ll land on Mars within fifty years. So this must be true.',
        accepted: ['aa'],
        note: 'This violates (3).',
      },
      {
        template:
          'The actress Ms. {a} posts that this is the best skincare brand – and that everyone who uses it will look as good as she does. So I’m getting this brand!',
        accepted: ['aa', 'ae'],
        note: 'This violates appeal to emotion and all three clauses of appeal to authority.',
      },
      {
        template:
          'My friend {a} with a PhD in physics says that atomic power plants are safe. So {b} must be right.',
        accepted: ['aa'],
        note: 'This violates (2) and (3).',
      },
      {
        template:
          'The head of the {l} party claims that {P} is by far the best candidate. So {P} must be the best candidate.',
        accepted: ['aa'],
        note: 'This violates (2) and (3).',
      },
      {
        template:
          'Dr. {a} of the biology department has spent years researching the effects of marijuana. {B} says that marijuana is harmless. So this must be true.',
        accepted: ['aa'],
        note: 'This violates (2) and (3).',
      },
      {
        // Added 2026-08-19. Passages with no date are from the 2008 source.
        template:
          'Linus Pauling won two Nobel Prizes, and he spent his later years arguing that megadoses of vitamin C prevent the common cold. So megadoses of vitamin C must prevent the common cold.',
        accepted: ['aa'],
        note: 'This violates (1), (2) and (3). His prizes were in chemistry and in peace, and no consensus of nutrition researchers agreed with him.',
      },
      {
        // Added 2026-08-19. Passages with no date are from the 2008 source.
        template:
          'Kary Mullis won a Nobel Prize for a technique now used in every laboratory on earth. He also said that astrology works. So there is probably something to astrology.',
        accepted: ['aa'],
        note: 'This violates (1) and (2) — but not (3). The fallacy does not require the conclusion to claim certainty.',
      },
      {
        // Added 2026-08-19. Passages with no date are from the 2008 source.
        template:
          'MrBeast has hundreds of millions of subscribers, and he says his lunch kits are healthier than the kits they’re compared against. So they must be healthier.',
        accepted: ['aa'],
        note: 'This violates (1), (2) and (3). Registered dietitians disputed the claim, and an audience is not a qualification.',
      },
      {
        // Added 2026-08-19. Passages with no date are from the 2008 source.
        template:
          'Tom Brady won seven Super Bowls, and his nutrition method says that drinking enough water prevents sunburn. So drinking enough water probably prevents sunburn.',
        accepted: ['aa'],
        note: 'This violates (1) and (2). There is no evidence that hydration prevents sunburn, and quarterbacking is not dermatology.',
      },
      {
        // Added 2026-08-19. Passages with no date are from the 2008 source.
        template:
          'Picasso said that good artists copy and great artists steal. He was one of the greatest painters who ever lived. So he must have been right about it.',
        accepted: ['aa'],
        note: 'Two things are wrong. There is no evidence Picasso ever said it — his name only became attached to the line decades after his death, and it most likely descends from T. S. Eliot in 1920. And being a great painter would not make him right about it in any case.',
      },
      {
        // Added 2026-08-19. Passages with no date are from the 2008 source.
        template:
          'The startup’s board has two former Secretaries of State, a former Secretary of Defense, an admiral and a general. So its blood-testing technology must work.',
        accepted: ['aa'],
        note: 'This violates (1) and (3). Theranos had exactly this board. Not one member had a background in blood diagnostics, investors said the board was what convinced them, the valuation reached nine billion dollars — and the technology never worked.',
      },
      {
        // Added 2026-08-19. Passages with no date are from the 2008 source.
        template:
          'The engineers say the seals aren’t rated for tomorrow’s temperature. But management has approved the launch, and they’re the ones responsible for flight safety. So it must be safe to fly.',
        accepted: ['aa'],
        note: 'This violates (1) and (3) — and note who the actual authorities are here. This is the argument that preceded Challenger: the engineers said not to launch below 53°F, it was 36°F, and the Rogers Commission found management’s reversal was not driven by any new engineering data. Nothing changed except who was deciding.',
      },
      {
        // Added 2026-08-19. Passages with no date are from the 2008 source.
        template:
          'A new study found that chocolate helps you lose weight, and it was in the news everywhere. So chocolate must help you lose weight.',
        accepted: ['aa'],
        note: 'This violates (2) and (3). A single unreplicated study is not a consensus of authorities.',
      },
    ],
  },
  {
    code: 'ac',
    variants: [
      {
        template:
          'Most people believe that {d}s are excellent cars. So they must be right.',
        accepted: ['ac'],
      },
      {
        template:
          'Recent polls say that most people favor {p}, the {l} candidate. So I’m going to vote for {hc}.',
        accepted: ['ac'],
      },
      {
        template:
          'No one accepts {a}’s theory any more. So {hC} theory must be wrong.',
        accepted: ['ac'],
      },
      {
        template:
          'Almost everyone I know thinks that {d} stock is going to fall sharply. So it surely will.',
        accepted: ['ac'],
      },
      {
        template:
          'A lot of people are saying that {p} will be the next {l} candidate. So this is sure to happen.',
        accepted: ['ac'],
      },
      {
        template:
          'This {g} gets five-star reviews from most people. So the {g} must be pretty good.',
        accepted: ['ac'],
        pool: [
          'course',
          'book',
          'teacher',
          'wine',
          'app',
          'podcast',
          'restaurant',
          'show',
          'game',
        ],
      },
      {
        // Added 2026-08-19. Passages with no date are from the 2008 source.
        template:
          'Millions of people have signed up to sell for this multi-level marketing company. So it must be a good way to make money.',
        accepted: ['ac'],
        note: 'Analyses of income-disclosure statements put the share of participants who lose money at around 99%. How many people joined says nothing about how they did.',
      },
      {
        // Added 2026-08-19. Passages with no date are from the 2008 source.
        template:
          'Cristiano Ronaldo has more followers than any other player in the game. So he must be the best player in the game.',
        accepted: ['ac'],
        note: 'The premise is true — he is the most-followed person on Instagram. It is a fact about how many people are watching, not about how well he plays.',
      },
      {
        // Added 2026-08-19. Passages with no date are from the 2008 source.
        template:
          'More fans name {f} as the best in the game than name anyone else. So {f} is the best in the game.',
        accepted: ['ac'],
        note: 'This is a headcount of opinion. It reports what fans think, and offers nothing else.',
      },
      {
        // Added 2026-08-19. Passages with no date are from the 2008 source.
        template:
          'Look at the size of the crowd. Nobody else is drawing numbers like this. So {P} must be right about the economy.',
        accepted: ['ac'],
        note: 'Turnout measures enthusiasm. It does not measure whether the economic claim is true.',
      },
    ],
  },
  {
    code: 'ae',
    variants: [
      {
        template:
          'The ad shows a sexy girl racing down the mountain road in her new {d}, with catchy music. Buy a {d}! What a car!',
        accepted: ['ae'],
      },
      {
        template:
          '{a}’s theory is simply revolting! I reject it firmly and I hope you do too.',
        accepted: ['ae'],
      },
      {
        template:
          'This proposal from {p} is a typically nauseating {l} proposal and thus is to be rejected.',
        accepted: ['ae', 'op', 'fs'],
        note: 'This violates appeal to emotion, false stereotype, and opposition.',
      },
      {
        template:
          'This new {E} proposal is really exciting. I love it! We should all vote for it.',
        accepted: ['ae'],
      },
      {
        template:
          'Dr. {a}, if you don’t pass me in this course then I’ll get depressed and my self-image will sink even lower. Surely you could give me at least a D!',
        accepted: ['ae'],
      },
      {
        template:
          'As intelligent members of the jury, you can’t find my client {A} guilty. {A} grew up in a poor family, as did many of you, and found life difficult. Your vote will show whether you understand this.',
        accepted: ['ae', 'bp'],
        note: 'This violates appeal to emotion and beside the point.',
      },
      {
        template:
          'Dr. {a}, my parents will get mad at me if I get a D – and I will feel so bad inside. Please? You know how I loved your course. I surely deserve at least a C.',
        accepted: ['ae'],
      },
      {
        // Added 2026-08-19. Passages with no date are from the 2008 source.
        template:
          'Look at this photograph of the child. Now tell me you still oppose the policy.',
        accepted: ['ae'],
        note: 'The photograph may be moving and the policy may still be a bad one. Nothing here is an argument.',
      },
      {
        // Added 2026-08-19. Passages with no date are from the 2008 source.
        template:
          '{P} talked about their own family for ten minutes and half the room was in tears. So we should back the bill.',
        accepted: ['ae'],
        note: 'Whether the bill is any good is never addressed.',
      },
    ],
  },
  {
    code: 'af',
    variants: [
      {
        template: '{A}, just accept this and shut up!',
        accepted: ['af'],
      },
      {
        template:
          '{P}, you better support this measure. Otherwise you’ll lose a lot of votes from us {D}s.',
        accepted: ['af'],
      },
      {
        template:
          'Surely, {a}, you agree that I deserve a raise. After all, you wouldn’t want people to hear about how you cheat on your expense account!',
        accepted: ['af'],
      },
      {
        template:
          'You better keep quiet about my illegal activities, {A}. Neither of us wants unfortunate accidents to happen.',
        accepted: ['af'],
      },
      {
        template:
          'I’m right! If you disagree with me, you get sent to your room!',
        accepted: ['af'],
      },
      {
        template:
          'If I don’t get a good grade, Dr. {a}, I’m going to talk to the dean about you. You recall that the dean is my {g}, don’t you?',
        accepted: ['af'],
        pool: ['father', 'mother'],
      },
      {
        // Added 2026-08-19. Passages with no date are from the 2008 source.
        template:
          'Rate the course five stars, {a}. I’ll be writing your reference letter in the spring.',
        accepted: ['af'],
        note: 'Nothing here is an argument that the course was good.',
      },
      {
        // Added 2026-08-19. Passages with no date are from the 2008 source.
        template:
          'Sign the agreement, {A}. Our lawyers have a great deal more time than you do.',
        accepted: ['af'],
        note: 'The threat is the whole content of the appeal.',
      },
    ],
  },
  {
    code: 'ah',
    variants: [
      {
        template:
          '{a} recently criticized the new tax policy. But we discovered that {b} didn’t know the details of the old tax policy. {HC} view must thus be wrong.',
        accepted: ['ah'],
        note: 'This violates clause (2).',
      },
      {
        template:
          'Hume’s philosophy said human knowledge was impossible. But Hume was inconsistent, since in real life he thought he knew things. So his philosophy must be wrong.',
        accepted: ['ah'],
        note: 'This violates clause (2).',
      },
      {
        template:
          'According to some of the Nazis: Einstein’s views should be rejected because Einstein was Jewish.',
        accepted: ['ah'],
        note: 'This violates clauses (1) and (2).',
      },
      {
        template:
          'Nietzsche said that the Christian “Love thy neighbor” was shallow and wrong. But Nietzsche later went insane. This shows that he was wrong.',
        accepted: ['ah'],
        note: 'This violates clauses (1) and (2).',
      },
      {
        template:
          'Officer {a}, you can’t criticize me for stealing. Didn’t I just read in the paper about police corruption?',
        accepted: ['ah'],
        note: 'This violates clauses (1) and (2).',
      },
      {
        template:
          'We can’t take seriously {a}’s plea for lower tax rates for corporations. {a} is the head of a large company and thus {b} stands to gain from lower taxes.',
        accepted: ['ah'],
        note: 'This violates clauses (1) and (2).',
      },
      {
        template:
          'Dr. {a} told me to lose weight and give up smoking. But {b} is overweight and smokes {hc}self, so I can ignore {hC} advice.',
        accepted: ['ah'],
        note: 'This violates clauses (1) and (2).',
      },
      {
        template:
          'Karl Marx was a personal failure who couldn’t support his family. So his political theory must be wrong.',
        accepted: ['ah'],
        note: 'This violates clauses (1) and (2).',
      },
      {
        template:
          'We should reject Mendel’s genetic theories, since he was a monk and thus couldn’t have known anything about science.',
        accepted: ['ah', 'fs'],
        note: 'This violates false stereotype and both clauses of ad hominem.',
      },
      {
        template:
          'The equal rights amendment was foolish, since its feminist sponsors were nothing but bra-less bubbleheads.',
        accepted: ['ah', 'ae', 'fs'],
        note: 'This violates appeal to emotion, false stereotype, and both clauses of ad hominem.',
      },
      {
        template:
          '{a} and others who opposed the war were obviously wrong. They were just a bunch of cowardly homosexual communists.',
        accepted: ['ah', 'ae', 'fs'],
        note: 'This violates appeal to emotion, false stereotype, and both clauses of ad hominem.',
      },
    ],
  },
  {
    code: 'ai',
    variants: [
      {
        template:
          'We haven’t been able to prove that senator {a} is honest. So we must conclude that {b} is dishonest.',
        accepted: ['ai'],
        mirror:
          'We haven’t been able to prove that senator {a} is dishonest. So we must conclude that {b} is honest.',
      },
      {
        template:
          'Since we haven’t been able to prove that there is a God, we must conclude that there is no God.',
        accepted: ['ai'],
      },
      {
        template:
          'Since we haven’t been able to prove that there is no God, we must conclude that there is a God.',
        accepted: ['ai'],
      },
      {
        template:
          '{a} states that {hC} company has been unable to prove that these children’s toys are dangerous. So these toys must be safe.',
        accepted: ['ai'],
      },
      {
        template:
          '{a} states that {hC} company has been unable to prove that these cigarettes are dangerous. So they must be safe.',
        accepted: ['ai'],
      },
      {
        template:
          '{a} is probably a Communist. After all, there is nothing in the files to disprove {hC} Communist connections.',
        accepted: ['ai'],
      },
      {
        template:
          'We haven’t been able to disprove the existence of {g}. Therefore we should affirm the existence of {g}.',
        accepted: ['ai'],
        pool: [
          'bigfoot',
          'visitors from space',
          'an afterlife',
          'Atlantis',
          'mermaids',
          'unicorns',
          'ghosts',
          'psychic powers',
          'the Loch Ness monster',
          'alien life',
          'intelligent alien civilizations',
          'a multiverse',
          'a simulated universe',
          'parallel universes',
          'machine consciousness',
          'free will',
          'a soul',
        ],
      },
      {
        template:
          'We haven’t been able to prove the existence of {g}. Therefore we should deny the existence of {g}.',
        accepted: ['ai'],
        pool: [
          'bigfoot',
          'visitors from space',
          'an afterlife',
          'Atlantis',
          'mermaids',
          'unicorns',
          'ghosts',
          'psychic powers',
          'the Loch Ness monster',
          'alien life',
          'intelligent alien civilizations',
          'a multiverse',
          'a simulated universe',
          'parallel universes',
          'machine consciousness',
          'free will',
          'a soul',
        ],
      },
      {
        // Added 2026-08-19. Passages with no date are from the 2008 source.
        template:
          'No one has ever shown that medieval West Africa produced books. So it can’t have produced many.',
        accepted: ['ai'],
        note: 'Timbuktu’s libraries hold hundreds of thousands of manuscripts — science, medicine, law, theology, poetry — some from the thirteenth century, and the university at Sankore taught thousands of students. That something has not been shown to you is a fact about you.',
      },
    ],
  },
  {
    code: 'am',
    variants: [
      {
        template:
          'Since God is love and love is an emotion, God must be an emotion.',
        accepted: ['am'],
        note: '“Love” could mean “supremely loving person” or “feeling of love.”',
      },
      {
        template:
          'Science tells us that this brick wall isn’t solid. So our common sense beliefs are wrong here.',
        accepted: ['am'],
        note: '“Solid” could mean “resisting pressure” or “without microscopic holes.”',
      },
      {
        template:
          'There are scientific laws. Where there are laws there must be a lawgiver. Hence some lawgiver set up the laws to govern our universe. This could only be God.',
        accepted: ['am'],
        note: '“Laws” could mean “observed regularities” or “something legislated.”',
      },
      {
        template:
          'Only men are rational animals. No woman is a man. Therefore no woman is a rational animal.',
        accepted: ['am'],
        note: '“Man” could mean “human being” or “adult male human being.”',
      },
      {
        template:
          'Ultimately, only pleasure is able to be desired. So only pleasure is ultimately desirable. So only pleasure is worth seeking.',
        accepted: ['am'],
        note: '“Desirable” could mean “able to be desired” or “worth being desired.”',
      },
      {
        template:
          'You agree that we ought to elect liberals. So you have to conclude that we ought to elect {a} – since {b}’s a “liberal” in my sense (= “someone opposed to setting up an hereditary monarchy”).',
        accepted: ['am'],
        note: 'This isn’t what you mean when you say you support liberals.',
      },
      {
        template:
          'Most college students are mainly concerned with sports, liquor, and sex. So this is normal. But {a} is mainly concerned with poetry. So {hC} case is abnormal and hence not healthy.',
        accepted: ['am', 'fs'],
        note: 'This shifts between the “average” and “healthy” senses of “normal.”',
      },
      {
        // Added 2026-08-19. Passages with no date are from the 2008 source.
        template:
          'The model is intelligent — it scores higher than most people on the exam. Intelligent beings deserve rights. So the model deserves rights.',
        accepted: ['am'],
        note: '“Intelligent” means one thing in the first premise (scoring well on a test) and another in the second (the kind of mind that can be wronged).',
      },
      {
        // Added 2026-08-19. Passages with no date are from the 2008 source.
        template:
          'He’s the most valuable player in the league — no club has ever paid a higher fee for anyone. The most valuable player is the one who contributes most to his team. So he contributes more than anyone in the league.',
        accepted: ['am'],
        note: '“Valuable” means market price in the first premise and contribution in the second. Same word, two different things being measured.',
      },
      {
        // Added 2026-08-19. Passages with no date are from the 2008 source.
        template:
          'They promise your data is secure. Secure means nobody can get at it. So nobody can get at your data.',
        accepted: ['am'],
        note: '“Secure” in the promise means encrypted against interception. In the conclusion it means inaccessible to anyone at all, which is a different claim.',
      },
      {
        // Added 2026-08-19. Passages with no date are from the 2008 source.
        template:
          'The average salary here is ninety thousand. So half the people here earn more than that.',
        accepted: ['am'],
        note: '“Average” is the mean in the premise and the median in the conclusion. One word, two different statistics — and they come apart badly whenever a few figures are very large.',
      },
      {
        // Added 2026-08-19. Passages with no date are from the 2008 source.
        template:
          'The result was statistically significant. Significant findings matter. So this finding matters.',
        accepted: ['am'],
        note: '“Significant” means unlikely to be chance in the first premise, and important in the second. A tiny effect measured precisely enough is significant in the first sense and can matter not at all in the second.',
      },
      {
        // Added 2026-08-19. Passages with no date are from the 2008 source.
        template:
          'Italy is one of the oldest countries in Europe. But Italy became a country in 1861 and Brazil in 1822. So Brazil is older than one of the oldest countries in Europe.',
        accepted: ['am'],
        note: '“Country” means a place and a people in the first premise and a unified state in the second. Both dates are right — Italian unification 1861, Brazilian independence 1822 — and the conclusion still does not follow.',
      },
      {
        // Added 2026-08-19. Passages with no date are from the 2008 source.
        template:
          'In the sip test more people preferred Pepsi. So more people prefer Pepsi.',
        accepted: ['am'],
        note: '“Prefer” ranges over one mouthful in the premise and over a whole can in the conclusion. Sweeter drinks win a sip and can lose a can, which is why sip tests and sales can disagree.',
      },
    ],
  },
  {
    code: 'bp',
    variants: [
      {
        template:
          'Hitler once talked to a group concerned with the threat of a Nazi-imposed dictatorship. He spent his time denouncing the evils of pacifism.',
        accepted: ['bp'],
      },
      {
        template:
          '{a}, in arguing that {b} deserved at least a B+ for {hC} work, showed {hC} professor that {b} was from a poor family and had to work long hours to pay for {hC} schooling.',
        accepted: ['bp', 'ae'],
        note: 'This violates beside the point and appeal to emotion.',
      },
      {
        template:
          '{a}, my opponent, asked me to explain irregularities in my tax returns. But why is {b} so interested with this? Maybe {b} should be concerned with {hC} former connections with the mob.',
        accepted: ['bp', 'ah', 'af'],
        note: 'This violates beside the point, ad hominem, and perhaps appeal to force (threat).',
      },
      {
        template:
          'President {a}’s veto was the right move. In these troubled times we need decisive leadership, even in the face of opposition. We should thank {hc} for {hC} courageous move.',
        accepted: ['bp', 'ae'],
        note: 'This violates beside the point (why was the veto right?) and appeal to emotion.',
      },
      {
        template:
          'You ask what concrete proposals I have. Well, we need a whole new direction. Our country under president {a} has been going down the drain. We need to change.',
        accepted: ['bp'],
        note: 'The person didn’t answer the question.',
      },
      {
        template:
          '{a}: “Playing on the basketball team is the best education you can get in college.” Friend: “Can’t classes teach you more?” {a}: “Well, most athletes are good scholars; for example ....”',
        accepted: ['bp'],
        note: 'Even if that’s true, it’s beside the point.',
      },
      {
        template:
          'The defense claims that there is doubt that {a} committed the crime. But are we going to let this horrible crime go unpunished because of this? Consider how horrible the crime was.',
        accepted: ['bp', 'ae'],
        note: 'This violates beside the point (we have to show that {a} is guilty) and appeal to emotion.',
      },
      {
        // Added 2026-08-19. Passages with no date are from the 2008 source.
        template:
          'You say this study was too small to show anything. But science has given us antibiotics, vaccines and spaceflight. Are you really going to stand there and attack science?',
        accepted: ['bp', 'sm'],
        note: 'Whether science in general is valuable is not the issue. The issue is whether *this* study, with this sample size, shows what it is said to show.',
      },
      {
        // Added 2026-08-19. Passages with no date are from the 2008 source.
        template:
          'You say this patent extension shouldn’t be granted. But without patents, nobody would develop new medicines at all.',
        accepted: ['bp', 'sm'],
        note: 'Nobody in the argument denied that patents fund research. The question is whether this particular extension is warranted.',
      },
      {
        // Added 2026-08-19. Passages with no date are from the 2008 source.
        template:
          'You say there’s no evidence that playing classical music to babies helps them. But a study in Nature found that Mozart improved spatial reasoning in college students.',
        accepted: ['bp'],
        note: 'The study was on adults, on one spatial task, and the effect lasted minutes. Whatever it showed, it was not about babies.',
      },
      {
        // Added 2026-08-19. Passages with no date are from the 2008 source.
        template:
          'You say the album is badly produced. But she has sold more records this year than anyone alive.',
        accepted: ['bp'],
        note: 'Whether it sold is not whether it was well made. The reply answers a question nobody asked.',
      },
    ],
  },
  {
    code: 'bw',
    variants: [
      {
        template:
          'Our economic system in the United States is capitalism. The other approach is socialism.',
        accepted: ['bw'],
      },
      {
        template:
          'Either you’re willing to fight to defend your country, or you aren’t a good citizen.',
        accepted: ['bw'],
      },
      {
        template:
          '{a} hated my course. {B} must have been very lazy. I only get two kinds of students: energetic ones who love my course and lazy ones who hate it.',
        accepted: ['bw'],
      },
      {
        template:
          'The way I figure it, people are either logical types who have little emotion or else emotional types who care little about logical reasoning.',
        accepted: ['bw'],
      },
      {
        template: '{A}, are you an athlete or an intellectual? Tell me which.',
        accepted: ['bw'],
      },
      {
        template:
          'Either you favor a massive arms buildup, or you aren’t a patriotic American.',
        accepted: ['bw'],
      },
      {
        template:
          'I figure that a person who doesn’t think that the American free enterprise system is the greatest in the world must be a Communist.',
        accepted: ['bw'],
      },
      {
        // Added 2026-08-19. Passages with no date are from the 2008 source.
        template:
          'Either you are with me, or you are my enemy. There is nothing in between.',
        accepted: ['bw'],
        note: 'Between ally and enemy lie most people: the neutral, the undecided, the ally who disagrees. (And the reply in Star Wars — “only a Sith deals in absolutes” — is itself an absolute, and refutes itself.)',
      },
      {
        // Added 2026-08-19. Passages with no date are from the 2008 source.
        template:
          'Either you accept the risk of another Chernobyl, or you close the reactors. There is nothing in between.',
        accepted: ['bw'],
        note: 'There is a great deal in between: siting, safety standards, which reactors, and on what timetable relative to whatever replaces them. Fukushima followed an earthquake and a tsunami, and what that implies for a country with different geology is a real question — one this framing stops anyone from asking.',
      },
    ],
  },
  {
    code: 'ci',
    variants: [
      {
        template:
          'God has to exist, since this world must have been created by a Supreme Being.',
        accepted: ['ci'],
      },
      {
        template: 'The soul is immortal, since it cannot die.',
        accepted: ['ci'],
      },
      {
        template:
          '{a} must like me. {B} told me {b} likes me – and {b} said that {b} always tells the truth to people {b} likes.',
        accepted: ['ci'],
      },
      {
        template:
          'How do I know it? Well, {a} told me. How does {a} know it? Well, I told {hc}.',
        accepted: ['ci'],
      },
      {
        template:
          '{a} must disagree with me, since {b} is irrational. And {a} must be irrational, since {b} disagrees with me.',
        accepted: ['ci'],
      },
      {
        template:
          'Believing in miracles is unreasonable, since no responsible person believes in them. How about {a}? Well, the mere fact that {b} believes in miracles shows that {b} is not responsible.',
        accepted: ['ci'],
      },
      {
        template:
          'The bible must tell the truth. After all, it is God’s word. How do I know that it is God’s word? Well, the bible says it is – and the bible tells the truth.',
        accepted: ['ci'],
      },
      {
        template:
          'The Rolling Stones are the greatest rock group ever – since people with true appreciation for rock prefer this group. I measure one’s appreciation for rock by how the person appreciates this great group.',
        accepted: ['ci'],
      },
      {
        template:
          'You’re wrong in disagreeing with me, {A}, because what you said is an error.',
        accepted: ['ci'],
      },
    ],
  },
  {
    code: 'cq',
    variants: [
      {
        template:
          'Why is the {E} party so much more responsive to the real needs of the people?',
        accepted: ['cq', 'ci'],
        note: 'This violates complex question and perhaps circular.',
      },
      {
        template:
          'Let’s ask how some people could be fooled into thinking that {A} is a better candidate than myself.',
        accepted: ['cq', 'ci'],
        note: 'This violates complex question and perhaps circular.',
      },
      {
        template:
          'The prosecutor asked me, “Where did you hide the money that you stole?”',
        accepted: ['cq', 'ci'],
        note: 'This violates complex question and perhaps circular.',
      },
      {
        template: 'Do you still beat your wife?',
        accepted: ['cq', 'ci'],
        note: 'This violates complex question and perhaps circular.',
      },
      {
        template:
          'So you didn’t like my book, {A}. What defect in your character do you attribute this to?',
        accepted: ['cq', 'ci'],
        note: 'This violates complex question and perhaps circular.',
      },
      {
        template:
          '{a} asked me whether I was still wasting my time at the university.',
        accepted: ['cq', 'ci'],
        note: 'This violates complex question and perhaps circular.',
      },
      {
        template: 'Do you want to be a good little boy and go to bed?',
        accepted: ['cq', 'ci'],
        note: 'This violates complex question and perhaps circular.',
      },
      {
        // Added 2026-08-19. Passages with no date are from the 2008 source.
        template: 'Why do these companies refuse to make their products safe?',
        accepted: ['cq', 'ci'],
        note: 'The question assumes they refuse, which is the very thing in dispute. Answer it either way and you have conceded the point.',
      },
      {
        // Added 2026-08-19. Passages with no date are from the 2008 source.
        template: 'When did {P} decide to stop listening to ordinary people?',
        accepted: ['cq', 'ci'],
        note: 'Any answer concedes that they stopped. The question does the arguing.',
      },
      {
        // Added 2026-08-19. Passages with no date are from the 2008 source.
        template:
          'Why did Jewish communities stay out of the Caribbean entirely?',
        accepted: ['cq', 'ci'],
        note: 'They did not. Sephardim expelled from Iberia settled across the Caribbean, and Port Royal in Jamaica had a synagogue and a street called Jews Street before the 1692 earthquake destroyed it. Some sailed as privateers against Spanish shipping — Moses Cohen Henriques helped take a Spanish treasure fleet in 1628. Answer either way and you have conceded an absence that was never there.',
      },
    ],
  },
  {
    code: 'fs',
    variants: [
      {
        template:
          '{a} is a logician. So {b} must be a non-emotional person. You probably know that logicians are non-emotional.',
        accepted: ['fs'],
      },
      {
        template:
          '{a} is a business major. So, like all other business majors, {b} must be concerned not with ideas but only with making money.',
        accepted: ['fs'],
      },
      {
        template: 'All Italians are lovers.',
        accepted: ['fs'],
      },
      {
        template: 'No New Yorkers care about their fellow human beings.',
        accepted: ['fs'],
      },
      {
        template:
          'In your paper, {A}, you express sympathy with some of the views of Karl Marx. So you must be one of those dangerous sorts who want to overthrow the government.',
        accepted: ['fs'],
      },
      {
        template:
          '{a} made an appointment to see me. But of course {b} didn’t show. {S} are all irresponsible.',
        accepted: ['fs'],
      },
      {
        template:
          'Academic philosophers these days are all logical positivists. None of them accept a spiritual dimension of humanity.',
        accepted: ['fs', 'sm'],
        note: 'This violates false stereotype and straw man.',
      },
      {
        // Added 2026-08-19. Passages with no date are from the 2008 source.
        template:
          'He’s a Lannister. Lannisters always pay their debts. So he’ll pay me what he owes.',
        accepted: ['fs'],
        note: 'Even where a group really does have a reputation, its members are not interchangeable.',
      },
      {
        // Added 2026-08-19. Passages with no date are from the 2008 source.
        template: 'She’s Asian, so she’ll be good at math.',
        accepted: ['fs'],
        note: 'A flattering stereotype is still a stereotype. This one covers nearly five billion people, and it lands on someone as an expectation they never asked for.',
      },
      {
        // Added 2026-08-19. Passages with no date are from the 2008 source.
        template: 'He’s German, so he’ll be punctual.',
        accepted: ['fs'],
        note: 'The same move with a different group and a compliment nobody objects to. That is the point: if the reasoning fails in one, it fails in the other.',
      },
      {
        // Added 2026-08-19. Passages with no date are from the 2008 source.
        template:
          'Steve Jobs was famously brutal with his staff, and he built one of the most valuable companies in the world. So you have to be brutal to build something great.',
        accepted: ['fs'],
        note: 'The unstated premise is that the founders you can name are a fair sample of the founders there are. You never hear about the brutal ones whose companies failed, or the decent ones who succeeded without a documentary.',
      },
    ],
  },
  {
    code: 'ge',
    variants: [
      {
        template:
          'Any good psychologist would recognize why {A} has those beliefs. So these beliefs must be false.',
        accepted: ['ge'],
      },
      {
        template:
          'This new book by {a} explains why Christianity spread so fast in the ancient world. {B} thus refutes Christianity.',
        accepted: ['ge'],
      },
      {
        template:
          'Dr. {a} in {hC} course explains how the modern belief in universal human rights arose in a specific historical context. {B} concludes that there is no objective basis for this belief.',
        accepted: ['ge'],
      },
      {
        template:
          'Belief in God is to be explained in terms of one’s need for a father-figure. Hence this belief is false.',
        accepted: ['ge'],
      },
      {
        template:
          'Religion originated from myth. Myth, of course, consists in superstitious errors. So religion must be false.',
        accepted: ['ge'],
      },
      {
        template:
          'The main reason you buy {d}s is that your family taught you that {d} makes the best cars. So your belief that {d}s are great cars is clearly wrong.',
        accepted: ['ge'],
      },
      {
        // Added 2026-08-19. Passages with no date are from the 2008 source.
        template:
          'The process that makes most of the world’s fertilizer was invented by the man who ran Germany’s chemical weapons program and supervised the first gas attack at Ypres. So we should have nothing to do with it.',
        accepted: ['ge'],
        note: 'Both halves are true of Fritz Haber. About half the world’s people are fed with nitrogen fixed by his process. Where something came from is not what makes it good or bad. The classic form dismisses a belief by its origin; dismissing the process itself is the same move.',
      },
      {
        // Added 2026-08-19. Passages with no date are from the 2008 source.
        template:
          'This argument was written with AI help. So it can’t be a good argument.',
        accepted: ['ge'],
        note: 'An argument is good or bad because of its premises and its structure, not because of what produced it.',
      },
      {
        // Added 2026-08-19. Passages with no date are from the 2008 source.
        template:
          'The study was funded by the Gates Foundation. So its findings must be false.',
        accepted: ['ge'],
        note: 'Who paid for a study is a reason to read it carefully. It is not a reason to conclude it is wrong.',
      },
      {
        // Added 2026-08-19. Passages with no date are from the 2008 source.
        template:
          'Chilies only reached Asia after 1492, carried from the Americas by Portuguese traders. So Sichuan cooking isn’t really Chinese.',
        accepted: ['ge'],
        note: 'Every word of the premise is true. Capsicum was domesticated in the Americas, and Portuguese ships had it in Goa and Malacca within twenty years of Columbus, and in Japan by the 1540s. Where an ingredient came from is not what makes a cuisine someone’s own.',
      },
      {
        // Added 2026-08-19. Passages with no date are from the 2008 source.
        template:
          'The tomato is a New World plant. Many Europeans thought it poisonous for two centuries, and pasta with tomato sauce doesn’t appear in an Italian cookbook until the 1830s. So pasta al pomodoro isn’t really Italian.',
        accepted: ['ge'],
        note: 'Every date holds. Tomatoes reached Europe with the Spanish in the early 1500s, were long shunned in the north as nightshade, and Cavalcanti’s vermicelli con lo pommodoro dates from 1839. A dish is not less a people’s own for having been invented at a particular moment.',
      },
      {
        // Added 2026-08-19. Passages with no date are from the 2008 source.
        template:
          'There wasn’t a single cow anywhere in the Americas until the Spanish brought them after 1493. So the Argentine asado isn’t really Argentine.',
        accepted: ['ge'],
        note: 'Cattle reached the Río de la Plata in the mid-1500s, and with no predators on the Pampas the feral herds ran to millions within a century. Where an animal came from is not what makes a tradition someone’s own.',
      },
      {
        // Added 2026-08-19. Passages with no date are from the 2008 source.
        template:
          'Alface, azeite, almofada, açúcar — hundreds of everyday Portuguese words came from Arabic, during five centuries of Muslim rule. So Portuguese isn’t really a Romance language.',
        accepted: ['ge'],
        note: 'The words are Arabic and the five centuries are real: Muslim rule in the Iberian southwest ran from 711 to 1249. A language is not disqualified from its family by what it borrowed — English would fail the same test twice over.',
      },
    ],
  },
  {
    code: 'op',
    variants: [
      {
        template:
          '{A} and the other dirty {D}s say that we ought to raise taxes. So therefore we shouldn’t do this.',
        accepted: ['op'],
      },
      {
        template:
          'Our enemies – the {D}s – are against this bill. So the bill must be pretty good.',
        accepted: ['op'],
      },
      {
        template:
          'The {D}s have come out in favor of the measure. So we should come out against it.',
        accepted: ['op'],
      },
      {
        // Added 2026-08-19. Passages with no date are from the 2008 source.
        template:
          'Every account I have muted is sharing this study. So there must be something wrong with it.',
        accepted: ['op'],
        note: 'Who else believes something is not evidence about whether it is true.',
      },
      {
        // Added 2026-08-19. Passages with no date are from the 2008 source.
        template: 'My ex loves this restaurant. So it can’t be any good.',
        accepted: ['op'],
        note: 'The fallacy does not need politics to work. Any opponent will do.',
      },
      {
        // Added 2026-08-19. Passages with no date are from the 2008 source.
        template:
          'The union has endorsed the proposal. So management should oppose it.',
        accepted: ['op'],
        note: 'Whether the proposal is any good is a separate question from who is for it.',
      },
      {
        // Added 2026-08-19. Passages with no date are from the 2008 source.
        template:
          '{P} came out in favor of the bill. That settles it for me — I’m against.',
        accepted: ['op'],
        note: 'This is the whole of the reasoning: someone I oppose is for it, so I am against it.',
      },
      {
        // Added 2026-08-19. Passages with no date are from the 2008 source.
        template:
          'Our biggest rivals have started using this training method. So we should stay well away from it.',
        accepted: ['op'],
        note: 'If the method works, it works whoever is using it.',
      },
      {
        // Added 2026-08-19. Passages with no date are from the 2008 source.
        template:
          'The people who have mocked her for a decade are saying the new album is her weakest. So it must actually be one of her best.',
        accepted: ['op'],
        note: 'That her detractors call it her weakest tells you about them, not about the album.',
      },
      {
        // Added 2026-08-19. Passages with no date are from the 2008 source.
        template:
          'The only people who like the album are the Swifties I spend all day arguing with online. So it can’t be any good.',
        accepted: ['op'],
        note: 'Inverting the endorsement of people you oppose is the same mistake as inverting their criticism. Their liking it is not evidence against it.',
      },
    ],
  },
  {
    code: 'pc',
    variants: [
      {
        template:
          '{a} is intelligent and has a lot of experience in politics. So you should vote for {hc}.',
        accepted: ['pc'],
        note: 'Maybe {b}’s a crook. Or maybe {hC} opponent is even more qualified.',
      },
      {
        template:
          '{d}s are inexpensive and get good gas mileage. So you should get a {d}.',
        accepted: ['pc'],
        note: 'What are the disadvantages of getting a {d}?',
      },
      {
        template:
          '{d}s are expensive and hard to get repaired. So you shouldn’t buy one.',
        accepted: ['pc'],
        note: 'What are the advantages of getting a {d}?',
      },
      {
        template:
          'We should legalize gambling in our state because it would be a new source of tax revenue, it would encourage tourists from other states to come and spend money here, and it would cost the state nothing.',
        accepted: ['pc'],
        note: 'What are the disadvantages?',
      },
      {
        // Added 2026-08-19. Passages with no date are from the 2008 source.
        template:
          'The brochure lists eleven benefits of the procedure and no risks at all. So it must be worth doing.',
        accepted: ['pc'],
        note: 'A list with no second column is not a weighing-up.',
      },
      {
        // Added 2026-08-19. Passages with no date are from the 2008 source.
        template:
          'This app is free, it saves you two hours a week, and it sets up in a minute. So obviously you should install it.',
        accepted: ['pc'],
        note: 'Everything stated is an advantage. That is the tell.',
      },
      {
        // Added 2026-08-19. Passages with no date are from the 2008 source.
        template:
          'Moving to the city means a longer commute, higher rent and no garden. So we shouldn’t move.',
        accepted: ['pc'],
        note: 'One-sided in the other direction: only disadvantages are mentioned.',
      },
      {
        // Added 2026-08-19. Passages with no date are from the 2008 source.
        template:
          'The plan will create thousands of jobs and bring investment to the region. So we should approve it.',
        accepted: ['pc'],
        note: 'What the plan costs, and who bears it, is not mentioned at all.',
      },
      {
        // Added 2026-08-19. Passages with no date are from the 2008 source.
        template:
          'We send the EU £350 million a week. Think what our health service could do with that. So we should leave.',
        accepted: ['pc'],
        note: 'That was the gross figure. It left out the rebate, which was never sent, and the money that came back. The UK Statistics Authority called it “a clear misuse of official statistics.”',
      },
      {
        // Added 2026-08-19. Passages with no date are from the 2008 source.
        template:
          'Leaving the EU would leave every household £4,300 worse off by 2030. So we should stay.',
        accepted: ['pc'],
        note: 'A fourteen-year projection, quoted to the nearest hundred pounds, and an aggregate change in output restated as a household loss. One column again — the other one.',
      },
      {
        // Added 2026-08-19. Passages with no date are from the 2008 source.
        template:
          'Rent control means tenants pay less each month than they otherwise would. So we should have rent control.',
        accepted: ['pc'],
        note: 'Everything stated is a benefit, and to one group. What happens to the supply of housing, or to people who do not yet have a tenancy, is not mentioned at all.',
      },
    ],
  },
  {
    code: 'ph',
    variants: [
      {
        template:
          '{a} had a beer before taking the exam. Then {b} got 100%. It’s amazing what a beer can do! I’ll try it next time.',
        accepted: ['ph'],
      },
      {
        template:
          '{a} walked under a ladder. {B} got fired from {hC} job a short time later. This proves again that walking under a ladder will bring you bad luck.',
        accepted: ['ph'],
      },
      {
        template:
          'People who read the Wall Street Journal make more money than average. I’m getting a subscription. Then I’ll make more money than average.',
        accepted: ['ph'],
      },
      {
        template:
          '{a} wore this headband and then kicked two long field goals. The headband brought him good luck.',
        accepted: ['ph'],
      },
      {
        template:
          'Look at all the bad things that happened while my {l} opponent {p} was in office. If you don’t want to elect an official who will bring about such things, then vote against my opponent.',
        accepted: ['ph'],
      },
      {
        template:
          'Whenever I go camping it seems to rain. I’m going backpacking next week. So watch for rain!',
        accepted: ['ph'],
      },
      {
        template:
          'Practically every heroin addict first tried marijuana. So marijuana causes heroin addiction.',
        accepted: ['ph'],
      },
      {
        template:
          'Ms. {a} brushed her teeth with Ultra Zest and then attracted boys like a magnet! Wow – I’m going to get some Ultra Zest, because then I will attract boys too!',
        accepted: ['ph'],
      },
      {
        // Added 2026-08-19. Passages with no date are from the 2008 source.
        template:
          'I started taking the supplement on Monday, and by Friday my cold was gone. So the supplement cured my cold.',
        accepted: ['ph'],
        note: 'Colds go away on their own in about a week. That something happened after something else is not yet a reason to think it happened because of it.',
      },
      {
        // Added 2026-08-19. Passages with no date are from the 2008 source.
        template:
          'I got the booster and felt terrible the next day. So the booster made me ill.',
        accepted: ['ph'],
        note: 'The question is not whether one person felt ill afterwards, but whether people who get it feel ill more often than people who do not.',
      },
      {
        // Added 2026-08-19. Passages with no date are from the 2008 source.
        template:
          'I sent in a donation, and the next month I got a raise. So the donation caused the raise.',
        accepted: ['ph'],
        note: 'The “seed faith” pitch runs on exactly this inference: any good thing that happens after a donation gets credited to the donation.',
      },
      {
        // Added 2026-08-19. Passages with no date are from the 2008 source.
        template:
          'He worked eighteen-hour days for a decade, and the company is now worth billions. So the hours are why it worked.',
        accepted: ['ph'],
        note: 'The premise nobody states is that whatever a successful person did is what made them successful. Plenty of people keep those hours and fail, and plenty succeed without them. You hear about neither.',
      },
      {
        // Added 2026-08-19. Passages with no date are from the 2008 source.
        template:
          'I’ve worn this shirt for every match they’ve won this season. So I need to wear it tonight.',
        accepted: ['ph'],
        note: 'The shirt was there for the wins, and for everything else that happened those days too. Being present is not being the cause.',
      },
    ],
  },
  {
    code: 'pw',
    variants: [
      {
        template:
          'My essay is brilliant. So each part of it must be brilliant.',
        accepted: ['pw'],
      },
      {
        template:
          'Each part of my essay is brilliant. So my essay must be brilliant.',
        accepted: ['pw'],
      },
      {
        template:
          'This is a great team. So {A}, who is on this team, must be a great player.',
        accepted: ['pw'],
      },
      {
        template:
          '{A}, who is on this team, is a great player. So this must be a great team.',
        accepted: ['pw'],
      },
      {
        template:
          'Each person in this country desires his or her own happiness. So the country as a whole must desire the happiness of the whole country.',
        accepted: ['pw'],
      },
      {
        template:
          'I kept thinking “One little drink won’t hurt” as I had one little drink. I repeated this reasoning ten times.',
        accepted: ['pw'],
      },
      {
        template:
          'Each thing in the universe comes into existence and later passes out of existence. So the universe also must have come into existence and must later pass out of existence.',
        accepted: ['pw'],
      },
      {
        template:
          'This used {d} won’t cost you much. The payments will only come to about $\\$20$ a day. Now $\\$20$ is not much at all these days.',
        accepted: ['pw'],
      },
      {
        template:
          'Each part of life has a purpose. Your eyes, hands, and so forth all have a purpose. Hence life itself must have a purpose.',
        accepted: ['pw'],
      },
      {
        // Added 2026-08-19. Passages with no date are from the 2008 source.
        template:
          'India has one of the largest economies in the world. So the average person in India must be well off.',
        accepted: ['pw'],
        note: 'True of the whole, not of the parts. A very large economy divided among a very large population is a different quantity altogether.',
      },
      {
        // Added 2026-08-19. Passages with no date are from the 2008 source.
        template:
          'It has been the coldest week here in twenty years. So much for global warming.',
        accepted: ['pw'],
        note: 'One week in one place is not the global average across decades, which is the quantity the phrase names. What holds of a part need not hold of the whole.',
      },
    ],
  },
  {
    code: 'sm',
    variants: [
      {
        template:
          '({a} proposes cutting defense spending by 10%.) My opponent {a} wants to disarm our country and hand it over on a silver platter to our enemies.',
        accepted: ['sm'],
      },
      {
        template:
          '({a} suggests closing some of the seldom used rapid transit stops.) {a}, my opponent for mayor, evidently wants to shut down all public transportation for our city!',
        accepted: ['sm'],
      },
      {
        template:
          'I oppose this bill. Contrary to what the {D}s think, this bill won’t solve all of our problems.',
        accepted: ['sm'],
      },
      {
        template:
          '{a} and the other feminists deny all difference between male and female. But this is absurd, as anyone with eyes can see.',
        accepted: ['sm', 'fs'],
        note: 'This violates straw man and false stereotype.',
      },
      {
        template:
          '{a} and the other atheists are pretty stupid. They deny God’s existence because they can’t see him. But who has seen electrons either?',
        accepted: ['sm', 'fs'],
        note: 'This violates straw man and false stereotype.',
      },
      {
        template:
          '{a} and the other Christians are pretty stupid. They all believe that the world was created in six days. None of them cares anything about science.',
        accepted: ['sm', 'fs'],
        note: 'This violates straw man and false stereotype.',
      },
      {
        // Added 2026-08-19. Passages with no date are from the 2008 source.
        template:
          '(A colleague suggests the team try a four-day week for one month.) So you want us to just stop working. Got it.',
        accepted: ['sm'],
        note: 'A one-month trial of four days is not a proposal to stop working.',
      },
      {
        // Added 2026-08-19. Passages with no date are from the 2008 source.
        template:
          '(Someone points out that the population is still growing.) So you’re Thanos now. You want to wipe out half of everyone.',
        accepted: ['sm'],
        note: 'Noting a fact about population is not proposing to do anything about it, let alone that.',
      },
    ],
  },
];

export const SURNAMES = [
  'Martinez',
  'Smith',
  'Jones',
  'Brown',
  'Greene',
  'Fernandez',
  'Connolly',
  'Wong',
  'Weiss',
  'Gensler',
  'Wilson',
  'Rogers',
  'Hilton',
  'Miller',
  'Boyle',
  'Hughes',
  'Santos',
  'Reyes',
  'Cruz',
  'Bautista',
  'Tan',
  'Lim',
  'Patel',
  'Singh',
  'Nakamura',
  'Ahmed',
  'Kim',
  'Silva',
  'Nguyen',
  'Garcia',
  'Rodriguez',
  'Lee',
];

export const CARS = [
  'Honda',
  'Ford',
  'Chevrolet',
  'Toyota',
  'Volkswagen',
  'Tesla',
  'Hyundai',
  'Kia',
  'Nissan',
  'Subaru',
  'Mazda',
  'BMW',
  'Audi',
  'Volvo',
  'Ferrari',
];

/** Affiliation groups for the {s}/{S} token. Chosen affiliations only. */
export const GROUPS = [
  'boomers',
  'millennials',
  'zoomers',
  'vegans',
  'gamers',
  'cyclists',
  'crypto investors',
  'influencers',
  'homeschoolers',
  'journalists',
  'academics',
  'lawyers',
  'bankers',
  'economists',
  'consultants',
  'landlords',
  'environmentalists',
  'activists',
  'libertarians',
  'nationalists',
  'populists',
  'preppers',
];

/** Footballers for the {f} token (opinion-headcount passages only). */
export const PLAYERS = ['Ronaldo', 'Messi', 'Haaland', 'Mbappé'];

/** Named political figures: {p}/{P} render the name, {l} their own label. */
export const POLITICIANS = [
  {
    name: 'Orbán',
    label: 'nationalist',
    b: 'he',
    B: 'He',
    hc: 'him',
    hC: 'his',
    HC: 'His',
  },
  {
    name: 'Meloni',
    label: 'nationalist',
    b: 'she',
    B: 'She',
    hc: 'her',
    hC: 'her',
    HC: 'Her',
  },
  {
    name: 'Reagan',
    label: 'conservative',
    b: 'he',
    B: 'He',
    hc: 'him',
    hC: 'his',
    HC: 'His',
  },
  {
    name: 'Thatcher',
    label: 'conservative',
    b: 'she',
    B: 'She',
    hc: 'her',
    hC: 'her',
    HC: 'Her',
  },
  {
    name: 'Milei',
    label: 'libertarian',
    b: 'he',
    B: 'He',
    hc: 'him',
    hC: 'his',
    HC: 'His',
  },
  {
    name: 'Merkel',
    label: 'christian democrat',
    b: 'she',
    B: 'She',
    hc: 'her',
    hC: 'her',
    HC: 'Her',
  },
  {
    name: 'Macron',
    label: 'centrist',
    b: 'he',
    B: 'He',
    hc: 'him',
    hC: 'his',
    HC: 'His',
  },
  {
    name: 'Obama',
    label: 'democrat',
    b: 'he',
    B: 'He',
    hc: 'him',
    hC: 'his',
    HC: 'His',
  },
  {
    name: 'Blair',
    label: 'labour',
    b: 'he',
    B: 'He',
    hc: 'him',
    hC: 'his',
    HC: 'His',
  },
  {
    name: 'Starmer',
    label: 'labour',
    b: 'he',
    B: 'He',
    hc: 'him',
    hC: 'his',
    HC: 'His',
  },
  {
    name: 'Ardern',
    label: 'progressive',
    b: 'she',
    B: 'She',
    hc: 'her',
    hC: 'her',
    HC: 'Her',
  },
  {
    name: 'Sanders',
    label: 'socialist',
    b: 'he',
    B: 'He',
    hc: 'him',
    hC: 'his',
    HC: 'His',
  },
  {
    name: 'Mamdani',
    label: 'democratic socialist',
    b: 'he',
    B: 'He',
    hc: 'him',
    hC: 'his',
    HC: 'His',
  },
  {
    name: 'Trump',
    label: 'republican',
    b: 'he',
    B: 'He',
    hc: 'him',
    hC: 'his',
    HC: 'His',
  },
  {
    name: 'Modi',
    label: 'nationalist',
    b: 'he',
    B: 'He',
    hc: 'him',
    hC: 'his',
    HC: 'His',
  },
  {
    name: 'Harris',
    label: 'democrat',
    b: 'she',
    B: 'She',
    hc: 'her',
    hC: 'her',
    HC: 'Her',
  },
  {
    name: 'Hillary Clinton',
    label: 'democrat',
    b: 'she',
    B: 'She',
    hc: 'her',
    hC: 'her',
    HC: 'Her',
  },
  {
    name: 'John F. Kennedy',
    label: 'democrat',
    b: 'he',
    B: 'He',
    hc: 'him',
    hC: 'his',
    HC: 'His',
  },
];

/** Party pools: {D} renders the noun, {E} the adjective (democrat -> democratic). */
export const PARTIES = [
  { noun: 'socialist', adj: 'socialist' },
  { noun: 'republican', adj: 'republican' },
  { noun: 'democrat', adj: 'democratic' },
  { noun: 'conservative', adj: 'conservative' },
  { noun: 'liberal', adj: 'liberal' },
  { noun: 'progressive', adj: 'progressive' },
  { noun: 'libertarian', adj: 'libertarian' },
  { noun: 'populist', adj: 'populist' },
  { noun: 'nationalist', adj: 'nationalist' },
  { noun: 'green', adj: 'green' },
];

/** Pronoun bundles; one is chosen per passage so pronouns agree throughout. */
export const GENDERS = [
  { b: 'he', B: 'He', hc: 'him', hC: 'his', HC: 'His' },
  { b: 'she', B: 'She', hc: 'her', hC: 'her', HC: 'Her' },
];
